(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.lnav2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.6)").s().p("AgmCOIAAgUIAhAAIAAj4IB7AAIAAD4IAbAAIAAAUgAAOB6IBSAAIAAhAIhSAAgAAOAmIBSAAIAAg+IhSAAgAAOgsIBSAAIAAg9IhSAAgAiPBqIAggGIAmgIIAogKIACASIg5AOIgyAOgAiKA5IgEgKQAFgCAGgFIAOgPIAPgRIAXgcIgjAFIgRADIgHACIgCgKIgEgKQAEgBAEgFIALgOIAMgTQAJgPAJgSQAKgTAIgUIATAJQgMAbgPAZQgOAZgQAWIAxgGIALgRIALgSIARALQgRAcgUAZQgTAZgVAWIBJgOIAAAKIAAAIIg0ALIgeAGIgQAEIgHAEIgCgJg");
	this.shape.setTransform(140.225,23.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.6)").s().p("AhgCTIAAiLIDEAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiNgTIAAgUIBSAAQgCgLgFgNQgFgNgHgLIAUgFQAFAIAEAJQAFAIADAJIAFAQIgOADIBXAAIAJgRIAIgUIAGgRIAXAGIgLAYIgNAYIBSAAIAAAUgAh6hfIAAgTIB0AAIgFgOIgHgOIAUgEIAJAQIAHAQIBsAAIAAATg");
	this.shape_1.setTransform(108.2,24.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.6)").s().p("ABQCSIAAhRIgqAAIAAgSIAqAAIAAgvIgvAAIAAgSIA/AAIAHgUIAHgWIAFgUIASAEIgKAeIgKAcIAhAAIAAASIguAAIAAAvIApAAIAAASIgpAAIAABRgAiECKQgEgEgEgDQAPgKAJgMQAHgNAEgNQADgOABgNIgnAAIAAgSIAnAAIAAgnIgrAAIAAgSIA9AAIAGgTIAGgWIADgTIASAEIgIAdIgJAbIAcAAIAAASIgqAAIAAAnIAnAAIAAASIgnAAQgCAPgEARQgDAQgKAPQgKAPgQALIgGgHgAgqCJIgHgHQAZgVANgZQAMgZADgcQAEgcAAgcIAAh1IASAAIAAB1QAAAYgCAWQgCAYgGAVQgGAWgNAUQgMATgUARIgHgHgAgmAPQAEgMADgQQADgQACgRIABghIAQACQAAAQgCARQgBASgDARQgCAQgFANgAA6glIgDgTIgHgTIARgCIAGASIAEASIACARIgRADIgCgQgAh4glIgDgTIgGgTIAQgDIAGASIAEATIACARIgRADIgCgQgAiNhUIAAgSIAtAAIgJgSIgIgSIASgFIAKAVIAJAUIAjAAIAAASgAAmhUIAAgSIAuAAIgIgTIgJgTIARgFIAMAVIAJAWIAkAAIAAASg");
	this.shape_2.setTransform(76.25,24.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.6)").s().p("ABLCRIAAimIhCAAQAAAYgEAeQgDAdgHAdQgJAdgSAYIgIgIIgKgGQARgXAJgcQAHgcADgcQADgbgBgZIAAhTIArgJIApgLQAUgGANgGIASARQgPAGgTAFIgoAKIgoAJIAAA3ICCAAIAAAVIgrAAIAACmgAiKBcIAAjQIBWAAIAAC3IhCAAIAAAZgAh2AvIAtAAIAAiPIgtAAg");
	this.shape_3.setTransform(44.65,24.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(0,0,0,0.6)").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_4.setTransform(23.85,34.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(0,0,0,0.6)").s().p("AhHB3IAAgPQA4gxAZglQAbglgBgeQAAgOgFgKQgEgLgKgHQgKgGgOAAQgPAAgMAIQgNAIgKAMIgPgPQANgQARgJQAQgJAWAAQAeAAASASQASATAAAfQAAAYgMAYQgLAXgWAaQgUAZgcAbIATgCIASAAIBDAAIAAAWg");
	this.shape_5.setTransform(10.625,24.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F7C677").s().p("AgmCOIAAgUIAhAAIAAj4IB7AAIAAD4IAbAAIAAAUgAAOB6IBSAAIAAhAIhSAAgAAOAmIBSAAIAAg+IhSAAgAAOgsIBSAAIAAg9IhSAAgAiPBqIAggGIAmgIIAogKIACASIg5AOIgyAOgAiKA5IgEgKQAFgCAGgFIAOgPIAPgRIAXgcIgjAFIgRADIgHACIgCgKIgEgKQAEgBAEgFIALgOIAMgTQAJgPAJgSQAKgTAIgUIATAJQgMAbgPAZQgOAZgQAWIAxgGIALgRIALgSIARALQgRAcgUAZQgTAZgVAWIBJgOIAAAKIAAAIIg0ALIgeAGIgQAEIgHAEIgCgJg");
	this.shape_6.setTransform(140.225,23.85);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F7C677").s().p("AhgCTIAAiLIDEAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiNgTIAAgUIBSAAQgCgLgFgNQgFgNgHgLIAUgFQAFAIAEAJQAFAIADAJIAFAQIgOADIBXAAIAJgRIAIgUIAGgRIAXAGIgLAYIgNAYIBSAAIAAAUgAh6hfIAAgTIB0AAIgFgOIgHgOIAUgEIAJAQIAHAQIBsAAIAAATg");
	this.shape_7.setTransform(108.2,24.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F7C677").s().p("ABQCSIAAhRIgqAAIAAgSIAqAAIAAgvIgvAAIAAgSIA/AAIAHgUIAHgWIAFgUIASAEIgKAeIgKAcIAhAAIAAASIguAAIAAAvIApAAIAAASIgpAAIAABRgAiECKQgEgEgEgDQAPgKAJgMQAHgNAEgNQADgOABgNIgnAAIAAgSIAnAAIAAgnIgrAAIAAgSIA9AAIAGgTIAGgWIADgTIASAEIgIAdIgJAbIAcAAIAAASIgqAAIAAAnIAnAAIAAASIgnAAQgCAPgEARQgDAQgKAPQgKAPgQALIgGgHgAgqCJIgHgHQAZgVANgZQAMgZADgcQAEgcAAgcIAAh1IASAAIAAB1QAAAYgCAWQgCAYgGAVQgGAWgNAUQgMATgUARIgHgHgAgmAPQAEgMADgQQADgQACgRIABghIAQACQAAAQgCARQgBASgDARQgCAQgFANgAA6glIgDgTIgHgTIARgCIAGASIAEASIACARIgRADIgCgQgAh4glIgDgTIgGgTIAQgDIAGASIAEATIACARIgRADIgCgQgAiNhUIAAgSIAtAAIgJgSIgIgSIASgFIAKAVIAJAUIAjAAIAAASgAAmhUIAAgSIAuAAIgIgTIgJgTIARgFIAMAVIAJAWIAkAAIAAASg");
	this.shape_8.setTransform(76.25,24.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F7C677").s().p("ABLCRIAAimIhCAAQAAAYgEAeQgDAdgHAdQgJAdgSAYIgIgIIgKgGQARgXAJgcQAHgcADgcQADgbgBgZIAAhTIArgJIApgLQAUgGANgGIASARQgPAGgTAFIgoAKIgoAJIAAA3ICCAAIAAAVIgrAAIAACmgAiKBcIAAjQIBWAAIAAC3IhCAAIAAAZgAh2AvIAtAAIAAiPIgtAAg");
	this.shape_9.setTransform(44.65,24.275);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F7C677").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_10.setTransform(23.85,34.675);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F7C677").s().p("AhHB3IAAgPQA4gxAZglQAbglgBgeQAAgOgFgKQgEgLgKgHQgKgGgOAAQgPAAgMAIQgNAIgKAMIgPgPQANgQARgJQAQgJAWAAQAeAAASASQASATAAAfQAAAYgMAYQgLAXgWAaQgUAZgcAbIATgCIASAAIBDAAIAAAWg");
	this.shape_11.setTransform(10.625,24.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).wait(2));

	// 图层_2
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AyfEUIAAonMAk/AAAIAAIng");
	this.shape_12.setTransform(114.675,22.775);

	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.7,-4.8,236.79999999999998,55.199999999999996);


(lib.lnav1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.6)").s().p("AhcCQIAAiMQgIAZgLAWQgLAWgLAPIgFgKIgHgKQAJgMAKgRQAJgRAIgUQAIgSAGgTIgrAAIAAgUIAuAAIAAg2IgRAEIgSADIgDgIIgEgIIAfgHIAegJQAOgEAJgFIAOARIgRAGIgTAGIAAA7IAoAAIAAAUIgoAAIAAAIIAJAMIALAPIALAQIAHALIgNASIgHgNIgJgRIgJgQIAACRgAgmCIIAAgUIBUAAIAAgvIg/AAIAAgUIA/AAIAAgrIhGAAIAAgTICjAAIAAATIhIAAIAAArIBCAAIAAAUIhCAAIAAAvIBPAAIAAAUgAgSgqIAAhdICSAAIAABdgAABg8IBqAAIAAg4IhqAAg");
	this.shape.setTransform(140,24.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.6)").s().p("AhgCTIAAiLIDEAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiNgTIAAgUIBSAAQgCgLgFgNQgFgNgHgLIAUgFQAFAIAEAJQAFAIADAJIAFAQIgOADIBXAAIAJgRIAIgUIAGgRIAXAGIgLAYIgNAYIBSAAIAAAUgAh6hfIAAgTIB0AAIgFgOIgHgOIAUgEIAJAQIAHAQIBsAAIAAATg");
	this.shape_1.setTransform(108.2,24.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.6)").s().p("ABQCSIAAhRIgqAAIAAgSIAqAAIAAgvIgvAAIAAgSIA/AAIAHgUIAHgWIAFgUIASAEIgKAeIgKAcIAhAAIAAASIguAAIAAAvIApAAIAAASIgpAAIAABRgAiECKQgEgEgEgDQAPgKAJgMQAHgNAEgNQADgOABgNIgnAAIAAgSIAnAAIAAgnIgrAAIAAgSIA9AAIAGgTIAGgWIADgTIASAEIgIAdIgJAbIAcAAIAAASIgqAAIAAAnIAnAAIAAASIgnAAQgCAPgEARQgDAQgKAPQgKAPgQALIgGgHgAgqCJIgHgHQAZgVANgZQAMgZADgcQAEgcAAgcIAAh1IASAAIAAB1QAAAYgCAWQgCAYgGAVQgGAWgNAUQgMATgUARIgHgHgAgmAPQAEgMADgQQADgQACgRIABghIAQACQAAAQgCARQgBASgDARQgCAQgFANgAA6glIgDgTIgHgTIARgCIAGASIAEASIACARIgRADIgCgQgAh4glIgDgTIgGgTIAQgDIAGASIAEATIACARIgRADIgCgQgAiNhUIAAgSIAtAAIgJgSIgIgSIASgFIAKAVIAJAUIAjAAIAAASgAAmhUIAAgSIAuAAIgIgTIgJgTIARgFIAMAVIAJAWIAkAAIAAASg");
	this.shape_2.setTransform(76.25,24.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.6)").s().p("ABLCRIAAimIhCAAQAAAYgEAeQgDAdgHAdQgJAdgSAYIgIgIIgKgGQARgXAJgcQAHgcADgcQADgbgBgZIAAhTIArgJIApgLQAUgGANgGIASARQgPAGgTAFIgoAKIgoAJIAAA3ICCAAIAAAVIgrAAIAACmgAiKBcIAAjQIBWAAIAAC3IhCAAIAAAZgAh2AvIAtAAIAAiPIgtAAg");
	this.shape_3.setTransform(44.65,24.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(0,0,0,0.6)").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_4.setTransform(23.85,34.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(0,0,0,0.6)").s().p("Ag+B1IAAgVIA0AAIAAizIgpAAIAAgSQAPgCAMgEQALgEAKgFIASAAIAADUIAwAAIAAAVg");
	this.shape_5.setTransform(11.15,24.65);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(241,171,78,0.4)").s().p("AhcCQIAAiMQgIAZgLAWQgLAWgLAPIgFgKIgHgKQAJgMAKgRQAJgRAIgUQAIgSAGgTIgrAAIAAgUIAuAAIAAg2IgRAEIgSADIgDgIIgEgIIAfgHIAegJQAOgEAJgFIAOARIgRAGIgTAGIAAA7IAoAAIAAAUIgoAAIAAAIIAJAMIALAPIALAQIAHALIgNASIgHgNIgJgRIgJgQIAACRgAgmCIIAAgUIBUAAIAAgvIg/AAIAAgUIA/AAIAAgrIhGAAIAAgTICjAAIAAATIhIAAIAAArIBCAAIAAAUIhCAAIAAAvIBPAAIAAAUgAgSgqIAAhdICSAAIAABdgAABg8IBqAAIAAg4IhqAAg");
	this.shape_6.setTransform(140,24.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(241,171,78,0.4)").s().p("AhgCTIAAiLIDEAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiNgTIAAgUIBSAAQgCgLgFgNQgFgNgHgLIAUgFQAFAIAEAJQAFAIADAJIAFAQIgOADIBXAAIAJgRIAIgUIAGgRIAXAGIgLAYIgNAYIBSAAIAAAUgAh6hfIAAgTIB0AAIgFgOIgHgOIAUgEIAJAQIAHAQIBsAAIAAATg");
	this.shape_7.setTransform(108.2,24.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(241,171,78,0.4)").s().p("ABQCSIAAhRIgqAAIAAgSIAqAAIAAgvIgvAAIAAgSIA/AAIAHgUIAHgWIAFgUIASAEIgKAeIgKAcIAhAAIAAASIguAAIAAAvIApAAIAAASIgpAAIAABRgAiECKQgEgEgEgDQAPgKAJgMQAHgNAEgNQADgOABgNIgnAAIAAgSIAnAAIAAgnIgrAAIAAgSIA9AAIAGgTIAGgWIADgTIASAEIgIAdIgJAbIAcAAIAAASIgqAAIAAAnIAnAAIAAASIgnAAQgCAPgEARQgDAQgKAPQgKAPgQALIgGgHgAgqCJIgHgHQAZgVANgZQAMgZADgcQAEgcAAgcIAAh1IASAAIAAB1QAAAYgCAWQgCAYgGAVQgGAWgNAUQgMATgUARIgHgHgAgmAPQAEgMADgQQADgQACgRIABghIAQACQAAAQgCARQgBASgDARQgCAQgFANgAA6glIgDgTIgHgTIARgCIAGASIAEASIACARIgRADIgCgQgAh4glIgDgTIgGgTIAQgDIAGASIAEATIACARIgRADIgCgQgAiNhUIAAgSIAtAAIgJgSIgIgSIASgFIAKAVIAJAUIAjAAIAAASgAAmhUIAAgSIAuAAIgIgTIgJgTIARgFIAMAVIAJAWIAkAAIAAASg");
	this.shape_8.setTransform(76.25,24.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(241,171,78,0.4)").s().p("ABLCRIAAimIhCAAQAAAYgEAeQgDAdgHAdQgJAdgSAYIgIgIIgKgGQARgXAJgcQAHgcADgcQADgbgBgZIAAhTIArgJIApgLQAUgGANgGIASARQgPAGgTAFIgoAKIgoAJIAAA3ICCAAIAAAVIgrAAIAACmgAiKBcIAAjQIBWAAIAAC3IhCAAIAAAZgAh2AvIAtAAIAAiPIgtAAg");
	this.shape_9.setTransform(44.65,24.275);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(241,171,78,0.4)").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_10.setTransform(23.85,34.675);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(241,171,78,0.4)").s().p("Ag+B1IAAgVIA0AAIAAizIgpAAIAAgSQAPgCAMgEQALgEAKgFIASAAIAADUIAwAAIAAAVg");
	this.shape_11.setTransform(11.15,24.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).wait(3));

	// 图层_2
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AyfEUIAAonMAk/AAAIAAIng");
	this.shape_12.setTransform(118.425,18.625);

	this.timeline.addTween(cjs.Tween.get(this.shape_12).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-9,236.9,57);


// stage content:
(lib.复习 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {lnav1:0,lnav2:5};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,5];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		
		var _this = this;
		
		
		
		_this.lnav1_btn.on('click', function(){
		
		_this.gotoAndStop('lnav1');
		});
		
		
		_this.lnav2_btn.on('click', function(){
		
		_this.gotoAndStop('lnav2');
		});
	}
	this.frame_5 = function() {
		this.stop();
		
		
		
		
		var _this = this;
		/*
		单击指定元件实例时将执行相应函数。
		*/
		_this.m1_btn.on('click', function(){
		/*
		将播放头移动到时间轴中的指定帧标签并继续从该帧播放。
		可在主时间轴或影片剪辑时间轴上使用。
		*/
		_this.gotoAndPlay('m1');
		});
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(5).call(this.frame_5).wait(5));

	// leftnav_on
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E28624").s().p("AhcCQIAAiMQgIAZgLAWQgKAWgLAPIgHgKIgGgKQAKgMAJgRQAJgRAIgUQAIgSAGgTIgrAAIAAgUIAuAAIAAg2IgSAEIgRADIgDgIIgDgIIAegHIAegJQANgEAKgFIAPARIgSAGIgTAGIAAA7IAoAAIAAAUIgoAAIAAAIIAJAMIALAPIALAQIAIALIgPASIgGgNIgIgRIgKgQIAACRgAgmCIIAAgUIBUAAIAAgvIg+AAIAAgUIA+AAIAAgrIhGAAIAAgTICjAAIAAATIhIAAIAAArIBBAAIAAAUIhBAAIAAAvIBPAAIAAAUgAgRgqIAAhdICRAAIAABdgAACg8IBpAAIAAg4IhpAAg");
	this.shape.setTransform(242.3,442.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E28624").s().p("AhfCTIAAiLIDDAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiMgTIAAgUIBSAAQgCgLgGgNQgFgNgHgLIAUgFQAGAIAEAJQAEAIADAJIAEAQIgNADIBWAAIAJgRIAJgUIAGgRIAYAGIgNAYIgMAYIBSAAIAAAUgAh6hfIAAgTIB1AAIgGgOIgIgOIAVgEIAJAQIAGAQIBtAAIAAATg");
	this.shape_1.setTransform(210.5,442.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E28624").s().p("ABPCSIAAhRIgpAAIAAgSIApAAIAAgvIguAAIAAgSIA/AAIAIgUIAGgWIAFgUIASAEIgKAeIgKAcIAhAAIAAASIgvAAIAAAvIAqAAIAAASIgqAAIAABRgAiECKQgDgEgEgDQAOgKAIgMQAIgNAEgNQADgOABgNIgnAAIAAgSIAnAAIAAgnIgsAAIAAgSIA+AAIAGgTIAFgWIAFgTIASAEIgJAdIgIAbIAbAAIAAASIgqAAIAAAnIAoAAIAAASIgpAAQgBAPgDARQgFAQgJAPQgKAPgQALIgGgHgAgpCJIgHgHQAZgVAMgZQALgZAFgcQADgcAAgcIAAh1IASAAIAAB1QAAAYgCAWQgCAYgGAVQgHAWgMAUQgMATgVARIgFgHgAgmAPQAEgMADgQQADgQABgRIACghIAPACQABAQgCARQAAASgDARQgEAQgEANgAA7glIgFgTIgFgTIAQgCIAFASIAFASIADARIgSADIgBgQgAh4glIgDgTIgGgTIAQgDIAGASIAEATIACARIgRADIgCgQgAiNhUIAAgSIAtAAIgIgSIgJgSIASgFIALAVIAJAUIAiAAIAAASgAAmhUIAAgSIAvAAIgIgTIgKgTIASgFIALAVIAJAWIAkAAIAAASg");
	this.shape_2.setTransform(178.55,442.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E28624").s().p("ABLCRIAAimIhCAAQAAAYgDAeQgEAdgHAdQgKAdgRAYIgIgIIgKgGQARgXAIgcQAJgcACgcQACgbAAgZIAAhTIArgJIApgLQATgGAOgGIATARQgQAGgTAFIgnAKIgpAJIAAA3ICCAAIAAAVIgrAAIAACmgAiJBcIAAjQIBVAAIAAC3IhCAAIAAAZgAh2AvIAtAAIAAiPIgtAAg");
	this.shape_3.setTransform(146.95,442.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E28624").s().p("AgNAPQgFgFgBgJQABgJAFgGQAGgFAHgBQAIABAGAFQAGAGgBAJQABAJgGAFQgGAGgIAAQgHAAgGgGg");
	this.shape_4.setTransform(126.15,452.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E28624").s().p("Ag+B1IAAgVIA1AAIAAizIgqAAIAAgRQAPgDAMgEQAMgDAJgGIATAAIAADUIAvAAIAAAVg");
	this.shape_5.setTransform(113.45,442.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E28624").s().p("AgmCOIAAgTIAhAAIAAj5IB7AAIAAD5IAbAAIAAATgAAOB7IBSAAIAAhBIhSAAgAAOAmIBSAAIAAg/IhSAAgAAOgsIBSAAIAAg+IhSAAgAiPBqIAggGIAmgJIAogJIACASIg5AOIgyANgAiKA5IgEgLQAFgBAGgFIAOgPIAPgRIAXgcIgjAFIgRADIgHACIgCgKIgEgKQAEgBAEgFIALgOIAMgUQAJgOAJgSQAKgTAIgUIATAIQgMAbgPAaQgOAagQAUIAxgFIALgRIALgSIARALQgRAcgUAZQgTAZgVAWIBJgNIAAAJIAAAJIg0AKIgeAHIgQADIgHAEIgCgJg");
	this.shape_6.setTransform(244.475,505.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E28624").s().p("AhgCTIAAiLIDEAAIAACLIgWAAIAAgMIiYAAIAAAMgAhKB1ICYAAIAAglIiYAAgAhKA+ICYAAIAAgjIiYAAgAiNgTIAAgUIBSAAQgBgLgGgNQgFgNgHgLIAUgFQAFAIAFAJQAEAIADAJIAFAQIgOADIBWAAIAJgRIAJgUIAHgRIAWAGIgMAYIgMAYIBTAAIAAAUgAh6hfIAAgTIB0AAIgFgOIgHgOIATgEIAJAQIAHAQIBtAAIAAATg");
	this.shape_7.setTransform(212.45,505.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E28624").s().p("ABQCSIAAhRIgqAAIAAgSIAqAAIAAgvIguAAIAAgSIA/AAIAHgUIAGgWIAFgUIASAEIgJAeIgKAcIAfAAIAAASIguAAIAAAvIAqAAIAAASIgqAAIAABRgAiECKQgDgEgFgDQAPgKAIgMQAJgNACgNQAEgOABgNIgnAAIAAgSIAnAAIAAgnIgrAAIAAgSIA9AAIAGgTIAFgWIAEgTIASAEIgIAdIgIAbIAcAAIAAASIgrAAIAAAnIAnAAIAAASIgnAAQgBAPgFARQgDAQgKAPQgJAPgRALIgGgHgAgqCJIgGgHQAYgVANgZQALgZAFgcQADgcAAgcIAAh1IASAAIAAB1QAAAYgCAWQgCAYgGAVQgGAWgMAUQgNATgVARIgGgHgAgmAPQAFgMACgQQADgQABgRIACghIAQACQAAAQgBARQgBASgEARQgDAQgEANgAA7glIgFgTIgGgTIAQgCIAHASIAEASIADARIgRADIgCgQgAh4glIgEgTIgFgTIAQgDIAGASIAEATIACARIgRADIgCgQgAiNhUIAAgSIAsAAIgIgSIgIgSIASgFIALAVIAJAUIAiAAIAAASgAAlhUIAAgSIAvAAIgHgTIgKgTIARgFIAMAVIAKAWIAjAAIAAASg");
	this.shape_8.setTransform(180.5,505.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E28624").s().p("ABKCRIAAimIhBAAQAAAYgDAeQgEAdgIAdQgIAdgSAYIgJgIIgJgGQARgXAIgcQAJgcACgcQACgbAAgZIAAhTIAqgJIAqgLQAUgGANgGIATARQgQAGgTAFIgoAKIgoAJIAAA3ICBAAIAAAVIgqAAIAACmgAiJBcIAAjQIBVAAIAAC3IhBAAIAAAZgAh1AvIAtAAIAAiPIgtAAg");
	this.shape_9.setTransform(148.9,506.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E28624").s().p("AgNAPQgGgFABgJQgBgJAGgGQAGgFAHgBQAIABAGAFQAFAGABAJQgBAJgFAFQgGAGgIAAQgHAAgGgGg");
	this.shape_10.setTransform(128.1,516.425);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E28624").s().p("AhHB3IAAgPQA4gxAZglQAbglgBgeQAAgOgFgKQgEgLgKgHQgKgGgOAAQgPAAgMAIQgNAIgKAMIgPgPQANgQARgJQAQgJAWAAQAeAAASASQASATAAAfQAAAYgMAYQgLAXgWAaQgUAZgcAbIATgCIASAAIBDAAIAAAWg");
	this.shape_11.setTransform(114.875,506.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},5).wait(5));

	// leftnav
	this.lnav2_btn = new lib.lnav2();
	this.lnav2_btn.name = "lnav2_btn";
	this.lnav2_btn.setTransform(151.45,505.75,1,1,0,0,0,47.2,24);
	new cjs.ButtonHelper(this.lnav2_btn, 0, 1, 2, false, new lib.lnav2(), 3);

	this.lnav1_btn = new lib.lnav1();
	this.lnav1_btn.name = "lnav1_btn";
	this.lnav1_btn.setTransform(149.5,442.1,1,1,0,0,0,47.2,24);
	new cjs.ButtonHelper(this.lnav1_btn, 0, 1, 2, false, new lib.lnav1(), 3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(153,153,153,0.498)").s().p("AAgBoIAAgxQgJALgNALQgMAKgNAHIgFgFIgGgFQAOgGAMgJQAMgJAIgKIAMAEIAAgrIgWACIgWABIgBgFIgDgGIAjgDIAigDIAbgFIANAKIgWAEIgZADIAAAYIAEAFIADAEIAUgNIARgMIAKAIIgTANIgVAMQAKAKANAHQAMAHAOAFQgDABgCAEIgEAGQgQgGgNgKQgOgKgLgMIAAA0gAhCBoIgNgBIgBgHIgDgGIANABIAJAAIAEgBIADgCQADgCACgJIAEgYIADgpIg3AAIADgYIADgdIACgcIANABIgCAXIgCAXIgCAWIAYAAIAEgbIACgeIADgeIg0AAIAAgOIBCAAIgCAiIgEAkIgDAfIAGAAIALAAIAAACIAAAEQgCAegCATQgCATgDAKQgCAKgEADIgGAFIgIACIgKAAgAhsAxIAagGIAegIIABANIgcAIIgaAHgAgSA0IgFgFIAVgMQAKgHAHgHIANAEQgJAJgLAIQgKAJgLAFIgFgEgAAZgFIAAgOIgaAEIgYADIgDgMIAOgCIAAhBIgLAAIAAgMIBGAAIAAAMIgIAAIAAA7IAIgBIAAALIgIABIAAAQgAgCgbIAbgEIAAgNIgbAAgAgCg2IAbAAIAAgOIgbAAgAgChOIAbAAIAAgNIgbAAgAAxgPIgFgFQAHgFAHgGQAHgHAGgJIgLgNIgLgMIAJgHIAKALIAKALIAHgPQADgHACgIIgmAAIAAgNIApAAIADAAIACAAIAIACQgDAPgFAMQgFANgGALIAMAOIAJAMIgKAJIgIgLIgKgNIgNAPQgHAGgIAFIgDgFg");
	this.shape_12.setTransform(189.925,374.775);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(153,153,153,0.498)").s().p("AhjBlIgFgIQBDgIArgYQAsgZAVgqIAPAHQgXAtguAbQgsAZhFALIgDgIgAgFA5IAAhLIhhAAIAAgQIAlAAIAAg2IAQAAIAAA2IAuAAIAAhJIAPAAIAAAaIBHAAIAAAPIhHAAIAAAgIBdAAIAAAQIheAAIAABLgAhYAyIgGgFQAOgLAMgOQANgOAJgNIAPAEQgKAQgOAQQgNAQgOALIgGgGg");
	this.shape_13.setTransform(166.075,374.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(153,153,153,0.498)").s().p("AgBBlIgHgFQAPgPAKgWQAJgVAEgZQAGgZAAgbIgiAAIAAgQIAjAAIABgZIAAgaIAQAAIgBAaIAAAZIA1AAIAAAJIgDA9IgDAqIgDAaQgDAJgDADQgEAFgEACIgJACIgOAAIgTgBIgCgHIgDgIIATABIANAAIAFAAIAEgDQADgEADgNIAEgoIADhEIgmAAQgCAdgEAbQgFAbgKAXQgKAXgSARIgEgGgAhjBGIgDgIQACgBADgEIAGgLIAFgPIAHgXIAIgaIgiAAIAAgPIBpAAIAAAPIg3AAQgFASgGAUIgOAkIA8gMIgHgUIgIgTIAOgDIAJAXIAJAYIAFAUIgNAFIgCgIIgDgJIgoAJIgYAFIgLAEIgGACIgCgHgAhghMIAAgOIBbAAIAAAOg");
	this.shape_14.setTransform(142.25,374.525);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(153,153,153,0.498)").s().p("AhqBiIAAgQICJAAIAEgTIACgVIhsAAIAHgbIAGgfIAGgiIAGgfIg0AAIAAgPIDGAAIAAAPIiBAAIgEATIgDAVIBVAAIADgBIAMABIgDAbIgEAgIgEAgIgFAgIA7AAIAAAQgAgsABIgGAaIBZAAIAEgcIADgZIhWAAIgEAbg");
	this.shape_15.setTransform(118.3,374.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("ABCEnQABgYgEgRQgEgRgIgJQgJgMgSgJQgRgJgZgGIAAgHIAiACIAiACIAaABQAIAAAHgDQAHgCAFgFQAOgMAKgtQAJgsAHhNQg6AkhUArQhTArh1A1QgDAGgEAFQgFAFgGACIg9hrQAcgGAsgMIBlgaIB3ghQBAgRBDgVIAFhaIAFhrImhAAIgGgSIGfAAIA0g1IBQBKQgDAFgIAEQgHAEgMACQgEBvgFBRQgFBPgIA2QgIA2gMAhQgMAhgRAQQgVAWgaAJQgZAKgkAAIgEgBgAgSgbQgbgYgkgZQgjgZgngVQgmgWgjgNIADgHQBMgLA0AFQA1AGAfAQQAfAQAOAVQANAVgCAUQgDAUgQAMQgOALgWAAIgGAAg");
	this.shape_16.setTransform(230.175,295.4012);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AB7EZQg0gPgsgXQhEAdhTAQQhTAOheADIgBgIQBNgPBFgWQBGgYA4ggQgTgQgQgRQgQgSgOgWQgbAagiAVQgiAWgmAPIgFgGQAWgYAUgdQATgdAPgfQAOgfAKgdIgNACIgMABIgNAAIAAisQgcAbgeAVQgeAVggAQIgFgFQAXgdAYgoQAXgoAUguQAUgvAOgxIB0AvQgDAGgHADQgGADgLgBIgHALIgGAKIDsAAIAxg+IAQAMIAkAbIAmAeQgBAFgFACQgFADgIAAIlvAAIgMARIgMAPIA4AWICjAAIAogtIBVBAQgDADgHAEQgFAEgKACIAACFQgBADgNAFQgNAEgSAEQgRAEgQgBIgQAAIAAgTIiuAAIAAAAQAAACgDADIgIAGIBOAhQgCAFgFAEQgGADgLgBIgEAHIgFAHICJAAIA4gvIBOBLQgDAGgHACQgHACgMABQgjAqguAgQAuAHAwADQAwADAuAAIAAAJQgdAIgQAYQgRAYgGAiQg7gJg1gPgAhHBtIgLAKQAUARAaANQAZANAdAJQAWgQASgTQASgSAOgVIiXAAIgKAMgAhQgGICuAAIAAg4IiuAAgAhQhQICuAAIAAg5IiuAAg");
	this.shape_17.setTransform(133.325,294.25);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#CCCCCC").ss(1,1,1).p("AzdAAMAm7AAA");
	this.shape_18.setTransform(228.875,350.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.lnav1_btn},{t:this.lnav2_btn}]}).wait(10));

	// 不动内容
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("Ag5DaQgRgQAAgXQAAgZARgRQAQgQAZgBQAYABAQAQQAQARABAZQgBAXgQAQQgQAQgYABQgZgBgQgQgAghBJQgHgRgDgNQgDgNAAgOQAAgTALgSQALgQAWgXQATgSAMgUQALgUABgYQgBgfgUgTQgUgTghgBIgNBBQgEAYgLALQgLALgTgBQgMABgKgFQgKgEgGgKQADg3AhgeQAhgdA8AAQA/AAAhAbQAhAaAAArQABAZgIASQgHASgRARQgSARgeAVIgfAWQgNAKgGAMQgIAMAAARIAAAWg");
	this.shape_19.setTransform(1801.0516,498.45);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AikEeIAAjPQgWAfgcAdQgcAbggAYIgGgGQAYghATgqQASgpAOgsQAPgtAJgrIhTAAIgFgSIBpAAIAAhlIgzACIgyACIgBgGQAkgNAngRQAmgRAjgSQAigSAWgRIBWBRIAAgOIBZAkIA0AAIAmgsIBOA9QgDAEgFADQgHADgIADIAAFoQgBAEgMAFQgMAGgQAFQgQAEgQAAIgPAAIAAhAIg8AAIAAAsQgBAFgKAHQgJAGgQAGQgRAFgSABIgPAAIAAk4QgCAEgDAAQgEABgFABIhaAAIAAAqQAwAMAWASQAVATADATQAEAUgKAOQgJAPgSACQgRABgTgPQgBgWgHgXQgGgXgLgSIAAEJQAAADgIAFQgJAGgPAEQgPAFgVABgABuCXIA8AAIAAk9Ig8AAgAgdiAIAaAYIAbAcIAAh9QgFADgLAAQgKAAgQgFIgdAGIghAFIAABuIAng4IAMAKg");
	this.shape_20.setTransform(1757.15,498.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AiNEVQA0g6AahCQAbhCAKhIQAJhIAAhQIhEAAIgFgRIBJAAIAAhAIAAhCIBvAKQgBAHgFAEQgGAEgLACIAAA0IgBAzIAqAAIAsgsIBIA/QgEAEgGAEQgGADgLACIgBAyIAFgBQAsAZAUAbQATAbABAXQABAYgMAQQgLAPgSABQgSABgSgTQAEgjgEghQgDgkgKgdQgBBPgDA4QgDA3gFAkQgFAlgIAUQgIAWgMAMQgRAQgWAIQgVAIgcAAQAAgWgDgOQgCgOgGgJQgHgKgNgHQgNgHgSgEIAAgIIAXACIAXABIASAAQAHAAAFgCQAFgBAEgEQAKgJAGgkQAFglAEhEQADhEABhnIgyAAQgBBBgIA9QgIA6gVA2QgWA1gnAuQgoAuhBAngAjoEdIAAl+IgzAAIgFgQIA4AAIAAirIBlAKQgBAFgEAFQgEADgLACIAACRIAiguIALAJIAYAWIAbAXQgCAFgEACQgEACgGAAIhQAAIAAFhQAAAEgKAHQgKAGgPAGQgPAFgPABgAhyBdQgMgFgHgNQgIgSAGgPQAHgPAPgLQAJgIAKgOQAJgPAGgSQAGgUgBgUIAHAAQARAoAEAeQAFAggFAWQgGAYgNAOQgJALgNACIgJABQgJAAgJgEg");
	this.shape_21.setTransform(1700.029,498.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AgsEeIAAkmQgvA2g8AuQg7AuhGAiIgDgEQAsgmAogtQApguAggwQAhgxAXgyQAYgzALguIjsAAIgFgRIGlAAIAyg/IAQANIAkAbIAmAeQgCAGgFABQgEADgHAAIi7AAQgLAcgPAcQgPAcgRAbIApAPQgCAFgDACQgFADgJACIAAFPQgBACgKAEQgMAEgQAEQgQADgQABgADUB+QgRgfgZggQgZgfgdgeQgdgcgdgVIAFgFQBHALAtAUQAuATAYAYQAYAYAGAXQAHAYgIAQQgHASgSAFQgGACgGAAQgOAAgPgIg");
	this.shape_22.setTransform(1641.75,498.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AgzEeIAAmAIB2AKQgBAHgFAEQgEAFgNACIAAFLQAAADgMAGQgMAGgSAFQgRAFgTAAgAkfAhQA1gnAqg1QAsg2Adg6QAfg7AOg3IB+AjQgBAHgIAEQgHADgQADQAcAmApAgQApAgAzAYQAzAYA5APIgCAJQgSAHgMAOQgNANgHARQgJARgEASQhMgmg1hBQg1hAgehWQgQAkgcAnQgdAmgmAkQgmAlgvAeQguAdg2AUg");
	this.shape_23.setTransform(1584.1,498.275);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AiyETQAkgwATg2QATg2AHg2IgPAAIgGgSIAYAAQADggACgfIABg/IgaAAIgFgRIAfAAIAAh+IggAAIgFgRIB0AAIAlgoIBAA5QgEAEgGAEQgHADgKACIAACtQAABIgCAxQgBAxgDAgQgDAfgGAUQgFASgJAKQgPASgTAIQgTAJgWAAQAAgUgCgMQgCgMgFgIQgFgIgKgFQgLgHgPgDIABgIQgQAXgVAVQgUAVgbASgAg3CEQgMAhgVAgIAaABIAXABQAGAAAFgCQAEgCAEgEQAIgIAEgeQAEgeABg6IgfAAQgIAigNAhgAgYgRQgCAfgFAhIAdAAIAAg4IAAhGIgUAAQAAAdgCAhgAgWhgIAUAAIAAh+IgUAAgABcEWIAAogIBGAbIAQAAIAkgkIBGA/QgEAFgGACQgGABgKAAIgUAvQgLAagOAaQgNAcgNAUQAcAWASAbQASAZAIAdQAJAbAAAaQAAAwgTAZQgTAZguABIgBgWIgCgVQgCgKgDgGQgCgDgDgDIgJgGIAACBQAAADgHAFQgHAFgNAFQgMAEgSAAgACiB1IAUAAIAGgBIADgCQAFgEACgIQACgJAAgOQABgigHgjQgGgigQgeIAFgzIAFg9IACg5IgWAAgAkbC7IAAm0IBCAcIAUAAIAfgiIA/AyQgDADgGAEQgHACgJACIAAFBQAAADgJAFQgIAFgMAFQgMADgMAAIgKAAIAAg0IgcAAIAABEQAAADgIAGQgHAGgMADQgMAEgPABgAjbBPIAcAAIAAkbIgcAAg");
	this.shape_24.setTransform(1527.425,498.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("Ag5DaQgRgQAAgXQAAgZARgRQAQgQAZgBQAYABAQAQQAQARABAZQgBAXgQAQQgQAQgYABQgZgBgQgQgAghBJQgHgRgDgNQgDgNAAgOQAAgTALgSQALgQAWgXQATgSAMgUQALgUABgYQgBgfgUgTQgUgTghgBIgNBBQgEAYgLALQgLALgTgBQgMABgKgFQgKgEgGgKQADg3AhgeQAhgdA8AAQA/AAAhAbQAhAaAAArQABAZgIASQgHASgRARQgSARgeAVIgfAWQgNAKgGAMQgIAMAAARIAAAWg");
	this.shape_25.setTransform(1453.0516,498.45);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AikEeIAAjPQgWAfgbAdQgdAbghAYIgFgGQAYghATgqQASgpAPgsQANgtAKgrIhTAAIgFgSIBpAAIAAhlIgyACIg0ACIAAgGQAkgNAmgRQAngRAjgSQAigSAXgRIBVBRIAAgOIBZAkIAzAAIAngsIBOA9QgDAEgFADQgGADgKADIAAFoQgBAEgLAFQgLAGgRAFQgRAEgPAAIgOAAIAAhAIg9AAIAAAsQgBAFgJAHQgLAGgPAGQgRAFgTABIgOAAIAAk4QgBAEgEAAQgEABgEABIhaAAIAAAqQAuAMAXASQAVATADATQAEAUgKAOQgJAPgSACQgRABgTgPQgBgWgGgXQgHgXgKgSIAAEJQgBADgIAFQgIAGgQAEQgPAFgVABgABuCXIA9AAIAAk9Ig9AAgAgdiAIAaAYIAbAcIAAh9QgFADgLAAQgKAAgPgFIgeAGIggAFIAABuIAmg4IAMAKg");
	this.shape_26.setTransform(1409.15,498.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AiNEVQA0g6AahCQAbhCAKhIQAJhIAAhQIhEAAIgFgRIBJAAIAAhAIAAhCIBvAKQgBAHgFAEQgGAEgLACIAAA0IgBAzIAqAAIAsgsIBIA/QgEAEgGAEQgGADgLACIgBAyIAFgBQAsAZAUAbQATAbABAXQABAYgMAQQgLAPgSABQgSABgSgTQAEgjgEghQgDgkgKgdQgBBPgDA4QgDA3gFAkQgFAlgIAUQgIAWgMAMQgRAQgWAIQgVAIgcAAQAAgWgDgOQgCgOgGgJQgHgKgNgHQgNgHgSgEIAAgIIAXACIAXABIASAAQAHAAAFgCQAFgBAEgEQAKgJAGgkQAFglAEhEQADhEABhnIgyAAQgBBBgIA9QgIA6gVA2QgWA1gnAuQgoAuhBAngAjoEdIAAl+IgzAAIgFgQIA4AAIAAirIBlAKQgBAFgEAFQgEADgLACIAACRIAiguIALAJIAYAWIAbAXQgCAFgEACQgEACgGAAIhQAAIAAFhQAAAEgKAHQgKAGgPAGQgPAFgPABgAhyBdQgMgFgHgNQgIgSAGgPQAHgPAPgLQAJgIAKgOQAJgPAGgSQAGgUgBgUIAHAAQARAoAEAeQAFAggFAWQgGAYgNAOQgJALgNACIgJABQgJAAgJgEg");
	this.shape_27.setTransform(1352.029,498.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AgzEeIAAmAIB2AKQgBAHgFAEQgFAFgMACIAAFLQAAADgMAGQgMAGgSAFQgRAFgUAAgAkgAhQA2gnAqg1QAsg2Adg6QAeg7APg3IB+AjQgCAHgHAEQgGADgRADQAcAmApAgQApAgAzAYQAzAYA4APIgBAJQgSAHgMAOQgNANgHARQgJARgEASQhMgmg0hBQg2hAgehWQgRAkgbAnQgdAmgmAkQgmAlguAeQgwAdg1AUg");
	this.shape_28.setTransform(1294.1,498.275);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#333333").s().p("AiyETQAkgwATg2QATg2AHg2IgPAAIgGgSIAYAAQADggACgfIABg/IgaAAIgFgRIAfAAIAAh+IggAAIgFgRIB0AAIAlgoIBAA5QgEAEgGAEQgHADgKACIAACtQAABIgCAxQgBAxgDAgQgDAfgGAUQgFASgJAKQgPASgTAIQgTAJgWAAQAAgUgCgMQgCgMgFgIQgFgIgKgFQgLgHgPgDIABgIQgQAXgVAVQgUAVgbASgAg3CEQgMAhgVAgIAaABIAXABQAGAAAFgCQAEgCAEgEQAIgIAEgeQAEgeABg6IgfAAQgIAigNAhgAgYgRQgCAfgFAhIAdAAIAAg4IAAhGIgUAAQAAAdgCAhgAgWhgIAUAAIAAh+IgUAAgABcEWIAAogIBGAbIAQAAIAkgkIBGA/QgEAFgGACQgGABgKAAIgUAvQgLAagOAaQgNAcgNAUQAcAWASAbQASAZAIAdQAJAbAAAaQAAAwgTAZQgTAZguABIgBgWIgCgVQgCgKgDgGQgCgDgDgDIgJgGIAACBQAAADgHAFQgHAFgNAFQgMAEgSAAgACiB1IAUAAIAGgBIADgCQAFgEACgIQACgJAAgOQABgigHgjQgGgigQgeIAFgzIAFg9IACg5IgWAAgAkbC7IAAm0IBCAcIAUAAIAfgiIA/AyQgDADgGAEQgHACgJACIAAFBQAAADgJAFQgIAFgMAFQgMADgMAAIgKAAIAAg0IgcAAIAABEQAAADgIAGQgHAGgMADQgMAEgPABgAjbBPIAcAAIAAkbIgcAAg");
	this.shape_29.setTransform(1237.425,498.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("ABxEeIAAlMIhAAAIAAABQABAsgGAsQgGAugUArQgUAsgpAnQgqAmhGAcIgEgEQAogjAZglQAZgnANgoQANgpAEgrQAEgrAAgsIAAjFIBVAdQAkgSAggTQAggTAWgQIBaBSQgHAGgLAAQgMAAgPgGQghAHgsAFQgsAGgvAEIAAB2IBwAAIAqg6IAOALIAeAaIAfAdQgBAEgEADQgFACgGAAIg8AAIAAE5QgBACgIAEQgJAFgQAEQgQAEgWAAgAkVCrIAAmZIBSAhIAgAAIAlgoIBLA5QgDAEgGAEQgGADgJADIAAEZQgBACgLAGQgLAEgQAFQgPADgPAAIgNAAIAAg/IgnAAIAABPQgBAFgJAGQgKAHgPAFQgQAFgSAAgAjEAvIAnAAIAAjrIgnAAg");
	this.shape_30.setTransform(1179.375,498.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#333333").s().p("AkXAxIgFgTIGfAAIA4hOIAKAJIAaAWIAgAcIAeAdQgBAFgFACQgFACgIAAg");
	this.shape_31.setTransform(1120.275,493.075);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("ABxEeIAAlMIhAAAIAAABQABAsgGAsQgGAugUArQgUAsgpAnQgqAmhGAcIgEgEQAogjAZglQAZgnANgoQANgpAEgrQAEgrAAgsIAAjFIBVAdQAkgSAggTQAggTAWgQIBaBSQgHAGgLAAQgMAAgPgGQghAHgsAFQgsAGgvAEIAAB2IBwAAIAqg6IAOALIAeAaIAfAdQgBAEgEADQgFACgGAAIg8AAIAAE5QgBACgIAEQgJAFgQAEQgQAEgWAAgAkVCrIAAmZIBSAhIAgAAIAlgoIBLA5QgDAEgGAEQgGADgJADIAAEZQgBACgLAGQgLAEgQAFQgPADgPAAIgNAAIAAg/IgnAAIAABPQgBAFgJAGQgKAHgPAFQgQAFgSAAgAjEAvIAnAAIAAjrIgnAAg");
	this.shape_32.setTransform(1063.375,498.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#333333").s().p("Ag7BiQAmgTAQgZQARgYADgWQgOgDgRgIQgQgIgNgOQgNgOgBgWQAAgWAQgRQAQgQAagBQAQAAANAIQAOAIAJAQQAIAPABAXQAAAfgMAfQgKAfgZAbQgWAbgoASg");
	this.shape_33.setTransform(982.3,523.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#333333").s().p("AjJEdIAAi+QgRAXgUAWQgVAWgXATIgGgFQATgjAQgpQAPgpALgsQALgrAHgsIhGAAIgFgQIBTAAIAAhfIgpADIgoACIgCgFQAdgNAggSQAegRAcgTQAbgTARgPIBaBNQgGAGgLAAQgKABgQgGIgWAGIgZAFIAABjIAdgqIAKAKIAZAWIAZAZQgBAFgEACQgFADgGgBIhJAAIAAAfQAsARAVAWQAUATACAVQACAUgKANQgKAOgQACQgRABgSgQQAAgWgFgXQgFgWgIgUIAAEVQAAADgIAFQgIAGgOAEQgPAFgUAAgAhKD8IgFgQICMAAIAAhwIhdAAIgFgRIBiAAIAAhoIhnAAIgEgQIDgAAIAkgzIAMAKIAaAXIAbAZQgCAFgEABQgEADgHAAIh4AAIAABoIASAAIAmgzIAMAKIAcAXIAdAaQgBAEgEADQgFADgHgBIhsAAIAABwIAuAAIAkg0IAMAKIAaAXIAbAaQgBAFgEACQgFACgHAAgAgagtIAAjdIBRAfIBjAAIAkgnIBLA4IgIAHQgGADgKACIAAB7QgBADgKAFQgLAEgQAEQgPADgOAAIgNAAIAAgWIhtAAIAAAQQAAAFgKAFQgKAGgQAEQgPAFgPAAgAA0hnIBtAAIAAhzIhtAAg");
	this.shape_34.setTransform(945.975,498.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AiyEdIAAkpIBcAiICnAAIApgsIBTA/QgDAEgGADQgHAEgJADIAADHQgBAEgMAGQgMAHgRAFQgRAGgSAAIgPAAIAAgsIiyAAIAAATQAAAFgMAHQgKAGgSAFQgQAFgTAAgAhaDeICyAAIAAhUIiyAAgAhaB5ICyAAIAAhSIiyAAgAkRglIgFgRIE2AAIAOgpIANgsIALgqIjFAAQAvAOAVAUQAVAVACAUQAAAVgMAOQgMAOgTABQgUABgVgSQgBgdgIgcQgIgcgLgXIhjAAIgEgQIDvAAIgKgEIgLgGQgCgWgJgTQgJgUgKgOIADgCQAzgCAZALQAYALAGAQQAFARgKAOQgJAOgSAGIB4AAIArg6IAOAMIAgAZIAhAcQgBAFgEACQgFACgHAAIiWAAIBcAcQgCAGgGADQgFADgKgBQgWAUgeAYQgeAYggAUIBsAAIAtg7IAOALIAhAaIAjAdQgCAFgEACQgFADgGAAg");
	this.shape_35.setTransform(888.15,498.216);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#333333").s().p("ABmD3QgEgPgIgJQgIgJgQgIQgRgIgYgFIABgHIAgACIAfACIAXABQAHAAAFgCQAGgCADgEQAQgPAHhTQAGhTACiYIhcAAQgYAngbAgQgbAfgfAZIgDgDIAADyQgBADgLAGQgLAFgQAEQgPAEgOABIgNAAIAAgwIhLAAIAAApQAAAFgJAHQgIAGgPAFQgPAFgSAAIgMAAIAAnJIBLAfIADglIADgpIABglIB0AcQgCAHgGAEQgHADgLAAIggAlIgiAmIAnAAIAlgpIBKA6QgCAEgHADQgGADgIADIAABkQAOggAOgpQAMgpALgtQALgtAGgsIBwAgQgCAGgGADQgGAEgKAAQgHATgJARIgSAjIBLAAIAtguIBJBBQgEAEgGADQgHADgKACQgCBegDBDQgCBDgFAtQgFAtgJAbQgIAbgNANQgRARgXAJQgXAHghAAQAAgVgDgPgAjECuIBLAAIAAidIhLAAgAjEAAIBLAAIAAiTIhLAAgAAkBRQgBghgLghQgLgfgPgaIADgDQA5AOAbAWQAbAWAFAXQAEAYgKARQgLARgVADIgEAAQgTAAgUgQg");
	this.shape_36.setTransform(831.4,498.375);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#333333").s().p("Aj9EXQBCgVAngXQAngYAUgaQAUgbAHgdIiMAAIgEgRICTAAQADgQABgQIABgjIhDAAIgDgKQgfAbgoAWQgnAXgxASIgEgGQAygiAlgoQAkgoAZgrIiJAAIgFgRICYAAIAOgdIAMgeIh7AAIgEgRICGAAIAIgbIAIgaIikAAIgFgRICtAAIAIgrIAGgqIB1AXQgBAHgGAEQgFAEgLAAIgGAXIgFAYIBwAAIArg1IANAKIAfAXIAiAbQgCAFgEACQgFADgGAAIjeAAIgJAbIgJAaICBAAIAngwIAMAKIAcAVIAfAYQgBAFgFADQgEACgHAAIjmAAIgPAeIgRAdIDOAAIArg3IAOALIAgAYIAiAbQgBAFgFACQgEADgHAAIirAAQAWAXAfAPQAgANAjAHQAkAHAiACIgBAJQgZAQgPAUQgPAUgCAYQgygWgmgpQglgpgYg0IiIAAQgNASgPARQgPAPgSAQICCAAIAlgsIAMAJIAaATIAdAXQgBAFgFACQgEADgHAAIg/AAQAAASgCARQgCAQgEAQIA1AAIAogzIAMAKIAdAWIAfAaQgBAFgFADQgEACgHAAIiZAAIgEALIgFALQBVAJAvAQQAwARATATQAUASgCARQgBARgPALQgPAKgUAAQgVAAgSgPQgRgWgigcQghgcgygaQgPAagfAWQgfAXg0ASQgzAShOAOg");
	this.shape_37.setTransform(772.225,498.125);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#333333").s().p("AjMEBQgCgNgHgIQgHgHgNgHQgNgGgSgEIAAgHIAZABIAaABIASABIALgBQAEgBAFgDQAKgJAHgoQAHgpAEhIIgtAAIgXAdIhBgjIAIgIIAKgHQADgUACgdIAEg3IACgwIBRAmIAUAAIAAhxIh2AAIgFgQIB0AAIAigmIBKA2QgDAFgHAEQgGADgKADIAAB/QgBACgKAEQgLAEgOADQgOAEgNAAIgMAAIAAgeIgkAAIgCAhIgDAlIgEAhIAqAAIAnglIBCA3QgDAEgGADQgGADgJAAQgEBBgFArQgHArgKAYQgKAZgPALQgPALgTAGQgTAFgaAAQAAgQgCgNgAA/EeIAAiGIiFAAIgFgRICKAAIAAhHIgkAAIAAAPQAAAEgQAGQgPAHgdABIgNAAIAAkaIBQAeIBdAAQAJgaAKgjQALgjAIgiIBiAmQgCAFgGADQgGAEgKgBQgVAXgYAVQgXAUgXARIAXAAIAlgpIBDA0QgDADgGADQgFADgKABIAADHQAAAEgRAGQgRAHgeAAIgNAAIAAgSIgkAAIAABHIAjAAIAng2IAMALIAcAYIAdAbQgBAEgFADQgEACgHAAIh+AAIAAByQAAADgHAEQgHAEgOAEQgNAEgUABgACKAwIAkAAIAAhYIgkAAgAAbAwIAkAAIAAhYIgkAAgACKg5IAkAAIAAhRIgkAAgAAbg5IAkAAIAAhRIgkAAgAAPiwQgEgbgLgaQgMgagPgUIAFgDQAyAHAaARQAZARAGATQAFAUgJAOQgJAPgSAEIgHABQgOAAgSgMg");
	this.shape_38.setTransform(713.775,498.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#333333").s().p("AAyEcIAAl/IgjAAIAAEXQgBADgHAFQgHAFgNAFQgOAEgUAAIgOAAIAAleIBUAgIAbAAIAAheIiBAAIgFgQID0AAIArg5IAMALIAfAZQARAPAOANQgBAFgFACQgFACgGAAIiBAAIAABeIAfAAIAhgmIBIA2QgCADgGADQgFAEgIACIAADKQAAAagGARQgFASgSAKQgRALgjADIgBghQgBgNgDgIQgCgIgGgGQgEgFgMgCIAAgIIAFAAIAJAAIAJAAQAGAAABgDQACgCAAgEIAAjOIglAAIAAFpQAAADgIAFQgIAGgPAEQgOAEgVAAgAkHEXQAignAUgvQASguAIg1QAHg1AAg5IAAkKIBjAJQgCAHgEAFQgFADgMACIAADwQAAA/gOA4QgOA5gjAuQgiAug8AggAkUCVIAAlkIBcAIQgBAHgEADQgFAEgKACIAAE4QAAADgJAFQgJAFgOADQgNAEgOAAg");
	this.shape_39.setTransform(657.25,498.45);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#333333").s().p("Ai2D7QgDgNgHgJQgHgJgLgGQgLgHgXgEIAAgHIALAAIAWABIAaABIAQABQAGAAADgDQACgBAAgGIAAgxIgjALIgmAOQgDAFgEAFQgFADgFABIgihVIA0gFIBIgJIAAg1IAnADIAMgVIALgTIg0AAQgfAYgjAXQgiAXgoASIgFgHQAZgSAWgUQAYgVAUgWIg0AAIgGgRIBKAAIAZgeIAXgfIiRAAIgFgRIBZAAIAAhOIg+AAIgFgRIBDAAIAAhTIBoAIQgBAGgFAFQgFAEgMACIAAA1IAbgmIAJAIIAVASIANgfIANgeIBZAsQgCAFgGADQgFACgLgCQgRAdgTAfQgVAegZAfIASAAIAdgpIAHAGIAQANIATASQAKgqAHgrQAHgsAEgsIBxAcQgCAFgFAEQgGAEgKAAIgPAxIgQAtIAyAAIAqg3IANAKIAeAZIAgAbQgBAFgFACQgFADgGAAIgaAAQgGBEgTA9QgTA9gjA1QAaAbAfAXQAfAWAlASIgCAFQgeAHgRASQgTASgHAdQgfgXgWgbQgXgegRghQgmAlg0AdQgzAehHAUIgDgGQBEgkAsgtQAvguAbg1QgJgggIgiQgHgigFglQgPAWgTATQgSAVgUARIgIgEIAJgTIAHgTIgHACIgKABIgfARIgjARIAVABQAAAIgFADQgFADgJACIAAATIA2gHIA4gHIABAHIgxAWIg+AYIAABVQABAbgIATQgGASgWALQgWAMgrAEQgBgUgEgOgABkheQgJASgKAQQAHAdAKAaQALAZAMAXQAPgoAIgrQAJgsACguIgmAAQgIASgJASgAAGgKQAHgSAGgUIAMgoIhiAAIgdAfIghAeIAjAAIAlgmgAh2h2IAVghIATggIgoAAg");
	this.shape_40.setTransform(598.15,498.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#333333").s().p("AkXEcIAAowIBVAmIARAAIAlgkIBAA6IgHgWIgHgUIAHgCQAsAVAUAYQATAZADAWQACAWgJAOQgJAPgRABQgQACgSgRQAAgTgCgTQgDgTgFgSQgDACgGABIgNABIgXAsIgdAxQgPAYgPAUQAcAUASAZQASAYAJAbQAIAaAAAaQAAAdgIAWQgHAVgTAMQgSALggABIgBgWIgCgVQgBgKgDgFQgEgJgKgEIAACYQAAADgIAGQgHAGgOAEQgOAFgUAAgAjKBiIAQAAIAGgBQADAAADgCQAEgEADgIQACgIAAgNQABgggHggQgGgggQgdIAIgxIAIg4IAGg2IgfAAgAiTDKIAmgTIAngUIAAi9IguAAIgEgSIAoAAIAkgvIAkAdQASgaAOggQANggAKgjIguAAIgEgRIA3AAIAIgnIAFgoIBpAXQgBAGgGAEQgFAEgLABIgHAUQgEALgFAKIApAAIAng3IAMAKIAcAZIAdAbQgCAFgEACQgFADgGAAIiLAAQgIAPgJAOQgIAPgLANIAhANIAuAAIAegkIBEA0QgDAEgGADQgGADgJACIAADEQAAAWgFAQQgFAQgQAJQgRAJggADIgCgbQgBgLgEgIQgDgHgGgFQgGgGgNgCIAAgJIAHABIAOABIAMAAQAFAAACgCQABgDAAgFIAAgxIg6AAIAABtQAAADgHAGQgHAGgNAEQgNAFgSABIgMAAIAAkJIgUAPQgJAHgLAHIAcAWQgEAEgHAEQgIADgNACIAAC1QAYAUAmAJQAlAJA4AAIA+gBIA9gCIAAAGQgRAFgJATQgKATgBAaIhnAAQgqAAgdgLQgcgLgVgVQgTgWgRgfQgFgJgFAAQgFABgFAIIgOAZIgTAhIgSAhQABAEgCAEIgGAFgAByAhIA6AAIAAg5Ig6AAgABygpIA6AAIAAg8Ig6AAg");
	this.shape_41.setTransform(541.625,498.475);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#333333").s().p("ACiDTQgbgpgQg4QgRg3gKhGIgjAAIAAC0IAlgHIAmgHIABAFIgwAoQgfAYgoAcQgGAKgHAHQgFAGgGADIgnhUQARgKAGgHQAGgIAAgLIAAh3QgCADgEABQgEACgFAAIhMAAIAABuIArgJIArgKIABAHQgiAXgzAdQg0AehLAiQgCAHgFAEQgEAEgGACIglhcIAMgBIAPgCIAAjCIBKAHQAAAEgCACQgDACgGABIAACoIARgDIAAj9IgEAAIAAAOQAAACgGAFQgIAFgNAEQgNAEgSAAIgOAAIAAjlIBRAkIA0AAIAhgjIBEAyQgCAEgGADQgFADgIACIAACFQgBACgKAEQgLAEgNADQgOAEgNAAIgDAAIAABfIAKAAIAdgxIAKAKIAUAUIAWAZIAAk2IBVAiIBaAAIAkgmIBIA3QgCAEgGADQgGADgJADIAADKQgBAEgKAFQgLAFgQAEIBGAzQgDAEgGABQgFABgJgCQgOAHgXALQgZALgbAIQAbAkAhAaQAiAZAmAPIgCAGQgVAHgRASQgQATgHAdQgogdgbgpgAB6AnQALAYAOAVQANgTAMgUIATgjIgHACIgJAAIgOAAIAAgXIg7AAQAJAaALAYgAA5gcIBoAAIAAhcIhoAAgAi7hnIBDAAIAAh8IhDAAgAA5iJIBoAAIAAhYIhoAAg");
	this.shape_42.setTransform(482.1,498.925);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#333333").s().p("AgqBJQgTgLgMgTQgLgUAAgXQAAgYALgTQAMgTATgLQAUgMAWABQAZgBASAMQAUALALATQALATAAAYQAAAXgLAUQgLATgUALQgSAMgZABQgWgBgUgMgAgrgsQgSASAAAaQAAAaASASQASASAZAAQAaAAASgSQASgSABgaQgBgagSgSQgSgRgagBQgZABgSARg");
	this.shape_43.setTransform(1723.05,517.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#333333").s().p("Ag+EXIAAkgIBVAgICKAAIAmgoIBPA6QgDAEgGAEQgGAEgKACIAADMQgBACgMAFIgcAIQgQAEgOAAIgPAAIAAgvIiTAAIAAAWQgBAEgKAGQgJAGgQAFQgQAFgSAAgAAUDWICTAAIAAhQIiTAAgAAUB1ICTAAIAAhNIiTAAgAkVCpIAAmVIBOAgIAgAAIAjgoIBJA5QgDADgGAEQgGADgJACIAAEdQgBADgLAEQgKAFgPAEQgOAEgOAAIgNAAIAAgzIgoAAIAABAQAAAEgJAGQgJAGgOAFQgPAFgRAAgAjJA+IAoAAIAAj5IgoAAgAgrgEIAAkHIBSAgIBpAAIAngrIBPA8QgDAFgHAEQgGAEgLACIAACsQgBACgMAFQgLAEgQADQgQADgOABIgOAAIAAgjIh0AAIAAATQAAAEgKAGQgKAFgPAFQgPAEgQABgAAjhBIB0AAIAAhEIh0AAgAAjiWIB0AAIAAhFIh0AAg");
	this.shape_44.setTransform(1683.225,498.475);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#333333").s().p("AiFEWQA1gWAhgXQAhgXAQgaQASgaAGgbIiBAAIgEgRICKAAIAEgiIABgkIgTAAIAAAQQAAAEgKAGQgKAGgPAFQgRAEgRAAIgLAAIAAgqQgJAFgNgBQgMgBgNgMQAAgVgFgVQgEgWgHgUIAAE2QAAAEgKAFQgKAGgQAEQgPAFgQgBIgRAAIAAjeQgQAXgTATQgTAVgWATIgHgHQAVgiAPgpQAPgqAKgsQALgtAGguIhGAAIgEgQIBPAAIAAiZIBqALQAAAGgFAFQgFAEgMACIAAB1IAcgsIALALIAYAXIAAgDIBTAgIB/AAIAkglIBHA1QgCADgEAEQgGACgHABIAACOQAAADgEADIgOAGIATAPIAbAYIAaAXQgCAFgEACQgEADgHAAIiTAAQAPAZApAPQAqAQBHAFIAAAIQgfAHgQATQgQATgBAmQglgMgXgYQgYgYgNgfQgNgdgFgeQgKAjgaAfQgaAcgzAXQgwAVhSAPgAB9BQQgDASgDAQIA0AAIAlg0IgUAGQgKACgLABIgPAAIAAgbIgZAAIgCAkgAARAbICHAAIAAg5IiHAAgAh+hDIABAAQAWAJAPAKQAQAKAJAKIAAhYIg/AAgAARgvICHAAIAAg5IiHAAgAgQiNIAAgzIhCAAIgFgRIBHAAIAAhJIBhAHQAAAGgEAEQgEAEgLACIAAAyIAvAAIAAhJIBiAHQgBAGgEAEQgEAEgLACIAAAsIAggrIAMAJIAZAXIAbAYQgBAFgFACQgEADgGAAIhQAAIAAAZQgBAEgJAEQgLAFgPAEQgQAEgPAAIgLAAIAAguIgvAAIAAAhQAAADgKAFQgLADgPAEQgPADgPAAg");
	this.shape_45.setTransform(1622.3,498.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#333333").s().p("AkcEbQA9gjAggoQAhgpAMgtQAMgtAAgxIiNAAIgGgQICTAAIAAiNIh1AAIgEgQIEgAAQAHgWAIgZIAOgxIALguIB1AgQgBAFgFAEQgHADgKAAQgVAWgeAaQgeAbggAXIBcAAIAsg4IAPALIAgAYIAiAcQgBAFgEACQgGACgGAAIhrAAIAACNIANAAIAtg5IAOALIAgAZIAiAcQgBAFgFACQgFACgGAAIh5AAIAADsQAAACgJAFQgJAGgQAEQgRAFgYAAIgRAAIAAkCIhfAAQgBAmgJAlQgJAlgYAjQgZAigwAdQgvAdhOAVgAgoAMIBfAAIAAiNIhfAAgAhrigQgFghgQgeQgQgfgUgXIAEgDQA9AGAgATQAfATAHAWQAIAXgKASQgJATgVAFIgLABQgQAAgTgMg");
	this.shape_46.setTransform(1562.2,497.875);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#333333").s().p("Ag6BiQAkgTASgZQAPgXAEgXQgOgDgQgIQgSgIgNgOQgMgNAAgXQgBgXARgQQAPgQAagBQAQAAAOAIQAOAIAIAQQAIAPAAAXQAAAfgKAfQgLAfgYAbQgXAcgnARg");
	this.shape_47.setTransform(1480.4,523.15);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#333333").s().p("AB6D5QgEgPgJgKQgIgKgOgHQgOgHgagEIAAgIIAMABIAbABIAeABIAXABQAIABADgEQACgDABgHIAAlIIlJAAIAAGRQABAGgLAHQgKAHgRAGQgQAEgSABIgOAAIAAnlIBcAkIBPAAIAIgnIAIgpIAGglIB7AbQgBAHgFACQgFAEgLAAIgnAlQgVAVgYATIDFAAIAmgqIBNA8QgCADgGAEQgGAEgKACIAAFEQABAcgHATQgIAVgYALQgYAMgvAEQgCgVgEgOgAh/CiIAAkBIBQAgIBAAAIAkgoIBJA4QgCAEgHADQgFAEgKACIAACeQgBACgKAGQgLAEgPAFQgPADgOABIgNAAIAAg1IhJAAIAAAtQAAAEgKAGQgJAGgPAEQgPAEgRABgAgyBLIBJAAIAAh6IhJAAg");
	this.shape_48.setTransform(1443.65,498.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("AkbEZQA0goAhgwQAhgxASg2QATg2AGg5QAIg7AAg8IikAAIgFgQIG0AAIAug8IAOALIAiAaIAkAeQgBAFgFACQgEACgHAAIkcAAIgFA1QgCAbgFAZIB8AAIAtgrIBKA/QgDAEgHADQgGADgLACQgEBOgHA1QgIA0gMAfQgMAfgRAPQgSANgVAGQgWAGghAAQABgTgDgPQgDgPgHgIQgJgKgPgIQgPgIgXgFIABgGIAfACIAeACIAVAAQAIAAAFgBIAJgEQANgMAJg0QAJg0AGhZIiFAAQgLBBgcA6QgbA6gzAuQgyAvhPAegAgTitQgGgegPgdQgPgdgTgVIAFgDQA8ADAeARQAfARAHAXQAIAWgKASQgJASgVAFIgLABQgQAAgTgMg");
	this.shape_49.setTransform(1382.15,498.075);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("AkkDFIApgXIAqgXIAAjHIhIAAIgEgRIBCAAIAngzIBSBBQgEAEgHAEQgIADgNADIAACyQALAKAMAJQANAHAOAHIgDgDQAWglALgpQALgpADgwIhLAAIgFgQIBQAAIABgSIAAgUIAAhOIg8AAIgFgRIBBAAIAAiLIBkAKQgCAHgEAEQgEAEgMABIAABxIA1AAIAAiLIBkAKQgBAHgFAEQgEAEgMACIAABwIACAAIAkg4IAMALIAaAZIAcAbQgCAFgEACQgEADgHAAIhXAAIAAB0IANAAIAmg6IANALIAbAaIAcAcQgBAFgFACQgEACgHAAIhmAAIAACeQAAAEgKAFQgKAGgOAEQgPAFgPAAIgOAAIAAi2Ig5AAQgHA2gbArQgbArg4AeQAfAOAtAEQAsAGBBAAIBZgCQArgBAvgDIAAAHQgZAHgOAUQgNAVgDAaIiYAAQg/ABgogMQgpgMgcgZQgbgZgWgmQgGgMgGABQgFABgGAKIgRAdIgXAnIgYAoQABAEgCAFQgCADgEACgAArgyQAAAVgBARIA2AAIAAh0Ig1AAgAjAiIQgHgjgRgiQgRgjgTgcIAEgCQA8AMAgAWQAeAWAIAYQAIAYgJASQgJATgUAFIgJAAQgQAAgTgMg");
	this.shape_50.setTransform(1322.175,498);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("AjCEcIAAkIQgVAPgXAOQgWAOgXAMIgGgGQAfgiAegpQAcgqAYgqQAYgpAOghIBkA7QgCAEgGACQgFADgLgBIgaAaIgdAbIAcALQgBAEgEADQgFADgIACIAAEcQgBADgLAFQgKAFgQAEQgQAEgRAAgABEDyQgFgPgLgKQgGgGgJgFQgJgFgNgFQgNgEgVgEIAAgHIAPABIAgACIAlACIAYABQAIAAADgDQADgDAAgGIAAjxIigAAIgFgRIDoAAIArg5IAOALIAeAZIAhAcQgCAFgEACQgFADgHAAIhQAAIAAD0QAAAcgIAVQgJAWgZANQgaANgyADQgCgUgEgQgAkQhuQAZgZAYgfQAZgfAUgfQAUgfAMgYIBeA7QgCAEgFADQgHACgJgCQgXAUgfAUQgeAVgkATQgjASgmAPgAgXjNIgFgRIC6AAIAog2IAOALIAcAYIAfAaQgBAFgEADQgFACgGAAg");
	this.shape_51.setTransform(1261.7,498.125);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("ABmD3QgEgPgHgJQgJgJgRgIQgQgIgXgFIAAgHIAfACIAgACIAWABQAIAAAFgCQAFgCAEgEQAQgPAGhTQAHhTACiYIhcAAQgXAngcAgQgaAfggAZIgEgDIAADyQAAADgLAGQgLAFgPAEQgPAEgPABIgOAAIAAgwIhJAAIAAApQgBAFgIAHQgKAGgPAFQgPAFgRAAIgNAAIAAnJIBMAfIADglIACgpIACglIB0AcQgCAHgHAEQgGADgLAAIgfAlIgjAmIAnAAIAlgpIBLA6QgDAEgGADQgHADgJADIAABkQAPggANgpQANgpALgtQAKgtAIgsIBvAgQgBAGgHADQgFAEgLAAQgIATgIARIgSAjIBLAAIAtguIBIBBQgDAEgHADQgGADgLACQgBBegCBDQgDBDgFAtQgFAtgJAbQgIAbgOANQgQARgXAJQgXAHgiAAQABgVgDgPgAjDCuIBJAAIAAidIhJAAgAjDAAIBJAAIAAiTIhJAAgAAlBRQgCghgLghQgLgfgPgaIAEgDQA4AOAbAWQAcAWAEAXQAFAYgLARQgLARgVADIgEAAQgTAAgTgQg");
	this.shape_52.setTransform(1203.5,498.025);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AiyEdIAAkpIBcAiICnAAIAqgsIBSA/QgEAEgFADQgHAEgKADIAADHQAAAEgMAGQgMAHgRAFQgRAGgRAAIgQAAIAAgsIizAAIAAATQAAAFgKAHQgMAGgQAFQgRAFgTAAgAhbDeICzAAIAAhUIizAAgAhbB5ICzAAIAAhSIizAAgAkRglIgFgRIE2AAIAOgpIANgsIALgqIjFAAQAvAOAVAUQAVAVABAUQACAVgMAOQgNAOgUABQgTABgVgSQgBgdgIgcQgHgcgMgXIhiAAIgGgQIDxAAIgLgEIgLgGQgCgWgJgTQgJgUgLgOIAEgCQA0gCAYALQAYALAGAQQAFARgJAOQgKAOgSAGIB3AAIAsg6IAOAMIAgAZIAiAcQgCAFgFACQgEACgHAAIiXAAIBcAcQgBAGgGADQgFADgKgBQgVAUgfAYQgfAYgfAUIBsAAIAtg7IAPALIAgAaIAjAdQgCAFgEACQgFADgGAAg");
	this.shape_53.setTransform(1142.25,497.866);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#333333").s().p("AgvD/QgDgPgJgJQgJgIgNgHQgOgGgbgFIAAgHIAMAAIAcACIAfACIAVAAQAIAAACgCQAEgDgBgFIAAjJIhwAAIgbAhIhNgqIAIgHIALgHIAMgzIAMg7IAKg4QAFgZABgRIBbAUQAugIAtgMQAugLAogMQAogNAdgLIBNBSQgGAEgLAAQgMAAgPgHQgmAEgwACQgwADg0AAQg0AAgzgCIgKA2IgNBAIgMA5IBvAAIAAiWIBsALQgBAGgEAEQgEAEgLACIAAB7IBPAAIAwg8IAPAMIAiAaIAlAdQgCAFgFADQgFACgGAAIjDAAIAADLQAAAdgIATQgIATgYALQgZAMgvAEQgCgUgEgNgAkbDxQAagYAagiQAZgiAWgpQAWgpAPgsIBoAxQgCAGgHACQgHADgKgBQgqA+g1AoQg1Ang9AYgADLDfQgMgigSgiQgSgigVggQgWgggVgbIAFgDQBOAWArAgQArAfAOAhQAOAggHAZQgHAYgVAHQgHADgHAAQgQAAgUgNg");
	this.shape_54.setTransform(1082.075,497.925);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#333333").s().p("ACYD5QgEgQgHgJQgIgKgMgIQgMgHgYgEIAAgIIAKABIAYABIAbACIATAAQAHAAAEgDQACgCAAgFIAAnKIBsALQAAAGgFAEQgGAFgLABIAAG1QABAdgHAUQgIAUgYAMQgXAMguAFQgBgWgEgOgAACEaQgVgDgVgMQgUgNgOgOIgcgiIgYgjQggAegnAYQgnAYgtASIgFgIQAogbAhgiQAigiAagpQgWgwgNg1QgNg0gHg5IhEAIIgGgQIBIgIQgEgsgCgtQgCgtABgvIBpALQgBAFgFAFQgEAFgMACQgBAkABAkQABAkAEAkIBFgIIAig2QgIADgLAAQgLAAgLgHQgFgWgOgVQgOgUgPgOIAEgDQAtgCAYAJQAZAKAIAOQAIAPgFAOQgDAOgOAIIARALIAcASIAeAVQgBAEgFAEQgEADgGAAIikATQADAhAHAfQAGAfAKAcQALgbAKgfQAKgfAIgkIBjAkQgCAGgFADQgGADgLgBQgRAugTAmQgUAngXAgQAJAQAMAOQALAOAOAMQAGAIAFAAQAEgBAFgHIAMgVIAPgcIAPgbIAFABIgRBsQARAgAEATQACATgJAHQgPAMgTAAIgHAAgAA8CKIAAl0IBlAIQgBAHgFAEQgEAFgMACIAAFFQAAADgKAFQgKAFgOAEQgPAEgQAAg");
	this.shape_55.setTransform(1021.65,498.025);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#333333").s().p("ACYD5QgDgQgJgJQgGgKgNgIQgMgHgZgEIAAgIIALABIAYABIAbACIATAAQAIAAACgDQADgCAAgFIAAnKIBtALQgBAGgFAEQgGAFgLABIAAG1QABAdgIAUQgHAUgYAMQgXAMguAFQgCgWgDgOgAACEaQgVgDgVgMQgVgNgNgOIgdgiIgXgjQghAegmAYQgnAYguASIgDgIQAogbAggiQAigiAbgpQgXgwgNg1QgNg0gHg5IhEAIIgGgQIBIgIQgEgsgCgtQgBgtAAgvIBoALQAAAFgEAFQgFAFgLACQgBAkABAkQAAAkADAkIBGgIIAjg2QgJADgKAAQgLAAgMgHQgGgWgNgVQgNgUgQgOIAEgDQAsgCAZAJQAYAKAJAOQAIAPgFAOQgDAOgOAIIARALIAcASIAeAVQgCAEgEAEQgDADgHAAIilATQAEAhAHAfQAGAfAJAcQAMgbAKgfQAKgfAJgkIBjAkQgCAGgGADQgGADgLgBQgRAugTAmQgUAngXAgQAJAQAMAOQAMAOANAMQAFAIAGAAQAEgBAFgHIAMgVIAPgcIAOgbIAGABIgRBsQARAgADATQAEATgKAHQgPAMgTAAIgHAAgAA8CKIAAl0IBlAIQgBAHgFAEQgEAFgMACIAAFFQgBADgJAFQgJAFgQAEQgOAEgQAAg");
	this.shape_56.setTransform(901.65,498.025);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#333333").s().p("Ag7EdIAAjwIhwAAIAAAfQgBAFgLAHQgLAHgTAFQgRAGgUAAIgNAAIAAkkIBjAlIBpAAIAAiHIBzALQgBAHgEAEQgFAFgMABIAABrIBtAAIAngsIBSA/QgCAEgHADQgFAEgJACIAADAQgBADgNAFIgeAJQgSADgPABIgQAAIAAgzIhyAAIAADQQgBAFgLAHQgLAIgRAFQgRAGgSABgAAiAdIByAAIAAihIhyAAgAirAdIBwAAIAAihIhwAAg");
	this.shape_57.setTransform(843.35,498.025);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#333333").s().p("AkSEMIgFgRIDqAAIAAi6IimAAIgFgQIFDAAIAog4IANAKIAdAZIAeAcQgCAFgEACQgFACgGAAIieAAIAAC6IBwAAIAqg6IAOALIAeAZIAfAdQgBAFgFACQgEADgHAAgAkHAlQAjgXAfgfQAfggAYghQAXghAMgbIBxA5QgDAGgHAEQgIADgPgBQgZAYgkAWQglAXgrARQgsASgwAKgAC/AdQgTgcgcgbQgcgbgfgZQgggYgegRIAEgFQAqAAAhAFQAhAFAZAIIAFgaIADgZIlkAAQAGAlgJAZQgKAZgTAKQgMAHgNgBQgNgBgKgHQgLgIgEgOQgGgUAKgOQAJgOASgIQAJgGAJgMQAJgLAEgPQAFgPgCgRIAHgBQAMAXAGAUICuAAIgJgEIgIgFQAAgXgJgVQgJgWgRgNIADgDQA4gGAcAKQAeAKAHARQAIASgIARQgJARgSAIICJAAIAtgtIBOBJQgDAEgFACQgGACgJAAQgOALgSAMQgSAMgTALQAlAUAOAYQAPAZgDAVQgEATgSAKQgJAGgMAAQgLAAgMgEg");
	this.shape_58.setTransform(782.3742,496.1125);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#333333").s().p("Ai9EdIAAjfQgpAhgzAZIgEgFQAmgjAegpQAfgoAYguQAYgtARgvIiRAAIgFgRICdAAQALgiAJggQAJggAGgeIB4AeQgBAGgFAEQgFADgMABQgHAVgJAVIgSAqICgAAIAwg9IARALIAiAbIAmAeQgCAFgFADQgEACgHAAIkfAAQgRAfgTAfQgVAfgYAcIAXAJQgBAEgFADQgEACgJACIAAEEQgBADgKAGQgKAFgRAEQgQAFgRAAgAhbD2IgFgRIB5AAIAAi4IhlAAIgFgRIBqAAIAAiNIBsAJQgBAGgDAEQgFAEgLACIAAB0IAQAAIAsg1IANALIAfAWIAgAbQgBAFgEADQgFACgHAAIh3AAIAAC4IArAAIAvg6IAPALIAgAaIAkAcQgBAFgFADQgEACgIAAg");
	this.shape_59.setTransform(721.9,497.825);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#333333").s().p("Ag7BiQAlgTARgZQARgXADgXQgOgDgRgIQgQgIgNgOQgNgNgBgXQAAgXAQgQQAQgQAagBQAQAAANAIQAPAIAIAQQAIAPABAXQAAAfgMAfQgLAfgXAbQgYAcgmARg");
	this.shape_60.setTransform(640.4,523.15);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#333333").s().p("ABxEeIAAlMIhAAAIAAABQABAsgGAsQgGAugUArQgUAsgpAmQgqAnhGAcIgEgEQAogjAZglQAZgnANgpQANgpAEgqQAEgqAAgtIAAjFIBVAdQAkgSAggTQAggTAWgQIBaBTQgHAFgLAAQgMAAgPgFQghAGgsAFQgsAGgvAEIAAB2IBwAAIAqg6IAOALIAeAaIAfAdQgBAFgEACQgFACgGAAIg8AAIAAE5QgBACgIAFQgJAEgQAEQgQAEgWAAgAkVCrIAAmZIBSAhIAgAAIAlgoIBLA5QgDAFgGADQgGADgJADIAAEYQgBAEgLAFQgLAFgQAEQgPADgPAAIgNAAIAAg/IgnAAIAABPQgBAFgJAGQgKAHgPAFQgQAFgSAAgAjEAvIAnAAIAAjrIgnAAg");
	this.shape_61.setTransform(603.475,497.85);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#333333").s().p("AkXAxIgFgTIGfAAIA4hOIAKAJIAaAWIAgAcIAeAdQgBAFgFACQgFACgIAAg");
	this.shape_62.setTransform(542.375,492.725);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#333333").s().p("ABxEeIAAlMIhAAAIAAABQABAsgGAsQgGAugUArQgUAsgpAmQgqAnhGAcIgEgEQAogjAZglQAZgnANgpQANgpAEgqQAEgqAAgtIAAjFIBVAdQAkgSAggTQAggTAWgQIBaBTQgHAFgLAAQgMAAgPgFQghAGgsAFQgsAGgvAEIAAB2IBwAAIAqg6IAOALIAeAaIAfAdQgBAFgEACQgFACgGAAIg8AAIAAE5QgBACgIAFQgJAEgQAEQgQAEgWAAgAkVCrIAAmZIBSAhIAgAAIAlgoIBLA5QgDAFgGADQgGADgJADIAAEYQgBAEgLAFQgLAFgQAEQgPADgPAAIgNAAIAAg/IgnAAIAABPQgBAFgJAGQgKAHgPAFQgQAFgSAAgAjEAvIAnAAIAAjrIgnAAg");
	this.shape_63.setTransform(483.475,497.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31,p:{x:1120.275,y:493.075}},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19}]}).to({state:[{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_31,p:{x:962.375,y:492.725}},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43}]},5).wait(5));

	// bg
	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("EiLsBMwQhvAAhQhPQhPhPAAhwMAAAiRDQAAhwBPhPQBQhPBvAAMEXZAAAQBvAABPBPQBQBPAABwMAAACRDQAABwhQBPQhPBPhvAAg");
	this.shape_64.setTransform(959.9897,540.0003,0.9999,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_64).wait(10));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(999,588.8,882,442.5);
// library properties:
lib.properties = {
	id: '6CC2A54E1AA7D548BDC8E574C2A3EB8B',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#F7C677",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['6CC2A54E1AA7D548BDC8E574C2A3EB8B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;