(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"复习_atlas_P_1", frames: [[0,0,1243,186]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap1 = function() {
	this.initialize(ss["复习_atlas_P_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.lnav2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.6)").s().p("ABACSIgggBIgCgLQgCgGgEgFIAiABIAXABIAIgBQADgBADgDQAFgEADgNQAEgNACgXIAEg7IAEhVIizAAQgNAZgOAVQgPAWgQAPIgJgGIgJgHQARgRAPgWQAPgVAMgaQAMgZAJgbIAVAFIgHAVIgIAVIC/AAIAAACIAAAFIAAAEIgEBfQgCAogDAZQgDAagEAOQgDAOgFAGQgGAHgGACQgGADgKABIgOAAIgJAAgAhNBqIAAiJIB7AAIAABxIhnAAIAAAYgAg5A/IBRAAIAAhKIhRAAg");
	this.shape.setTransform(203.5,24.2833);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.6)").s().p("AiJCHIgIgHQAUgSALgVQAMgVAGgWQAFgWACgVIg2AAIAAgSIA3AAIAAgGIAAgHIAAgzIgTAAIgJAbQgFANgGALIgIgGIgJgGQAIgMAFgRQAGgQAEgTIAHgmIAUAEIgEAUIgEATIBKAAIAAAUIgoAAIAAAzIAAAHIAAAGIAtAAIAAASIgvAAIgBANIgCANIALAPIAOASIANASIAJAMIgOASIgKgRIgOgVIgOgTQgGAYgNAXQgNAXgVAUIgGgIgAgeCKIAAgUIBjAAIALgZIALgcIAIgbIAWAFIgKAZIgLAbIgKAXIA4AAIAAAUgAAUBbIgIgXIgKgXIASgFIAKAXIAIAXIAGAVIgTAFIgFgVgAgGAaIAAhiICHAAIAABigAANAGIBgAAIAAg7IhgAAgAgRhsIAAgUICgAAIAAAUg");
	this.shape_1.setTransform(172.175,23.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.6)").s().p("ABQCBQgRgKgTgJQgSgJgSgHIAOgOIAkAQQATAIAQAKQASAJALAIIgPAPQgLgIgQgJgAhwCKIgHgIQAcgIATgJQATgJAMgKQAMgJAGgKIhRAAIAAgSIBaAAQACgHABgIIABgNIAAAAIgyAAIAAgMQgPAOgSAMQgSAMgWAJIgHgJIgIgHQAegMAXgQQAWgRARgTIhVAAIAAgSIBhAAIAIgNIAHgMIhNAAIAAgSIBUAAIAEgMIADgNIhnAAIAAgRIBrAAIABgOIABgMIAUABIgBAMIgBANIBtAAIAAARIhxAAIgDANIgCAMIBpAAIAAASIhwAAIgGAMIgGANICeAAIAAASIhVAAQAQAUAaAQQAYARAcAIIgHAIQgEAFgCAEQgVgHgTgMQgTgMgQgPIAAANIgzAAIAAABIgBANIgCAOIBfAAIAAASIhlAAQgFAMgMANQgNANgWALQgWAMghAKIgFgIgAA2ALIgMgMQgHgHgEgIIg+AAIgLAPIgMAMIBsAAIAAAAg");
	this.shape_2.setTransform(140.35,24.275);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.6)").s().p("AgqCSIAAieIhVAAIAAgUIDsAAIAABqQABAKgEAGQgDAGgIACQgIADgPAAQgPABgWAAIgDgLIgEgLIAhAAIATAAQAEAAACgCQACgBgBgEIAAhVIhrAAIAACegAArgyIAAglIhWAAIAAAlIgWAAIAAglIhLAAIAAgVIBLAAIAAglIAWAAIAAAlIBWAAIAAglIAWAAIAAAlIBMAAIAAAVIhMAAIAAAlg");
	this.shape_3.setTransform(108.225,24.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(0,0,0,0.6)").s().p("Ag6CKIgJgHQAXgPANgXQAOgVAGgbQAHgaADgcQABgdABgeIg3AAIAAgVIDJAAIAAAVIh8AAIgBAYIgBAZIBmAAIAAAKIgFBMQgDAegDAPQgDAPgFAGQgEAEgFACQgGADgHAAIgSABIgYgBIgCgKIgFgKIAZACIAQAAQAEAAADgBIAEgEQAEgDADgNQADgNACgZIADhBIhRAAQgDAegIAbQgIAbgNAXQgPAWgXAQIgHgHgAhnCRIAAi0IgPAVIgPARIgGgJIgHgLQAPgPAOgVQAOgVAMgXQAMgXAIgYIAVAFQgHATgIARQgIASgKARIAADVgAAphqIgGgRIgFgRIAUgEIAGAQIAGARIAEAOIgWAGIgDgPg");
	this.shape_4.setTransform(76.075,24.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(0,0,0,0.6)").s().p("ABQB4QgWgSgMgcIgBAAQgGASgLANQgMAOgRAKQgTAKgcAHIgFgJIgGgIQAYgFAQgIQARgIAJgKQAKgKAGgOIhKAAIAAgSIBQAAIADgNIACgPIhAAAIAAhgICaAAIAABgIhEAAIgCAPIgDANIBaAAIAAASIhKAAQALAVAVAOQAVANAcAGIgHAJIgHAJQgfgIgXgSgAgKAMIByAAIAAgXIhyAAgAgKgbIByAAIAAgZIhyAAgAhlCRIAAiVQgHAYgJAWQgJAWgJAQIgGgLIgGgKQAKgNAIgVQAJgUAHgWQAIgYAEgWIgoAAIAAgUIAoAAIAAg+IAUAAIAAA+IAiAAIAAAUIgiAAIAAANIAJAOIAMATIAKARIAHAMIgNAQIgHgOIgIgRIgKgSIAACmgABKhKIAAgZIgyAAIAAAZIgVAAIAAgZIgvAAIAAgTIAvAAIAAgaIAVAAIAAAaIAyAAIAAgaIAVAAIAAAaIAvAAIAAATIgvAAIAAAZg");
	this.shape_5.setTransform(44.175,24.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(0,0,0,0.6)").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_6.setTransform(23.85,34.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(0,0,0,0.6)").s().p("AhHB3IAAgPQA4gxAZglQAbglgBgeQAAgOgFgKQgEgLgKgHQgKgGgOAAQgPAAgMAIQgNAIgKAMIgPgPQANgQARgJQAQgJAWAAQAeAAASASQASATAAAfQAAAYgMAYQgLAXgWAaQgUAZgcAbIATgCIASAAIBDAAIAAAWg");
	this.shape_7.setTransform(10.625,24.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F7C677").s().p("ABACSIgggBIgCgLQgCgGgEgFIAiABIAXABIAIgBQADgBADgDQAFgEADgNQAEgNACgXIAEg7IAEhVIizAAQgNAZgOAVQgPAWgQAPIgJgGIgJgHQARgRAPgWQAPgVAMgaQAMgZAJgbIAVAFIgHAVIgIAVIC/AAIAAACIAAAFIAAAEIgEBfQgCAogDAZQgDAagEAOQgDAOgFAGQgGAHgGACQgGADgKABIgOAAIgJAAgAhNBqIAAiJIB7AAIAABxIhnAAIAAAYgAg5A/IBRAAIAAhKIhRAAg");
	this.shape_8.setTransform(203.5,24.2833);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F7C677").s().p("AiJCHIgIgHQAUgSALgVQAMgVAGgWQAFgWACgVIg2AAIAAgSIA3AAIAAgGIAAgHIAAgzIgTAAIgJAbQgFANgGALIgIgGIgJgGQAIgMAFgRQAGgQAEgTIAHgmIAUAEIgEAUIgEATIBKAAIAAAUIgoAAIAAAzIAAAHIAAAGIAtAAIAAASIgvAAIgBANIgCANIALAPIAOASIANASIAJAMIgOASIgKgRIgOgVIgOgTQgGAYgNAXQgNAXgVAUIgGgIgAgeCKIAAgUIBjAAIALgZIALgcIAIgbIAWAFIgKAZIgLAbIgKAXIA4AAIAAAUgAAUBbIgIgXIgKgXIASgFIAKAXIAIAXIAGAVIgTAFIgFgVgAgGAaIAAhiICHAAIAABigAANAGIBgAAIAAg7IhgAAgAgRhsIAAgUICgAAIAAAUg");
	this.shape_9.setTransform(172.175,23.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F7C677").s().p("ABQCBQgRgKgTgJQgSgJgSgHIAOgOIAkAQQATAIAQAKQASAJALAIIgPAPQgLgIgQgJgAhwCKIgHgIQAcgIATgJQATgJAMgKQAMgJAGgKIhRAAIAAgSIBaAAQACgHABgIIABgNIAAAAIgyAAIAAgMQgPAOgSAMQgSAMgWAJIgHgJIgIgHQAegMAXgQQAWgRARgTIhVAAIAAgSIBhAAIAIgNIAHgMIhNAAIAAgSIBUAAIAEgMIADgNIhnAAIAAgRIBrAAIABgOIABgMIAUABIgBAMIgBANIBtAAIAAARIhxAAIgDANIgCAMIBpAAIAAASIhwAAIgGAMIgGANICeAAIAAASIhVAAQAQAUAaAQQAYARAcAIIgHAIQgEAFgCAEQgVgHgTgMQgTgMgQgPIAAANIgzAAIAAABIgBANIgCAOIBfAAIAAASIhlAAQgFAMgMANQgNANgWALQgWAMghAKIgFgIgAA2ALIgMgMQgHgHgEgIIg+AAIgLAPIgMAMIBsAAIAAAAg");
	this.shape_10.setTransform(140.35,24.275);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F7C677").s().p("AgqCSIAAieIhVAAIAAgUIDsAAIAABqQABAKgEAGQgDAGgIACQgIADgPAAQgPABgWAAIgDgLIgEgLIAhAAIATAAQAEAAACgCQACgBgBgEIAAhVIhrAAIAACegAArgyIAAglIhWAAIAAAlIgWAAIAAglIhLAAIAAgVIBLAAIAAglIAWAAIAAAlIBWAAIAAglIAWAAIAAAlIBMAAIAAAVIhMAAIAAAlg");
	this.shape_11.setTransform(108.225,24.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F7C677").s().p("Ag6CKIgJgHQAXgPANgXQAOgVAGgbQAHgaADgcQABgdABgeIg3AAIAAgVIDJAAIAAAVIh8AAIgBAYIgBAZIBmAAIAAAKIgFBMQgDAegDAPQgDAPgFAGQgEAEgFACQgGADgHAAIgSABIgYgBIgCgKIgFgKIAZACIAQAAQAEAAADgBIAEgEQAEgDADgNQADgNACgZIADhBIhRAAQgDAegIAbQgIAbgNAXQgPAWgXAQIgHgHgAhnCRIAAi0IgPAVIgPARIgGgJIgHgLQAPgPAOgVQAOgVAMgXQAMgXAIgYIAVAFQgHATgIARQgIASgKARIAADVgAAphqIgGgRIgFgRIAUgEIAGAQIAGARIAEAOIgWAGIgDgPg");
	this.shape_12.setTransform(76.075,24.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F7C677").s().p("ABQB4QgWgSgMgcIgBAAQgGASgLANQgMAOgRAKQgTAKgcAHIgFgJIgGgIQAYgFAQgIQARgIAJgKQAKgKAGgOIhKAAIAAgSIBQAAIADgNIACgPIhAAAIAAhgICaAAIAABgIhEAAIgCAPIgDANIBaAAIAAASIhKAAQALAVAVAOQAVANAcAGIgHAJIgHAJQgfgIgXgSgAgKAMIByAAIAAgXIhyAAgAgKgbIByAAIAAgZIhyAAgAhlCRIAAiVQgHAYgJAWQgJAWgJAQIgGgLIgGgKQAKgNAIgVQAJgUAHgWQAIgYAEgWIgoAAIAAgUIAoAAIAAg+IAUAAIAAA+IAiAAIAAAUIgiAAIAAANIAJAOIAMATIAKARIAHAMIgNAQIgHgOIgIgRIgKgSIAACmgABKhKIAAgZIgyAAIAAAZIgVAAIAAgZIgvAAIAAgTIAvAAIAAgaIAVAAIAAAaIAyAAIAAgaIAVAAIAAAaIAvAAIAAATIgvAAIAAAZg");
	this.shape_13.setTransform(44.175,24.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F7C677").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_14.setTransform(23.85,34.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F7C677").s().p("AhHB3IAAgPQA4gxAZglQAbglgBgeQAAgOgFgKQgEgLgKgHQgKgGgOAAQgPAAgMAIQgNAIgKAMIgPgPQANgQARgJQAQgJAWAAQAeAAASASQASATAAAfQAAAYgMAYQgLAXgWAaQgUAZgcAbIATgCIASAAIBDAAIAAAWg");
	this.shape_15.setTransform(10.625,24.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},2).wait(2));

	// 图层_2
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AyfEUIAAonMAk/AAAIAAIng");
	this.shape_16.setTransform(114.675,22.775);

	this.timeline.addTween(cjs.Tween.get(this.shape_16).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.7,-4.8,236.79999999999998,55.199999999999996);


(lib.lnav1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.6)").s().p("AhcCQIAAiMQgIAZgLAWQgLAWgLAPIgFgKIgHgKQAJgMAJgRQAKgRAIgUQAIgSAGgTIgrAAIAAgUIAuAAIAAg2IgRAEIgSADIgDgIIgEgIIAfgHIAegJQANgEALgFIANARIgRAGIgTAGIAAA7IApAAIAAAUIgpAAIAAAIIAJAMIALAPIALAQIAHALIgNASIgHgNIgJgRIgJgQIAACRgAgmCIIAAgUIBUAAIAAgvIg/AAIAAgUIA/AAIAAgrIhGAAIAAgTICjAAIAAATIhIAAIAAArIBCAAIAAAUIhCAAIAAAvIBPAAIAAAUgAgSgqIAAhdICSAAIAABdgAABg8IBqAAIAAg4IhqAAg");
	this.shape.setTransform(204,24.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.6)").s().p("AhgCTIAAiLIDEAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiNgTIAAgUIBSAAQgCgLgFgNQgFgNgHgLIAUgFQAFAIAEAJQAFAIADAJIAFAQIgOADIBXAAIAJgRIAIgUIAHgRIAWAGIgLAYIgNAYIBTAAIAAAUgAh6hfIAAgTIB0AAIgFgOIgHgOIATgEIAKAQIAHAQIBsAAIAAATg");
	this.shape_1.setTransform(172.2,24.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.6)").s().p("AAgCSIAAgyIhXAAIAAgUIBXAAIAAgcIhIAAIAAgTIBIAAIAAgbIhEAAIAAgRIBEAAIAAgeIhSAAIAAgSIBSAAIAAgdIhDAAIAAgSIBDAAIAAgjIAVAAIAAAjIBHAAIAAAvIAXAAIAAASIgXAAIAAAvIhHAAIAAAbIBLAAIAAATIhLAAIAAAcIBbAAIAAAUIhbAAIAAAygAA1gPIAyAAIAAgeIgyAAgAA1g/IAyAAIAAgdIgyAAgAhhCRIAAiUIgTASIgTARIgFgJIgGgKQAOgLAOgNQAOgOANgQQAMgQAJgRIATAHIgMAUIgOATIAACtgAiHhFIgGgIQANgJAMgLQANgLALgMQALgMAHgMIAVAIQgKAOgNANQgMAOgOAMQgOANgOAKIgFgJg");
	this.shape_2.setTransform(140.025,24.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.6)").s().p("AiMCKIgIgHQASgUAIgeQAJgfADgmQACgmAAguIgjAAIAAgUIBAAAQgEgKgGgMIgNgXIASgGIAOAXIALAVIgRAHIA8AAIAAAUIhIAAIAAAWIgBAVIA7AAIAAAKIgCBCIgDAtQgBARgCAKQgCAJgDAEQgDAFgFACIgKADIgOABIgSgBIgCgKIgDgJIARABIALAAQAEAAACgBQACgBACgCQACgEACgNQACgNABgcIADhHIgnAAQgCAhgEAcQgEAdgJAYQgJAXgPASIgIgIgAgXCJIgIgHQAOgNAHgUQAHgVADgYQACgYABgaIATAAIgBAZIgCAYQAFAWAJAOQAIANALAIIAAiJIg2AAIAAgTICBAAIADgBIAOAFIgNAeQgGAOgGAKIgRgGIAIgPIAHgSIgtAAIAAA5IA+AAIAAATIg+AAIAABFIAOADIAPABIAJAAIAOAAIAPgBIAKAAIgEAKIgCAKIgrAAQgUAAgQgEQgRgFgMgMQgNgMgJgWQgFASgHAQQgGAPgMAMQgCgEgEgEgAgSgtIgJgGQAPgSAMgYQALgYAHgcIAVAEIgGATIgHATIB4AAIAAATIiAAAIgOAZQgGAMgIAJIgIgHg");
	this.shape_3.setTransform(108.125,24.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(0,0,0,0.6)").s().p("AgiCLIAAiLICoAAIAACKIgWAAIAAgLIh9AAIAAAMgAgNBsIB9AAIAAgkIh9AAgAgNA1IB9AAIAAgiIh9AAgAiEBVIAAjOIBPAAIAACwIg8AAIAAAegAhxAiIAoAAIAAiHIgoAAgAgYgWIAAh0ICRAAIAAB0gAgEgoIBpAAIAAggIhpAAgAgEhYIBpAAIAAghIhpAAg");
	this.shape_4.setTransform(76.25,24.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(0,0,0,0.6)").s().p("ABQB4QgWgSgMgcIgBAAQgGASgLANQgMAOgRAKQgTAKgcAHIgFgJIgGgIQAYgFAQgIQARgIAJgKQAKgKAGgOIhKAAIAAgSIBQAAIADgNIACgPIhAAAIAAhgICaAAIAABgIhEAAIgCAPIgDANIBaAAIAAASIhKAAQALAVAVAOQAVANAcAGIgHAJIgHAJQgfgIgXgSgAgKAMIByAAIAAgXIhyAAgAgKgbIByAAIAAgZIhyAAgAhlCRIAAiVQgHAYgJAWQgJAWgJAQIgGgLIgGgKQAKgNAIgVQAJgUAHgWQAIgYAEgWIgoAAIAAgUIAoAAIAAg+IAUAAIAAA+IAiAAIAAAUIgiAAIAAANIAJAOIAMATIAKARIAHAMIgNAQIgHgOIgIgRIgKgSIAACmgABKhKIAAgZIgyAAIAAAZIgVAAIAAgZIgvAAIAAgTIAvAAIAAgaIAVAAIAAAaIAyAAIAAgaIAVAAIAAAaIAvAAIAAATIgvAAIAAAZg");
	this.shape_5.setTransform(44.175,24.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(0,0,0,0.6)").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_6.setTransform(23.85,34.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(0,0,0,0.6)").s().p("Ag+B1IAAgVIA0AAIAAizIgpAAIAAgSQAPgCAMgEQALgEAKgFIASAAIAADUIAwAAIAAAVg");
	this.shape_7.setTransform(11.15,24.65);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(241,171,78,0.4)").s().p("AhcCQIAAiMQgIAZgLAWQgLAWgLAPIgFgKIgHgKQAJgMAJgRQAKgRAIgUQAIgSAGgTIgrAAIAAgUIAuAAIAAg2IgRAEIgSADIgDgIIgEgIIAfgHIAegJQANgEALgFIANARIgRAGIgTAGIAAA7IApAAIAAAUIgpAAIAAAIIAJAMIALAPIALAQIAHALIgNASIgHgNIgJgRIgJgQIAACRgAgmCIIAAgUIBUAAIAAgvIg/AAIAAgUIA/AAIAAgrIhGAAIAAgTICjAAIAAATIhIAAIAAArIBCAAIAAAUIhCAAIAAAvIBPAAIAAAUgAgSgqIAAhdICSAAIAABdgAABg8IBqAAIAAg4IhqAAg");
	this.shape_8.setTransform(204,24.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(241,171,78,0.4)").s().p("AhgCTIAAiLIDEAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiNgTIAAgUIBSAAQgCgLgFgNQgFgNgHgLIAUgFQAFAIAEAJQAFAIADAJIAFAQIgOADIBXAAIAJgRIAIgUIAHgRIAWAGIgLAYIgNAYIBTAAIAAAUgAh6hfIAAgTIB0AAIgFgOIgHgOIATgEIAKAQIAHAQIBsAAIAAATg");
	this.shape_9.setTransform(172.2,24.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(241,171,78,0.4)").s().p("AAgCSIAAgyIhXAAIAAgUIBXAAIAAgcIhIAAIAAgTIBIAAIAAgbIhEAAIAAgRIBEAAIAAgeIhSAAIAAgSIBSAAIAAgdIhDAAIAAgSIBDAAIAAgjIAVAAIAAAjIBHAAIAAAvIAXAAIAAASIgXAAIAAAvIhHAAIAAAbIBLAAIAAATIhLAAIAAAcIBbAAIAAAUIhbAAIAAAygAA1gPIAyAAIAAgeIgyAAgAA1g/IAyAAIAAgdIgyAAgAhhCRIAAiUIgTASIgTARIgFgJIgGgKQAOgLAOgNQAOgOANgQQAMgQAJgRIATAHIgMAUIgOATIAACtgAiHhFIgGgIQANgJAMgLQANgLALgMQALgMAHgMIAVAIQgKAOgNANQgMAOgOAMQgOANgOAKIgFgJg");
	this.shape_10.setTransform(140.025,24.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(241,171,78,0.4)").s().p("AiMCKIgIgHQASgUAIgeQAJgfADgmQACgmAAguIgjAAIAAgUIBAAAQgEgKgGgMIgNgXIASgGIAOAXIALAVIgRAHIA8AAIAAAUIhIAAIAAAWIgBAVIA7AAIAAAKIgCBCIgDAtQgBARgCAKQgCAJgDAEQgDAFgFACIgKADIgOABIgSgBIgCgKIgDgJIARABIALAAQAEAAACgBQACgBACgCQACgEACgNQACgNABgcIADhHIgnAAQgCAhgEAcQgEAdgJAYQgJAXgPASIgIgIgAgXCJIgIgHQAOgNAHgUQAHgVADgYQACgYABgaIATAAIgBAZIgCAYQAFAWAJAOQAIANALAIIAAiJIg2AAIAAgTICBAAIADgBIAOAFIgNAeQgGAOgGAKIgRgGIAIgPIAHgSIgtAAIAAA5IA+AAIAAATIg+AAIAABFIAOADIAPABIAJAAIAOAAIAPgBIAKAAIgEAKIgCAKIgrAAQgUAAgQgEQgRgFgMgMQgNgMgJgWQgFASgHAQQgGAPgMAMQgCgEgEgEgAgSgtIgJgGQAPgSAMgYQALgYAHgcIAVAEIgGATIgHATIB4AAIAAATIiAAAIgOAZQgGAMgIAJIgIgHg");
	this.shape_11.setTransform(108.125,24.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(241,171,78,0.4)").s().p("AgiCLIAAiLICoAAIAACKIgWAAIAAgLIh9AAIAAAMgAgNBsIB9AAIAAgkIh9AAgAgNA1IB9AAIAAgiIh9AAgAiEBVIAAjOIBPAAIAACwIg8AAIAAAegAhxAiIAoAAIAAiHIgoAAgAgYgWIAAh0ICRAAIAAB0gAgEgoIBpAAIAAggIhpAAgAgEhYIBpAAIAAghIhpAAg");
	this.shape_12.setTransform(76.25,24.85);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(241,171,78,0.4)").s().p("ABQB4QgWgSgMgcIgBAAQgGASgLANQgMAOgRAKQgTAKgcAHIgFgJIgGgIQAYgFAQgIQARgIAJgKQAKgKAGgOIhKAAIAAgSIBQAAIADgNIACgPIhAAAIAAhgICaAAIAABgIhEAAIgCAPIgDANIBaAAIAAASIhKAAQALAVAVAOQAVANAcAGIgHAJIgHAJQgfgIgXgSgAgKAMIByAAIAAgXIhyAAgAgKgbIByAAIAAgZIhyAAgAhlCRIAAiVQgHAYgJAWQgJAWgJAQIgGgLIgGgKQAKgNAIgVQAJgUAHgWQAIgYAEgWIgoAAIAAgUIAoAAIAAg+IAUAAIAAA+IAiAAIAAAUIgiAAIAAANIAJAOIAMATIAKARIAHAMIgNAQIgHgOIgIgRIgKgSIAACmgABKhKIAAgZIgyAAIAAAZIgVAAIAAgZIgvAAIAAgTIAvAAIAAgaIAVAAIAAAaIAyAAIAAgaIAVAAIAAAaIAvAAIAAATIgvAAIAAAZg");
	this.shape_13.setTransform(44.175,24.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(241,171,78,0.4)").s().p("AgNAPQgGgFAAgJQAAgJAGgGQAFgFAIgBQAJABAFAFQAGAGAAAJQAAAJgGAFQgFAGgJAAQgIAAgFgGg");
	this.shape_14.setTransform(23.85,34.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(241,171,78,0.4)").s().p("Ag+B1IAAgVIA0AAIAAizIgpAAIAAgSQAPgCAMgEQALgEAKgFIASAAIAADUIAwAAIAAAVg");
	this.shape_15.setTransform(11.15,24.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},1).wait(3));

	// 图层_2
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AyfEUIAAonMAk/AAAIAAIng");
	this.shape_16.setTransform(118.425,18.625);

	this.timeline.addTween(cjs.Tween.get(this.shape_16).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-9,236.9,57);


// stage content:
(lib.复习 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {lnav1:0,lnav2:5};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,5];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		
		var _this = this;
		
		
		
		_this.lnav1_btn.on('click', function(){
		
		_this.gotoAndStop('lnav1');
		});
		
		
		_this.lnav2_btn.on('click', function(){
		
		_this.gotoAndStop('lnav2');
		});
	}
	this.frame_5 = function() {
		this.stop();
		
		
		
		
		var _this = this;
		/*
		单击指定元件实例时将执行相应函数。
		*/
		_this.m1_btn.on('click', function(){
		/*
		将播放头移动到时间轴中的指定帧标签并继续从该帧播放。
		可在主时间轴或影片剪辑时间轴上使用。
		*/
		_this.gotoAndPlay('m1');
		});
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(5).call(this.frame_5).wait(5));

	// leftnav_on
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E28624").s().p("AhcCQIAAiMQgJAZgKAWQgKAWgMAPIgGgKIgGgKQAKgMAJgRQAJgRAIgUQAIgSAGgTIgrAAIAAgUIAuAAIAAg2IgRAEIgSADIgDgIIgDgIIAegHIAegJQANgEAKgFIAPARIgSAGIgTAGIAAA7IAoAAIAAAUIgoAAIAAAIIAJAMIALAPIALAQIAIALIgPASIgGgNIgIgRIgKgQIAACRgAgmCIIAAgUIBUAAIAAgvIg+AAIAAgUIA+AAIAAgrIhGAAIAAgTICjAAIAAATIhIAAIAAArIBCAAIAAAUIhCAAIAAAvIBPAAIAAAUgAgRgqIAAhdICRAAIAABdgAABg8IBqAAIAAg4IhqAAg");
	this.shape.setTransform(306.3,442.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E28624").s().p("AhfCTIAAiLIDDAAIAACLIgWAAIAAgMIiZAAIAAAMgAhLB1ICZAAIAAglIiZAAgAhLA+ICZAAIAAgjIiZAAgAiMgTIAAgUIBSAAQgCgLgGgNQgFgNgHgLIAUgFQAGAIADAJQAFAIADAJIAEAQIgNADIBXAAIAJgRIAIgUIAGgRIAYAGIgNAYIgMAYIBSAAIAAAUgAh6hfIAAgTIB1AAIgGgOIgIgOIAVgEIAJAQIAGAQIBtAAIAAATg");
	this.shape_1.setTransform(274.5,442.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E28624").s().p("AAgCRIAAgxIhXAAIAAgUIBXAAIAAgdIhIAAIAAgTIBIAAIAAgaIhEAAIAAgRIBEAAIAAgdIhSAAIAAgTIBSAAIAAgdIhDAAIAAgSIBDAAIAAgiIAVAAIAAAiIBHAAIAAAvIAXAAIAAATIgXAAIAAAuIhHAAIAAAaIBLAAIAAATIhLAAIAAAdIBbAAIAAAUIhbAAIAAAxgAA1gPIAyAAIAAgdIgyAAgAA1g/IAyAAIAAgdIgyAAgAhhCRIAAiVIgTAUIgTARIgFgKIgGgKQAOgLAOgNQAOgOANgQQAMgQAJgRIATAHIgMAUIgOATIAACtgAiHhFIgGgJQANgIAMgLQANgLALgMQALgMAHgLIAVAHQgKAOgNAOQgMANgOANQgOAMgOAJIgFgIg");
	this.shape_2.setTransform(242.325,442.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E28624").s().p("AiMCKIgIgHQASgUAIgeQAJgfADgmQACgmAAguIgjAAIAAgUIBAAAQgEgKgGgMIgNgXIASgGIAOAXIALAVIgRAHIA8AAIAAAUIhIAAIAAAWIgBAVIA7AAIAAAKIgCBCIgDAtQgBARgCAKQgCAJgDAEQgDAFgFACIgKADIgOABIgSgBIgCgKIgDgJIARABIALAAQAEAAACgBQACgBACgCQACgEACgNQACgNABgcIADhHIgnAAQgCAhgEAcQgEAdgJAYQgJAXgPASIgIgIgAgXCJIgIgHQAOgNAHgUQAHgVADgYQACgYABgaIATAAIgBAZIgCAYQAFAWAJAOQAIANALAIIAAiJIg2AAIAAgTICBAAIADgBIAOAFIgNAeQgGAOgGAKIgRgGIAIgPIAHgSIgtAAIAAA5IA+AAIAAATIg+AAIAABFIAOADIAPABIAJAAIAOAAIAPgBIAKAAIgEAKIgCAKIgrAAQgUAAgQgEQgRgFgMgMQgNgMgJgWQgFASgHAQQgGAPgMAMQgCgEgEgEgAgSgtIgJgGQAPgSAMgYQALgYAHgcIAVAEIgGATIgHATIB4AAIAAATIiAAAIgOAZQgGAMgIAJIgIgHg");
	this.shape_3.setTransform(210.425,442.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E28624").s().p("AgiCLIAAiLICnAAIAACJIgVAAIAAgLIh9AAIAAANgAgNBrIB9AAIAAgkIh9AAgAgNA1IB9AAIAAgiIh9AAgAiEBWIAAjOIBPAAIAACuIg8AAIAAAggAhxAiIAoAAIAAiHIgoAAgAgYgWIAAh0ICSAAIAAB0gAgDgnIBoAAIAAghIhoAAgAgDhZIBoAAIAAgfIhoAAg");
	this.shape_4.setTransform(178.55,442.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E28624").s().p("ABQB4QgWgSgMgcIgBAAQgGASgLANQgMAOgRAKQgTAKgcAHIgFgJIgGgIQAYgFAQgIQARgIAJgKQAKgKAGgOIhKAAIAAgSIBQAAIADgNIACgPIhAAAIAAhgICaAAIAABgIhEAAIgCAPIgDANIBaAAIAAASIhKAAQALAVAVAOQAVANAcAGIgHAJIgHAJQgfgIgXgSgAgKAMIByAAIAAgXIhyAAgAgKgbIByAAIAAgZIhyAAgAhlCRIAAiVQgHAYgJAWQgJAWgJAQIgGgLIgGgKQAKgNAIgVQAJgUAHgWQAIgYAEgWIgoAAIAAgUIAoAAIAAg+IAUAAIAAA+IAiAAIAAAUIgiAAIAAANIAJAOIAMATIAKARIAHAMIgNAQIgHgOIgIgRIgKgSIAACmgABKhKIAAgZIgyAAIAAAZIgVAAIAAgZIgvAAIAAgTIAvAAIAAgaIAVAAIAAAaIAyAAIAAgaIAVAAIAAAaIAvAAIAAATIgvAAIAAAZg");
	this.shape_5.setTransform(146.475,442.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E28624").s().p("AgNAPQgFgFgBgJQABgJAFgGQAGgFAHgBQAIABAGAFQAGAGgBAJQABAJgGAFQgGAGgIAAQgHAAgGgGg");
	this.shape_6.setTransform(126.15,452.775);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E28624").s().p("Ag+B1IAAgVIA1AAIAAizIgqAAIAAgRQAPgDAMgEQAMgDAJgGIATAAIAADUIAvAAIAAAVg");
	this.shape_7.setTransform(113.45,442.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E28624").s().p("ABACSIgfgBIgDgLQgCgGgDgFIAhABIAXABIAIgBQAEgBADgDQAEgEADgNQADgNADgXIAFg7IADhVIizAAQgNAZgOAVQgPAWgQAPIgIgGIgKgHQARgRAPgWQAPgVAMgaQAMgZAJgbIAWAFIgIAVIgJAVIDAAAIAAACIAAAFIAAAEIgEBfQgCAogDAZQgCAagEAOQgEAOgFAGQgFAHgHACQgGADgJABIgPAAIgJAAgAhNBqIAAiJIB7AAIAABxIhmAAIAAAYgAg4A/IBRAAIAAhKIhRAAg");
	this.shape_8.setTransform(307.75,506.0333);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E28624").s().p("AiJCHIgIgHQAUgSALgVQAMgVAGgWQAFgWACgVIg2AAIAAgSIA3AAIAAgGIAAgHIAAgzIgTAAIgJAbQgFANgGALIgIgGIgJgGQAIgMAFgRQAGgQAEgTIAHgmIAUAEIgEAUIgEATIBKAAIAAAUIgoAAIAAAzIAAAHIAAAGIAtAAIAAASIgvAAIgBANIgCANIALAPIAOASIANASIAJAMIgOASIgKgRIgOgVIgOgTQgGAYgNAXQgNAXgVAUIgGgIgAgeCKIAAgUIBjAAIALgZIALgcIAIgbIAWAFIgKAZIgLAbIgKAXIA4AAIAAAUgAAUBbIgIgXIgKgXIASgFIAKAXIAIAXIAGAVIgTAFIgFgVgAgGAaIAAhiICHAAIAABigAANAGIBgAAIAAg7IhgAAgAgRhsIAAgUICgAAIAAAUg");
	this.shape_9.setTransform(276.425,505.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E28624").s().p("ABPCBQgQgKgTgJQgTgJgRgHIAPgOIAjAQQATAIARAKQAQAJAMAIIgPAPQgLgIgRgJgAhwCKIgHgIQAbgIAUgJQATgJAMgKQAMgJAHgKIhRAAIAAgSIBZAAQACgHABgIIABgNIAAAAIgxAAIAAgMQgQAOgSAMQgSAMgXAJIgGgJIgHgHQAdgMAXgQQAXgRAQgTIhVAAIAAgSIBhAAIAIgNIAHgMIhNAAIAAgSIBUAAIAEgMIADgNIhoAAIAAgRIBsAAIABgOIABgMIAVABIgCAMIgCANIBuAAIAAARIhxAAIgDANIgDAMIBqAAIAAASIhwAAIgGAMIgGANICfAAIAAASIhXAAQARAUAaAQQAZARAcAIIgIAIQgEAFgCAEQgVgHgTgMQgTgMgQgPIAAANIgzAAIAAABIgBANIgCAOIBgAAIAAASIhmAAQgFAMgNANQgMANgWALQgVAMgiAKIgFgIgAA2ALIgMgMQgGgHgFgIIg+AAIgKAPIgNAMIBsAAIAAAAg");
	this.shape_10.setTransform(244.6,506.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E28624").s().p("AgqCSIAAieIhVAAIAAgUIDsAAIAABqQABAKgEAGQgDAGgIACQgIADgPAAQgPABgWAAIgDgLIgEgLIAhAAIATAAQAEAAACgCQACgBgBgEIAAhVIhrAAIAACegAArgyIAAglIhWAAIAAAlIgWAAIAAglIhLAAIAAgVIBLAAIAAglIAWAAIAAAlIBWAAIAAglIAWAAIAAAlIBMAAIAAAVIhMAAIAAAlg");
	this.shape_11.setTransform(212.475,505.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#E28624").s().p("Ag6CKIgJgHQAXgPANgXQAOgVAGgaQAHgbADgcQABgdABgeIg3AAIAAgVIDJAAIAAAVIh8AAIgBAZIgBAYIBmAAIAAAKIgFBMQgDAegDAPQgDAPgFAFQgEAGgFABQgGADgHAAIgSABIgYgBIgCgLIgFgJIAZABIAQAAQAEABADgBQACgBACgCQAEgEADgNQADgNACgZIADhBIhRAAQgDAegIAbQgIAbgNAXQgPAWgXARIgHgIgAhnCRIAAizIgPAUIgPARIgGgJIgHgKQAPgQAOgVQAOgUAMgYQAMgXAIgYIAVAFQgHASgIASQgIASgKARIAADVgAAphpIgGgSIgFgRIAUgEIAGAQIAGARIAEAOIgWAGIgDgOg");
	this.shape_12.setTransform(180.325,506);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E28624").s().p("AgNAPQgGgFABgJQgBgJAGgGQAGgFAHgBQAIABAGAFQAFAGABAJQgBAJgFAFQgGAGgIAAQgHAAgGgGg");
	this.shape_13.setTransform(128.1,516.425);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#E28624").s().p("AhHB3IAAgPQA4gxAZglQAbglgBgeQAAgOgFgKQgEgLgKgHQgKgGgOAAQgPAAgMAIQgNAIgKAMIgPgPQANgQARgJQAQgJAWAAQAeAAASASQASATAAAfQAAAYgMAYQgLAXgWAaQgUAZgcAbIATgCIASAAIBDAAIAAAWg");
	this.shape_14.setTransform(114.875,506.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5,p:{x:146.475,y:442.275}},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_5,p:{x:148.425,y:505.925}},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},5).wait(5));

	// leftnav
	this.lnav2_btn = new lib.lnav2();
	this.lnav2_btn.name = "lnav2_btn";
	this.lnav2_btn.setTransform(151.45,505.75,1,1,0,0,0,47.2,24);
	new cjs.ButtonHelper(this.lnav2_btn, 0, 1, 2, false, new lib.lnav2(), 3);

	this.lnav1_btn = new lib.lnav1();
	this.lnav1_btn.name = "lnav1_btn";
	this.lnav1_btn.setTransform(149.5,442.1,1,1,0,0,0,47.2,24);
	new cjs.ButtonHelper(this.lnav1_btn, 0, 1, 2, false, new lib.lnav1(), 3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(153,153,153,0.498)").s().p("AAgBoIAAgxQgJALgNALQgMAKgNAHIgFgFIgGgFQAOgGAMgJQAMgJAIgKIAMAEIAAgrIgWACIgWABIgBgFIgDgGIAjgDIAigDIAbgFIANAKIgWAEIgZADIAAAYIAEAFIADAEIAUgNIARgMIAKAIIgTANIgVAMQAKAKANAHQAMAHAOAFQgDABgCAEIgEAGQgQgGgNgKQgOgKgLgMIAAA0gAhCBoIgNgBIgBgHIgDgGIANABIAJAAIAEgBIADgCQADgCACgJIAEgYIADgpIg3AAIADgYIADgdIACgcIANABIgCAXIgCAXIgCAWIAYAAIAEgbIACgeIADgeIg0AAIAAgOIBCAAIgCAiIgEAkIgDAfIAGAAIALAAIAAACIAAAEQgCAegCATQgCATgDAKQgCAKgEADIgGAFIgIACIgKAAgAhsAxIAagGIAegIIABANIgcAIIgaAHgAgSA0IgFgFIAVgMQAKgHAHgHIANAEQgJAJgLAIQgKAJgLAFIgFgEgAAZgFIAAgOIgaAEIgYADIgDgMIAOgCIAAhBIgLAAIAAgMIBGAAIAAAMIgIAAIAAA7IAIgBIAAALIgIABIAAAQgAgCgbIAbgEIAAgNIgbAAgAgCg2IAbAAIAAgOIgbAAgAgChOIAbAAIAAgNIgbAAgAAxgPIgFgFQAHgFAHgGQAHgHAGgJIgLgNIgLgMIAJgHIAKALIAKALIAHgPQADgHACgIIgmAAIAAgNIApAAIADAAIACAAIAIACQgDAPgFAMQgFANgGALIAMAOIAJAMIgKAJIgIgLIgKgNIgNAPQgHAGgIAFIgDgFg");
	this.shape_15.setTransform(189.925,374.775);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(153,153,153,0.498)").s().p("AhjBlIgFgIQBDgIArgYQAsgZAVgqIAPAHQgXAtguAbQgsAZhFALIgDgIgAgFA5IAAhLIhhAAIAAgQIAlAAIAAg2IAQAAIAAA2IAuAAIAAhJIAPAAIAAAaIBHAAIAAAPIhHAAIAAAgIBdAAIAAAQIheAAIAABLgAhYAyIgGgFQAOgLAMgOQANgOAJgNIAPAEQgKAQgOAQQgNAQgOALIgGgGg");
	this.shape_16.setTransform(166.075,374.25);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(153,153,153,0.498)").s().p("AgBBlIgHgFQAPgPAKgWQAJgVAEgZQAGgZAAgbIgiAAIAAgQIAjAAIABgZIAAgaIAQAAIgBAaIAAAZIA1AAIAAAJIgDA9IgDAqIgDAaQgDAJgDADQgEAFgEACIgJACIgOAAIgTgBIgCgHIgDgIIATABIANAAIAFAAIAEgDQADgEADgNIAEgoIADhEIgmAAQgCAdgEAbQgFAbgKAXQgKAXgSARIgEgGgAhjBGIgDgIQACgBADgEIAGgLIAFgPIAHgXIAIgaIgiAAIAAgPIBpAAIAAAPIg3AAQgFASgGAUIgOAkIA8gMIgHgUIgIgTIAOgDIAJAXIAJAYIAFAUIgNAFIgCgIIgDgJIgoAJIgYAFIgLAEIgGACIgCgHgAhghMIAAgOIBbAAIAAAOg");
	this.shape_17.setTransform(142.25,374.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(153,153,153,0.498)").s().p("AhqBiIAAgQICJAAIAEgTIACgVIhsAAIAHgbIAGgfIAGgiIAGgfIg0AAIAAgPIDGAAIAAAPIiBAAIgEATIgDAVIBVAAIADgBIAMABIgDAbIgEAgIgEAgIgFAgIA7AAIAAAQgAgsABIgGAaIBZAAIAEgcIADgZIhWAAIgEAbg");
	this.shape_18.setTransform(118.3,374.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("ABCEnQABgYgEgRQgEgRgIgJQgJgMgSgJQgRgJgZgGIAAgHIAiACIAiACIAaABQAIAAAHgDQAHgCAFgFQAOgMAKgtQAJgsAHhNQg6AkhUArQhTArh1A1QgDAGgEAFQgFAFgGACIg9hrQAcgGAsgMIBlgaIB3ghQBAgRBDgVIAFhaIAFhrImhAAIgGgSIGfAAIA0g1IBQBKQgDAFgIAEQgHAEgMACQgEBvgFBRQgFBPgIA2QgIA2gMAhQgMAhgRAQQgVAWgaAJQgZAKgkAAIgEgBgAgSgbQgbgYgkgZQgjgZgngVQgmgWgjgNIADgHQBMgLA0AFQA1AGAfAQQAfAQAOAVQANAVgCAUQgDAUgQAMQgOALgWAAIgGAAg");
	this.shape_19.setTransform(230.175,295.4012);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AB7EZQg0gPgsgXQhEAdhTAQQhTAOheADIgBgIQBNgPBFgWQBGgYA4ggQgTgQgQgRQgQgSgOgWQgbAagiAVQgiAWgmAPIgFgGQAWgYAUgdQATgdAPgfQAOgfAKgdIgNACIgMABIgNAAIAAisQgcAbgeAVQgeAVggAQIgFgFQAXgdAYgoQAXgoAUguQAUgvAOgxIB0AvQgDAGgHADQgGADgLgBIgHALIgGAKIDsAAIAxg+IAQAMIAkAbIAmAeQgBAFgFACQgFADgIAAIlvAAIgMARIgMAPIA4AWICjAAIAogtIBVBAQgDADgHAEQgFAEgKACIAACFQgBADgNAFQgNAEgSAEQgRAEgQgBIgQAAIAAgTIiuAAIAAAAQAAACgDADIgIAGIBOAhQgCAFgFAEQgGADgLgBIgEAHIgFAHICJAAIA4gvIBOBLQgDAGgHACQgHACgMABQgjAqguAgQAuAHAwADQAwADAuAAIAAAJQgdAIgQAYQgRAYgGAiQg7gJg1gPgAhHBtIgLAKQAUARAaANQAZANAdAJQAWgQASgTQASgSAOgVIiXAAIgKAMgAhQgGICuAAIAAg4IiuAAgAhQhQICuAAIAAg5IiuAAg");
	this.shape_20.setTransform(133.325,294.25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#CCCCCC").ss(1,1,1).p("AzdAAMAm7AAA");
	this.shape_21.setTransform(228.875,350.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.lnav1_btn},{t:this.lnav2_btn}]}).wait(10));

	// 不动内容
	this.instance = new lib.Bitmap1();
	this.instance.setTransform(450,355);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AgqBKQgUgMgLgTQgLgUgBgXQABgYALgSQALgUAUgMQATgLAYAAQAYAAATALQATAMALAUQALASAAAYQAAAXgLAUQgLATgTAMQgTALgYAAQgYAAgTgLgAgrgrQgSARAAAaQAAAaASASQARASAbABQAagBARgSQASgSABgaQgBgagSgRQgRgTgaAAQgaAAgSATg");
	this.shape_22.setTransform(2452.7,754.75);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AjSEcIAAo4IBpAKQAAAHgFAEQgFAFgMACIAABJIAEgCQAcALAQAMQAPAMAFAMQAFgaADgaQADgbABgaIBeAaIAAg9IBqAJQgBAHgEAEQgEADgKADIAACHIAiAAIApg5IANAMIAdAYIAfAcQgBAFgFACQgEADgHAAIiDAAIAACTIAbAAIAng4IANAKIAcAZIAdAcQgBAFgFACQgFACgGAAIh3AAIAAC5IApAAIArg7IAOALIAfAbIAgAcQgBAFgFADQgEADgGgBIl0AAIgFgRICRAAIAAi5IhlAAIgFgQIBqAAIAAiTIgzAAQgRAlgVAeQgWAfgaAWIgIgDQAKgYAHgcQAIgdAHgfQgJAHgNAAQgMAAgMgMQABgUgEgUQgFgVgHgQIAAG3QAAAEgKAFQgKAFgPAEQgPAFgRgBgAAfjKIgNAsIgQApIAtAAIAAhYQgFADgLAAgAkRgEQgKgCgGgKQgIgOAEgMQAFgNAMgKQAHgJAIgQQAHgRAEgVQAEgTgCgVIAJAAQAVA1AAAnQgBAmgPAWQgHAIgLAEQgFACgGAAIgKgCg");
	this.shape_23.setTransform(2411.8804,735.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AC1EBIgDgUQgCgKgFgHQgHgIgLgDIAAgHIAIAAIAPAAQAEAAACgBQACgCAAgDIAAhQIgjAAIAAB+QgBACgHAFQgHAFgOAEQgMADgTABIgNAAIAAiSIgiAAQgEAggMAeQgLAegZAbQgYAbgrAXIgFgFQAZgfALglQALgkADgpQADgoAAgrIAAiTIgTANIgVAMIgGgFQAQgaAPghQAOgiAMgmQAKgmAHgoIBsAiQgCAGgGADQgGADgKAAIgHAPIgHAOIAuAAIAngpIBIA8QgEAEgFACQgGACgJAAQgSAQgXASQgYARgZANIBIAAIAegnIBLA5QgDAEgHAEIgNAFIAAEnQAAAZgHARQgIAQgSAJQgTAIghACIAAgcgACVBjIAjAAIAAhgIgjAAgAAtA0IgBAYIAAAXIAgAAIAAhgIgfAAgACVgNIAjAAIAAhYIgjAAgAAtgNIAfAAIAAhYIgfAAgAAlihQgLAPgNANIAsAPIAmAAQAHgQAGgUIAKgnIg7AAQgKARgMAPgAjsD/IAAi4QgVAbgYAZIgHgFQAUgsAQg1QAQg1ALg6QAKg5AHg3IhIAAIgFgRICbAAIAogzIAMAKIAdAXIAfAZQgCAFgEACQgFADgGAAIhXAAQgHAogKAlQgLAlgOAjIAJAEIASAAIAigmIBFA2QgCAEgGADQgFADgJACIAADeQgBACgKAFQgKAEgOAEQgOAEgNAAIgNAAIAAgpIggAAIAAA3QgBACgHAFQgHAGgNAEQgNAEgTAAgAijCjIAgAAIAAjEIggAAg");
	this.shape_24.setTransform(2351.75,735.325);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AhYEeIAAk0QgPASgRAPQgQAPgSAOIgGgGQAWgiARgoQASgpAOgrQAOgsAJgoQAKgoAEgiIBvAdIgFgPQgDgIgEgHIAFgCQA2ALAZAUQAZAUABAVQACAVgOAPQgNAOgVABQgVABgWgUQABgSgCgRQgBgRgFgQQgCADgFADQgEAEgKABIgRAoIgVAqICkAAIAqg3IAMAKIAeAZIAeAcQgBAEgEADQgFACgGAAIh7AAIAABqIAVAAIAmg3IAMALIAbAYIAdAbQgBAFgFACQgEADgGAAIhvAAIAABrIAVAAIAmg4IAMAMIAbAYIAdAbQgBAFgFACQgEACgGAAIhvAAIAABwIAeAAIArg7IAMALIAfAaIAgAdQgCAFgEACQgFADgGAAIkXAAIAAAbQAAADgIAFQgHAGgPAFQgPAEgVAAgAgHDbIBCAAIAAhwIhCAAgAgHBbIBCAAIAAhrIhCAAgAgHiKIAABpIBCAAIAAhqIhBAAgAjqEPQgMgHgGgRQAHgeABgbQABgbgCgTQgEgSgHgFQgHgFgHgDQgIgCgKAAIAAgLIAcAAQAHABAEgDQAEgCAEgJIAJgOIAKgXIAVgtIAkhRIA6iFIAJABIgTBGIgWBQIgSBGIgLAuIgHAiQgCAQAAANQABAQAHANQAIAOAHARQAGAQAAAaQgBAYgQAPQgRAOgcAAIgBABQgMAAgLgGgAjiiIQgDgfgOggQgOgfgTgYIAGgCQA5AJAdAUQAeAUAGAXQAGAXgKARQgKASgVAEIgHABQgRAAgTgPg");
	this.shape_25.setTransform(2292.25,735.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("ABmD3QgEgPgIgJQgIgJgRgIQgQgIgYgFIABgHIAfACIAgACIAXABQAHAAAFgCQAGgCADgEQAQgPAGhTQAHhTACiYIhcAAQgYAngbAgQgbAfgfAZIgDgDIAADyQgBADgLAGQgLAFgQAEQgPAEgOABIgOAAIAAgwIhKAAIAAApQAAAFgJAHQgIAGgPAFQgPAFgSAAIgMAAIAAnJIBLAfIADglIADgpIABglIB0AcQgCAHgHAEQgGADgKAAIghAlIgiAmIAoAAIAkgpIBKA6QgCAEgHADQgGADgIADIAABkQAOggAOgpQAMgpALgtQALgtAGgsIBwAgQgCAGgGADQgGAEgKAAQgIATgIARIgSAjIBLAAIAtguIBJBBQgEAEgGADQgHADgKACQgCBegDBDQgCBDgFAtQgFAtgJAbQgIAbgOANQgQARgXAJQgXAHghAAQAAgVgDgPgAjECuIBKAAIAAidIhKAAgAjEAAIBKAAIAAiTIhKAAgAAkBRQgBghgLghQgLgfgPgaIADgDQA5AOAbAWQAbAWAFAXQAEAYgKARQgLARgVADIgEAAQgTAAgUgQg");
	this.shape_26.setTransform(2233.15,735.475);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AixEdIAAkpIBbAiICnAAIApgsIBTA/QgDAEgHADQgGAEgJADIAADHQgBAEgMAGQgMAHgRAFQgSAGgRAAIgPAAIAAgsIizAAIAAATQAAAFgLAHQgKAGgSAFQgQAFgTAAgAhbDeICzAAIAAhUIizAAgAhbB5ICzAAIAAhSIizAAgAkRglIgFgRIE2AAIAPgpIAMgsIAKgqIjFAAQAwAOAVAUQAVAVABAUQABAVgMAOQgMAOgTABQgUABgVgSQgBgdgIgcQgIgcgLgXIhjAAIgFgQIDwAAIgKgEIgKgGQgDgWgJgTQgJgUgLgOIAEgCQAzgCAYALQAZALAGAQQAFARgKAOQgJAOgSAGIB3AAIAsg6IAPAMIAeAZIAiAcQgBAFgFACQgEACgHAAIiXAAIBdAcQgCAGgGADQgFADgKgBQgWAUgeAYQgfAYgfAUIBsAAIAtg7IAOALIAiAaIAiAdQgBAFgFACQgEADgHAAg");
	this.shape_27.setTransform(2171.9,735.316);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AimEeIAAjlQgcAHggAGQgeAGghADIgCgGQBKgYBCgjQBCgjA1gtQgQgRgNgUQgOgVgMgWQgmAlgrAeQgsAegvAVIgEgEQAjgdAggqQAhgpAZgwQAagvAQguIB1AbQgCAFgGACQgEADgNAAIgRAZIgTAYIBrAAIA4gxIBRBNQgEAGgGACQgFACgNACQgUAcgYAZQgYAZgdAXQAyARA3AKQA2AJA1AFIAAAIQgcAHgRATQgRAVgIAfQgjgJghgKIA2AoQgCAFgHADQgGAEgLADIAACeQgBACgNAEQgMAFgQADQgSAEgPABIgPAAIAAguIioAAIAAAWQgBAFgLAGQgLAHgSAFQgQAFgUAAgAhNDbICoAAIAAiDIioAAgAg1ATQgnAQgrAOIA+AXICdAAIAhgkQgbgLgYgNQgZgNgVgRQgiAVgnAQgAhBiqIgMANQAQASATAQQATAPAWANQAVgUARgWQARgWANgXIh5AAIgLAMg");
	this.shape_28.setTransform(2111.95,735.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#333333").s().p("ACeEYIAAg0Ik4AAIgXAoIhUguIAJgKIALgKIAAiyIBoALQgBAEgEAEQgFAEgLABIAACjIBwAAIAAjwIhQAAIgYAnIhRgtIAJgKIALgJIAAinIBmAKQgBAFgEADQgGAEgKACIAACXIBUAAIAAjpIBtALQgBAGgEAFQgFAEgMACIAADNIBZAAIAAivIBnAJQAAAGgEADQgFAEgKACIAAC5QgBADgKAEQgKAEgQADQgQADgQABIgPAAIAAgjIhZAAIAADwIB1AAIAAi6IBoAJQgBAFgEAEQgEAEgLACIAADUQAAADgKAEQgLAEgPAEQgQADgQABg");
	this.shape_29.setTransform(3248.55,639.175);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("Ag+EXIAAkgIBVAgICKAAIAmgoIBPA6QgDAEgGAEQgGAEgKACIAADMQgBACgMAFIgcAIQgQAEgOAAIgPAAIAAgvIiTAAIAAAWQgBAEgKAGQgJAGgQAFQgQAFgSAAgAAUDWICTAAIAAhQIiTAAgAAUB1ICTAAIAAhNIiTAAgAkVCpIAAmVIBOAgIAgAAIAjgoIBJA5QgDADgGAEQgGADgJACIAAEdQgBADgLAEQgKAFgPAEQgOAEgOAAIgNAAIAAgzIgoAAIAABAQAAAEgJAGQgJAGgOAFQgPAFgRAAgAjJA+IAoAAIAAj5IgoAAgAgrgEIAAkHIBSAgIBpAAIAngrIBPA8QgDAFgHAEQgGAEgLACIAACsQgBACgMAFQgLAEgQADQgQADgOABIgOAAIAAgjIh0AAIAAATQAAAEgKAGQgKAFgPAFQgPAEgQABgAAjhBIB0AAIAAhEIh0AAgAAjiWIB0AAIAAhFIh0AAg");
	this.shape_30.setTransform(3189.775,639.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#333333").s().p("AkgEaQAUgwAIg3QAJg3ACg5QACg4AAg1IAAjBIBCAVQAegSAbgTQAbgSARgQIBSBIQgFAFgKABQgLAAgOgFQgZAGgiAFQghAGgkAEIAABFIA4AAIAkgoIBKA5QgDADgGAEQgFAEgKACIAACjQgBADgLAEQgLAEgPADQgPAEgNAAIgOAAIAAgnIhBAAQgDAqgMArQgLAqgXAnQgYAogpAggAimgnIgBAkIgBAkIBAAAIAAiKIg+AAgAhbEYQArgzAVg5QAVg5AGg8QAGg7AAg7IAAiyIBQAZQAhgSAegTQAegTATgPIBXBOQgGAFgLAAQgLAAgQgFQgdAGgoAFQgoAGgqAEIAABxIBaAAIAng2IANAKIAcAYIAdAbQgBAFgEACQgFADgGAAIgvAAIAAE7QAAADgJAFQgIAFgQAFQgPAEgXABIgQAAIAAlSIgxAAQAAArgFAtQgFAvgSAvQgRAugkAqQgiAqg9Ahg");
	this.shape_31.setTransform(3128.675,639.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("ABxEeIAAlMIhAAAIAAABQABAsgGAsQgGAugUArQgUAsgpAmQgqAmhGAdIgEgFQAoghAZgnQAZgmANgoQANgpAEgsQAEgpAAgsIAAjGIBVAdQAkgSAggTQAggTAWgQIBaBSQgHAFgLABQgMAAgPgGQghAGgsAGQgsAGgvADIAAB3IBwAAIAqg6IAOALIAeAaIAfAcQgBAGgEABQgFADgGAAIg8AAIAAE4QgBADgIAFQgJAEgQAEQgQAEgWAAgAkVCsIAAmaIBSAiIAgAAIAlgqIBLA7QgDAEgGADQgGADgJACIAAEZQgBAEgLAEQgLAGgQADQgPAFgPAAIgNAAIAAhAIgnAAIAABPQgBAFgJAHQgKAGgPAFQgQAFgSABgAjEAwIAnAAIAAjsIgnAAg");
	this.shape_32.setTransform(3070.025,639.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#333333").s().p("AiGEhIAAh6IgwAXIg3AYQgDAGgEAEQgGAFgFABIgihhIASgDIAYgDIAAlVIgjAAIgFgRIC6AAIAogxIAMAKIAeAWIAdAZQgBAEgEADQgFACgGAAIg0AAIAACmQAaglAUgrQAUgrAPgqQAPgpAGgiIByAoQgCAGgGAEQgGADgNABQAPAjAZAWQAZAXAfAOQAgANAfAHIAAAJQgbASgOAVQgQAWgCAbQgpgggagzQgagzgPg/QgTAjgbAkQgbAjgjAgQghAhgoAaIAAB5IAfgFIAegGIABAHIgcAQIgiATIAACLQgBACgGAFQgIAFgOAEQgNAFgUAAgAiuB1IAogHIAAhdIgoAAgAiuAAIAoAAIAAhiIgoAAgAiuhzIAoAAIAAhjIgoAAgAB3EXQgNgbgVgbQgXgbgagYQgagYgZgRIAFgFQAiADAcAGQAcAHAVAJIAVgoIATgsIAOgoIizAAIgFgRIC3AAIAtgrIBKBHQgDAEgFACIgQADQgRARgWAUQgWAUgZATQgYASgYAQQAnAVAQAZQAQAZgEAVQgDAVgRAJQgIAEgJAAQgMAAgOgGgABQgNQgBgZgHgZQgGgYgLgTIAGgDQAuALAVASQAWARACATQACASgKANQgKAMgSABIgDAAQgQAAgRgNg");
	this.shape_33.setTransform(3008.85,638.825);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#333333").s().p("AhuETQgSgFgIgNQgHgOABgZIAAhfIBiAHQgBAGgEAEQgFADgJACIAAA5QAAAFAEACQAEACAOAAIBEAAIAeAAIAWAAQAHgBAEgBQAEgCADgFQAGgHAIgOQAIgQAKgXIAGAAIACA+QAQAGAGAHQAGAIAAAKQAAARgMAKQgNAKggAEQghAEg6AAIhIAAIgGAAQgfAAgSgFgAjyELQgNgBgJgIQgKgHgEgNQgEgTAJgOQAJgNARgGQAMgFAMgKQALgJAHgNQAIgNAAgQIAHAAIADAGIAAjWIBYAhIDBAAIAiglImPAAIgFgRICzAAIgHgDIgIgFQgBgUgHgSQgIgTgJgNIAEgDIAGAAIC0AAIgHApIgIAoIhjAAQAOgGAHgNQAEgHAAgHQAAgGgDgHQgFgOgXgKQgVgKgngBQAnABAVAKQAXAKAFAOQADAHAAAGQAAAHgEAHQgHANgOAGIBjAAIAIgoIAHgpIi0AAIgGAAIhkAAIgFgQIDSAAQgHgUgNgSQgNgRgOgLIADgEQAsgGAZAFQAYAGALANQAKANgBAOQgCAOgKALIBiAAIAqgzIANAJIAeAXIAgAaQgBAFgFACQgEACgHAAIiOAAIBLAUQgCAGgFADQgGAEgKgBIgkAYQgVANgWAMIBpAAIApgyIANAJIAeAXIAhAaQgCAFgEACQgFACgHAAIh+AAIBJA3QgCADgGAEQgGAEgKACIAAB5QgBADgLAFQgLAFgQAEQgQAFgPAAIgPAAIAAgYIjLAAIAAAGQgBAEgLAGQgKAGgQAFQgRAEgRABIgMAAQANAjgBAcQgCAcgLASQgMATgRAIQgJAEgKAAIgGAAgAhnBPIDLAAIAAgzIjLAAgAhnALIDLAAIAAgxIjLAAgADIDxQgCgfgOggQgOgfgVgWIAFgEQA3AKAbAUQAcAUAGAWQAHAWgJARQgJARgTAEIgHABQgPAAgSgNgAAAC9QgDgXgKgVQgLgWgNgPIAEgDQAvADAXANQAYANAFARQAEAQgIAOQgJAOgRADIgIABQgNAAgPgKg");
	this.shape_34.setTransform(2948.7527,638.2206);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AjZEVQgMgHgFgRQAGggABgbQACgcgDgTQgEgTgHgFQgGgFgJgCQgIgDgKAAIAAgLIAdAAQAHAAAEgBQADgCAGgKIAIgOIAMgWIAVgsIAmhPIA9iCIAJACIgQAzID8AAIAqg6IAOALIAeAaIAfAcQgBAFgFACQgEADgIAAIiNAAIAACcIAjAAIAng1IAMALIAcAXIAeAaQgBAFgFADQgEACgGAAIiAAAIAADEIAvAAIAsg8IAOALIAfAbIAhAdQgCAFgEACQgFADgHAAImBAAIgFgRICWAAIAAjEIh0AAIgFgRIB5AAIAAicIh1AAIgEgPIgTA9IgTA+IgPAyIgJAiIgGAiQgEAQAAAMQABARAHAOIAOAfQAHARAAAbQgCAXgPAPQgRAPgaABQgNAAgLgHgAjsgmQgGgagPgZQgOgZgRgSIAEgDQA2ABAcAPQAbAOAIATQAHATgJAQQgIAQgSAFIgLACQgOAAgQgKgAAwikQgKgggVgeQgTgfgXgWIAEgEQA8AEAhARQAgARAKAWQAKAWgHATQgHASgTAHQgGACgHAAQgOAAgQgJgAi3itQgIgbgSgaQgRgZgRgTIAEgEQA3ABAeAOQAdAOAJATQAIAUgHAQQgIARgSAGQgGACgHAAQgNAAgQgIg");
	this.shape_35.setTransform(2889,639.425);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#333333").s().p("Ag7BiQAmgTAQgYQARgZADgVQgOgFgQgHQgRgIgNgOQgNgOgBgWQABgWAPgRQAQgQAagBQAQAAAOAIQANAIAJAPQAIAQAAAXQAAAegLAfQgLAggYAcQgXAbgnARg");
	this.shape_36.setTransform(2806.95,664.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#333333").s().p("AjJEdIAAi/QgRAYgUAWQgVAWgXAUIgGgHQATghAQgqQAPgoALgsQALgsAHgrIhGAAIgFgRIBTAAIAAhgIgpAEIgoADIgCgGQAdgNAggSQAegRAcgSQAbgTARgQIBaBOQgGAEgLABQgKAAgQgEIgWAEIgZAGIAABjIAdgqIAKAJIAZAXIAZAZQgBAFgEACQgFACgGABIhJAAIAAAdQAsASAVAVQAUAUACAVQACAUgKAOQgKANgQABQgRACgSgQQAAgVgFgXQgFgXgIgUIAAEVQAAADgIAGQgIAEgOAFQgPAFgUAAgAhKD9IgFgRICMAAIAAhvIhdAAIgFgRIBiAAIAAhqIhnAAIgEgPIDgAAIAkgzIAMAKIAaAWIAbAaQgCAFgEABQgEADgHgBIh4AAIAABqIASAAIAmg0IAMAKIAcAXIAdAaQgBAFgEACQgFADgHAAIhsAAIAABvIAuAAIAkg0IAMAKIAaAXIAbAaQgBAFgEADQgFACgHAAgAgagtIAAjeIBRAgIBjAAIAkgnIBLA4IgIAHQgGAEgKACIAAB7QgBADgKADQgLAFgQADQgPAEgOABIgNAAIAAgYIhtAAIAAASQAAADgKAGQgKAGgQAEQgPAFgPAAgAA0hnIBtAAIAAh0IhtAAg");
	this.shape_37.setTransform(2768.625,639.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#333333").s().p("AiyEdIAAkpIBcAiICnAAIAqgsIBSA/QgEAEgGADQgGAEgKADIAADHQgBAEgLAGQgMAHgRAFQgSAGgQAAIgQAAIAAgsIizAAIAAATQABAFgLAHQgMAGgQAFQgRAFgTAAgAhbDeICzAAIAAhUIizAAgAhbB5ICzAAIAAhSIizAAgAkRglIgFgRIE2AAIAOgpIANgsIAKgqIjFAAQAwAOAVAUQAVAVABAUQACAVgNAOQgMAOgUABQgTABgVgSQgBgdgIgcQgHgcgMgXIhiAAIgGgQIDxAAIgLgEIgLgGQgCgWgJgTQgJgUgLgOIAEgCQA0gCAXALQAZALAGAQQAFARgKAOQgJAOgSAGIB3AAIAsg6IAOAMIAgAZIAiAcQgCAFgFACQgEACgHAAIiXAAIBcAcQgBAGgGADQgFADgKgBQgVAUgfAYQgfAYgfAUIBsAAIAtg7IAPALIAgAaIAjAdQgBAFgFACQgFADgGAAg");
	this.shape_38.setTransform(2708.8,639.116);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#333333").s().p("AjUEdIAAkDIgjAZQgRANgTAJIgFgEQAbgiAYgqQAYgqATgpQASgpALgiIBjA0IBMAAIAAhKIhiAAIgFgQIBnAAIAAhQIBrAKQgBAGgFAEQgFAFgMACIAAA1IAlAAIAlgpIBNA6QgCADgGAEQgGADgJADIAAA4IAYgqIAJAJIASAVIASAWQgBAFgEADQgEACgGAAIg2AAIAABfQgBACgMADQgLAEgRAEQgQADgOABIgPAAIAAgUIgqAAIAABHIA4AAIAog0IAMAKIAdAWIAeAaQgBAFgFADQgEACgGAAIiXAAIAABLIBIAAIArg3IANAKIAfAYIAgAcQgCAFgEACQgFADgHAAIitAAIAABSQAAAEgLAHQgKAGgPAGQgQAFgQABIgQAAIAAhvIiAAAIgFgRICFAAIAAhLIhyAAIgEgQIB2AAIAAhHIhlAAIgFgRIBqAAIAAhLIhmAAIgUAZIgWAZIAYAJQgBAFgEADQgFADgIABIAAEdQgBAEgJAGQgKAGgQAFQgPAGgSgBgABegWIAqAAIAAhLIgqAAgABehxIAqAAIAAhKIgqAAgAkihvQAVgaAVgfQAUggARgeQASgfAKgXIBjA0QgBAEgFADQgGADgLgBQgVATgdAWQgdAVggATQgiAVgiAPg");
	this.shape_39.setTransform(2648.975,639.25);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#333333").s().p("AhaEYQApg7AThLQAShMgEhdIBfAPIAAhEIhSAAIgFgOIgRAMIgSALIgHgEQAQgaAOgiQAOgjAKgmQAMgoAGgoIBwAkQgCAHgGACQgGAEgLgBQgIARgKAQIgTAeIBdAAIAqg7IAOALIAeAaIAgAdQgCAFgEACQgFACgGAAIjPAAQgOATgRAQQgQAQgQANIC1AAIAmgmIBBA/QgEAEgFABIgOACIgaAUIgdAVIgaATIgGgEIAGgiIAFglIgbAAIAACAIAMAAIAmg0IANAJIAbAXIAdAbQgBAFgFACQgEADgHAAIhmAAIAAB7IAPABIAPAAIBrAAIAAAHQgQAFgHATQgIATAAAaIhPAAQgoAAgegJQgegLgWgYQgVgZgMgsQgRArgbAfQgbAggmAXgABIADIgLADQgEAkgGAeQgGAegJAaQAJAPALAMQAKALANAHIAAitIgHADgAkiETQAfg/ANhFQANhFAChHQABhHAAhJIg3AAIgFgRICqAAIAmg3IAMALIAaAZIAdAaQgCAFgEADQgEACgHAAIh0AAIAAApIgCApIAbAAIAngnIBDA5QgDAEgHADQgGADgKACQgCBFgDAwQgEAxgGAfQgFAggJASQgJATgMAKQgPAOgTAFQgTAHgZAAQAAgSgBgNQgCgNgGgIQgFgHgIgFQgIgGgMgEQgNAWgSAWQgRAUgWAUgAinBPQgMA7gdA0IAXABIASABQAGAAAEgBQAFgCAEgDQAIgIAGgZQAGgbAEgwQAEgwAChIIghAAQgDA+gNA7gAjBi2QACgbgKgbQgJgagRgTIAEgDQA2AGAZASQAaARAEAVQAEAUgLAQQgLAQgTADIgGAAQgRAAgTgPg");
	this.shape_40.setTransform(2589.175,639.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#333333").s().p("ABlD3QgCgPgJgJQgIgJgRgIQgQgIgYgFIABgHIAgACIAfACIAWABQAIAAAFgCQAGgCADgEQAQgPAGhTQAHhTACiYIhcAAQgYAngbAgQgaAfggAZIgEgDIAADyQgBADgKAGQgLAFgQAEQgOAEgPABIgNAAIAAgwIhLAAIAAApQAAAFgJAHQgJAGgOAFQgPAFgSAAIgMAAIAAnJIBLAfIADglIADgpIABglIB0AcQgCAHgGAEQgHADgKAAIghAlIgiAmIAnAAIAlgpIBKA6QgCAEgHADQgFADgKADIAABkQAPggAOgpQAMgpALgtQALgtAGgsIBwAgQgCAGgFADQgHAEgKAAQgIATgIARIgSAjIBLAAIAtguIBJBBQgEAEgHADQgGADgKACQgCBegDBDQgCBDgFAtQgFAtgIAbQgJAbgOANQgQARgXAJQgXAHghAAQAAgVgEgPgAjECuIBLAAIAAidIhLAAgAjEAAIBLAAIAAiTIhLAAgAAkBRQgBghgLghQgLgfgPgaIADgDQA5AOAbAWQAbAWAFAXQAFAYgLARQgMARgUADIgEAAQgTAAgUgQg");
	this.shape_41.setTransform(2530.05,639.275);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#333333").s().p("Aj9EXQBCgVAngXQAngYAUgaQAUgbAHgdIiMAAIgEgRICTAAQADgQABgQIABgjIhDAAIgDgKQgfAbgoAWQgnAXgxASIgEgGQAygiAlgoQAkgoAZgrIiJAAIgFgRICYAAIAOgdIAMgeIh7AAIgEgRICGAAIAIgbIAIgaIikAAIgFgRICtAAIAIgrIAGgqIB1AXQgBAHgGAEQgFAEgLAAIgGAXIgFAYIBwAAIArg1IANAKIAfAXIAiAbQgCAFgEACQgFADgGAAIjeAAIgJAbIgJAaICBAAIAngwIAMAKIAcAVIAfAYQgBAFgFADQgEACgHAAIjmAAIgPAeIgRAdIDOAAIArg3IAOALIAgAYIAiAbQgBAFgFACQgEADgHAAIirAAQAWAXAfAPQAgANAjAHQAkAHAiACIgBAJQgZAQgPAUQgPAUgCAYQgygWgmgpQglgpgYg0IiIAAQgNASgPARQgPAPgSAQICCAAIAlgsIAMAJIAaATIAdAXQgBAFgFACQgEADgHAAIg/AAQAAASgCARQgCAQgEAQIA1AAIAogzIAMAKIAdAWIAfAaQgBAFgFADQgEACgHAAIiZAAIgEALIgFALQBVAJAvAQQAwARATATQAUASgCARQgBARgPALQgPAKgUAAQgVAAgSgPQgRgWgigcQghgcgygaQgPAagfAWQgfAXg0ASQgzAShOAOg");
	this.shape_42.setTransform(2468.875,639.025);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#333333").s().p("AjMEAQgCgMgHgIQgHgIgNgGQgNgHgSgEIAAgHIAZADIAaABIASAAIALgBQAEgBAFgDQAKgJAHgoQAHgpAEhIIgtAAIgXAdIhBgkIAIgHIAKgGQADgWACgcIAEg4IACguIBRAlIAUAAIAAhwIh2AAIgFgRIB0AAIAignIBKA4QgDAEgHADQgGAFgKABIAACAQgBACgKAEQgLAEgOADQgOADgNAAIgMAAIAAgcIgkAAIgCAhIgDAkIgEAgIAqAAIAngkIBCA3QgDAEgGACQgGADgJACQgEBAgFArQgHAqgKAaQgKAYgPALQgPAMgTAFQgTAFgaAAQAAgQgCgOgAA/EdIAAiFIiFAAIgFgQICKAAIAAhHIgkAAIAAANQAAAFgQAHQgPAGgdAAIgNAAIAAkZIBQAdIBdAAQAJgZAKgjQALgjAIgiIBiAmQgCAGgGACQgGADgKAAQgVAWgYAVQgXAWgXAPIAXAAIAlgoIBDAzQgDAEgGADQgFADgKACIAADHQAAADgRAGQgRAHgeABIgNAAIAAgSIgkAAIAABHIAjAAIAng2IAMAKIAcAYIAdAaQgBAGgFACQgEACgHAAIh+AAIAAByQAAADgHAEQgHAFgOAEQgNADgUAAgACKAwIAkAAIAAhYIgkAAgAAbAwIAkAAIAAhYIgkAAgACKg5IAkAAIAAhSIgkAAgAAbg5IAkAAIAAhSIgkAAgAAPiwQgEgbgLgaQgMgagPgUIAFgDQAyAHAaARQAZARAGATQAFATgJAPQgJAPgSAEIgHABQgOAAgSgMg");
	this.shape_43.setTransform(2408.425,639.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#333333").s().p("AAyEcIAAmAIgkAAIAAEYQAAADgHAFQgHAFgOAEQgOAFgTABIgOAAIAAleIBTAfIAcAAIAAheIiBAAIgFgQID0AAIAqg5IANALIAfAZQARAOAOAOQgBAFgEADQgGACgGgBIiBAAIAABeIAfAAIAhgmIBHA2QgCADgFAEQgFACgIACIAADLQAAAagGASQgFARgSAKQgRALgjACIgBgfQgBgOgDgIQgCgIgGgGQgEgFgLgDIAAgIIAEAAIAJAAIAJABQAFAAACgCQACgDgBgEIAAjPIgkAAIAAFqQAAADgIAFQgIAFgOAEQgPAFgVAAgAkHEXQAjgnASguQATgwAIg0QAHg1AAg5IAAkKIBjAJQgCAHgFAEQgEAEgMADIAADvQAAA/gOA5QgOA4gjAuQgiAug8AggAkUCVIAAlkIBcAIQgBAGgEAEQgEAEgLACIAAE4QgBADgIAFQgJAEgOAFQgNADgOAAg");
	this.shape_44.setTransform(2349.9,639.35);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#333333").s().p("Ai2D8QgDgOgHgKQgHgIgLgGQgLgHgXgEIAAgHIALAAIAWABIAaABIAQABQAGAAACgCQADgDAAgEIAAgzIgkANIglAMQgCAHgFADQgFAEgFACIgihXIA0gEIBIgIIAAg2IAnADIAMgUIALgTIg0AAQgfAYgjAWQgiAXgoARIgFgFQAYgTAXgVQAXgUAVgVIg0AAIgGgRIBKAAIAZgfIAXgfIiRAAIgFgRIBZAAIAAhPIg+AAIgFgRIBDAAIAAhTIBoAIQgBAHgFAEQgFAEgMADIAAA1IAbglIAJAHIAVASIANgfIAMgeIBaAtQgDAEgFADQgFACgMgBQgQAcgTAfQgVAegZAfIASAAIAdgpIAHAFIAQAOIATASQAKgqAHgsQAHgrAEgsIBxAbQgCAHgFADQgGAEgKAAIgPAxIgQAtIAyAAIAqg4IANALIAeAYIAgAcQgBAFgFADQgEABgHAAIgaAAQgGBFgTA+QgTA8gjA0QAaAcAfAXQAfAXAlAQIgCAGQgeAHgRASQgTARgHAeQgfgWgWgdQgXgcgRgjQgmAmg0AeQgzAdhHAUIgEgFQBFglAsgtQAuguAcg1QgJgggIgjQgHghgFgmQgQAXgSAUQgSATgUASIgIgEIAJgSIAHgUIgHACIgKABIggARIgiARIAVACQAAAGgFAEQgFAEgKAAIAAAVIA3gHIA4gIIABAIIgxAVIg/AZIAABTQACAcgIASQgGAUgWALQgWALgrADQgCgSgDgOgABkheQgJASgKAQQAHAdAKAZQALAaAMAXQAPgoAIgrQAJgsACgvIgmAAQgIATgJASgAAGgKQAHgSAGgUIALgoIhhAAIgdAfIghAfIAjAAIAlgngAh2h1IAVgiIATghIgoAAg");
	this.shape_45.setTransform(2288.8,639.3);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#333333").s().p("Ag+EXIAAkgIBVAgICKAAIAmgoIBPA6QgDAEgGAEQgGAEgKACIAADMQgBACgMAFIgcAIQgQAEgOAAIgPAAIAAgvIiTAAIAAAWQgBAEgKAGQgJAGgQAFQgQAFgSAAgAAUDWICTAAIAAhQIiTAAgAAUB1ICTAAIAAhNIiTAAgAkVCpIAAmVIBOAgIAgAAIAjgoIBJA5QgDADgGAEQgGADgJACIAAEdQgBADgLAEQgKAFgPAEQgOAEgOAAIgNAAIAAgzIgoAAIAABAQAAAEgJAGQgJAGgOAFQgPAFgRAAgAjJA+IAoAAIAAj5IgoAAgAgrgEIAAkHIBSAgIBpAAIAngrIBPA8QgDAFgHAEQgGAEgLACIAACsQgBACgMAFQgLAEgQADQgQADgOABIgOAAIAAgjIh0AAIAAATQAAAEgKAGQgKAFgPAFQgPAEgQABgAAjhBIB0AAIAAhEIh0AAgAAjiWIB0AAIAAhFIh0AAg");
	this.shape_46.setTransform(2229.775,639.725);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#333333").s().p("AiFEVQA1gUAhgYQAhgXAQgaQASgaAHgbIiCAAIgEgRICKAAIAEgjIACgkIgUAAIAAARQAAAEgLAGQgJAGgQAEQgQAFgRABIgLAAIAAgsQgKAHgMgCQgNgBgNgNQABgUgEgWQgFgVgHgTIAAE1QAAADgKAGQgLAGgOAEQgQAEgQABIgRAAIAAjfQgQAWgTAVQgTAUgWASIgHgFQAVgjAPgpQAPgqAKgsQALgtAGguIhGAAIgEgQIBPAAIAAiYIBqAKQAAAGgFAFQgEAEgNACIAAB2IAdgsIAKAJIAYAZIAAgEIBTAhIB/AAIAkgmIBHA2QgCACgFADQgFAEgHABIAACOQABACgGACIgNAHIATAQIAbAXIAaAXQgCAFgEADQgFACgGAAIiTAAQAOAZAqAPQAqAQBGAGIAAAHQgeAIgQASQgQATgBAnQglgNgXgYQgYgYgNgeQgNgegFgfQgLAlgaAdQgZAegzAVQgxAXhSANgAB9BQQgCARgEARIA0AAIAlg0IgUAGQgLADgKgBIgOAAIAAgbIgaAAIgCAlgAARAaICIAAIAAg4IiIAAgAh+hCIABAAQAWAIAQAKQAPAKAJAKIAAhYIg/AAgAARgvICIAAIAAg5IiIAAgAgQiMIAAg0IhCAAIgFgRIBHAAIAAhJIBiAIQgBAFgEAEQgFAEgKACIAAAyIAvAAIAAhJIBiAIQgBAFgEAEQgEAEgLACIAAAsIAggrIALAKIAaAVIAbAZQgCAFgEADQgEACgHAAIhPAAIAAAZQAAADgLAGQgKAFgPADQgPAEgQAAIgLAAIAAguIgvAAIAAAiQgBACgKAEQgJAEgPAEQgQADgPABg");
	this.shape_47.setTransform(2168.85,639.35);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#333333").s().p("AgmAnQgQgQAAgWQAAgWAQgQQAPgQAXAAQAXAAAQAQQAPAQABAWQgBAWgPAQQgQAPgXAAQgXAAgPgPg");
	this.shape_48.setTransform(2128.475,657.575);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("AiFDkIAAgTIBXgLIAAg4IABg4IAAkFIhIAHIAAgWICiglIAJAGIgCBiIAADRIAAA4IABA4IBRALIAAATg");
	this.shape_49.setTransform(2100.2,639.275);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("AgqBJQgTgLgMgTQgLgUgBgXQABgYALgTQAMgTATgMQAUgLAXABQAXgBATALQAUAMALATQALATAAAYQAAAXgLAUQgLATgUALQgTAMgXABQgXgBgUgMgAgrgsQgSASAAAaQAAAaASASQARASAbAAQAZAAATgSQARgSABgaQgBgagRgSQgTgRgZgBQgbABgRARg");
	this.shape_50.setTransform(1675.45,423.25);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("Ah8EYQAxg4AZhEQAYhDAGhJQAHhIgChJIhZAAIgFgRIEWAAIArg9IAOAMIAfAbIAgAdQgBAFgFADQgEACgHAAIjBAAIgDAxQgBAZgDAYIBQAAIArgqIBIA9QgDAFgGACQgGADgKACQgEBTgGA0QgGA0gLAcQgLAcgSANQgPANgVAGQgUAHgbAAQAAgUgCgOQgCgPgGgIQgHgJgLgHQgLgHgSgFIAAgGIAVACIAXABIARAAIAKgBQAFgCAEgDQAMgKAIgxQAHgyAFhdIhYAAQgIA8gVA4QgUA4gmAvQgoAvg/AhgAjWEdIAAkvQgfAdglAYIgGgEQAYgmAYgzQAXgzASg6QATg6ALg7IB5AkQgCAGgGADQgHAEgKAAQgOAjgQAfQgQAfgSAcIAdAKQgBAEgFADQgEADgJACIAAFcQgBAEgKAGQgKAFgQAFQgQAFgSAAgAA1iqQgCgdgNgdQgMgcgSgVIAEgDQA4AHAcARQAcATAGAVQAGAVgKARQgKARgUAEIgIABQgQAAgTgOg");
	this.shape_51.setTransform(1634.325,403.925);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("AiFEWQA1gWAhgXQAhgXAQgaQASgaAGgbIiAAAIgFgRICKAAIAEgiIABgkIgTAAIAAAQQAAAEgKAGQgKAGgPAFQgQAEgSAAIgLAAIAAgqQgKAFgMgBQgMgBgNgMQAAgVgFgVQgEgWgHgUIAAE2QAAAEgKAFQgKAGgQAEQgPAFgQgBIgRAAIAAjeQgQAXgTATQgTAVgWATIgHgHQAVgiAPgpQAPgqAKgsQAKgtAHguIhGAAIgEgQIBPAAIAAiZIBrALQgBAGgFAFQgFAEgMACIAAB1IAcgsIALALIAYAXIAAgDIBTAgIB/AAIAkglIBHA1QgCADgEAEQgGACgHABIAACOQAAADgEADIgOAGIATAPIAbAYIAaAXQgCAFgEACQgFADgGAAIiTAAQAPAZApAPQAqAQBHAFIAAAIQgfAHgQATQgQATgBAmQgkgMgYgYQgYgYgNgfQgNgdgFgeQgLAjgZAeQgaAdgzAXQgwAVhSAPgAB9BQQgDASgDAQIA0AAIAlg0IgUAGQgKACgLABIgPAAIAAgbIgZAAIgCAkgAARAbICHAAIAAg5IiHAAgAh+hDIABAAQAWAJAPAKQAQAKAJAKIAAhYIg/AAgAARgvICHAAIAAg5IiHAAgAgQiNIAAgzIhCAAIgFgRIBHAAIAAhJIBhAHQAAAGgEAEQgEAEgMACIAAAyIAwAAIAAhJIBiAHQgBAGgEAEQgEAEgLACIAAAsIAggrIAMAJIAZAXIAbAYQgBAFgFACQgEADgGAAIhQAAIAAAZQgBAEgJAEQgLAFgPAEQgQAEgPAAIgLAAIAAguIgwAAIAAAhQABADgKAEQgLAEgPAEQgPADgOAAg");
	this.shape_52.setTransform(1574.7,404.05);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AjCEcIAAkIQgWAPgWAOQgWAOgYAMIgEgGQAegiAdgpQAdgqAYgqQAXgpAOghIBlA7QgCAEgFACQgGADgLgBIgZAaIgdAbIAcALQgCAEgFADQgDADgJACIAAEcQgBADgKAFQgLAFgQAEQgQAEgRAAgABDDyQgEgPgKgKQgHgGgJgFQgJgFgNgFQgNgEgVgEIAAgHIAOABIAhACIAlACIAZABQAHAAADgDQADgDAAgGIAAjxIihAAIgEgRIDpAAIAqg5IAOALIAeAZIAgAcQgBAFgFACQgEADgHAAIhQAAIAAD0QAAAcgIAVQgJAWgaANQgZANgzADQAAgUgGgQgAkQhuQAZgZAZgfQAYgfAUgfQAUgfAMgYIBeA7QgDAEgFADQgFACgLgCQgWAUgfAUQgfAVgjATQgjASglAPgAgXjNIgFgRIC5AAIAqg2IAMALIAeAYIAfAaQgCAFgFADQgEACgGAAg");
	this.shape_53.setTransform(1514.1,404.075);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#333333").s().p("AkkDFIApgXIAqgXIAAjHIhIAAIgEgRIBCAAIAngzIBSBBQgEAEgHAEQgIADgNADIAACyQALAKAMAJQANAHAOAHIgDgDQAWglALgpQALgpADgwIhLAAIgFgQIBQAAIABgSIAAgUIAAhOIg8AAIgFgRIBBAAIAAiLIBkAKQgCAHgEAEQgEAEgMABIAABxIA1AAIAAiLIBkAKQgBAHgFAEQgEAEgMACIAABwIACAAIAkg4IAMALIAaAZIAcAbQgCAFgEACQgEADgHAAIhXAAIAAB0IANAAIAmg6IANALIAbAaIAcAcQgBAFgFACQgEACgHAAIhmAAIAACeQAAAEgKAFQgKAGgOAFQgPAEgPAAIgOAAIAAi2Ig5AAQgHA2gbArQgbArg4AeQAfAOAtAEQAsAGBBAAIBZgCQArgBAvgDIAAAHQgZAHgOAUQgNAVgDAaIiYAAQg/ABgogMQgpgMgcgZQgbgZgWgmQgGgMgGABQgFABgGAKIgRAdIgXAnIgYAoQABAEgCAFQgCADgEACgAArgyQAAAVgBARIA2AAIAAh0Ig1AAgAjAiIQgHgjgRgiQgRgjgTgbIAEgDQA8AMAgAWQAeAWAIAYQAIAYgJASQgJASgUAGIgJAAQgQAAgTgMg");
	this.shape_54.setTransform(1454.575,403.95);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#333333").s().p("AAQBSQAWgKAOgOQAPgNAHgNQAHgOACgJQgPgEgOgGQgOgHgKgNQgJgNgBgUQAAgVAOgNQAPgNAWAAQAWAAAPAPQAQAPAAAfQAAAcgJAaQgJAbgWAXQgVAXgjAPgAh8BSQAWgKAOgOQAPgNAHgNQAIgOABgJQgOgEgOgGQgOgHgLgNQgKgNAAgUQAAgVAPgNQAOgNAXAAQAWAAAPAPQAPAPABAfQAAAcgKAaQgJAbgWAXQgVAXgiAPg");
	this.shape_55.setTransform(1381.4,384.425);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#333333").s().p("AAtCgQgRgOgHgYQgPARgNALQgOAMgRAGQgRAGgYAAQgnAAgYgWQgYgVgBgnQAAgbAMgUQAMgUAcgPQAcgPAwgOIAcgHIAegIIAAglQAAgfgFgSQgGgSgNgHQgNgHgWAAIgNABIgMABIgFArQgCAegMAOQgNANgSAAQgQAAgLgIQgKgIgEgPQAEgrAmgYQAmgYBGgBQA+AAAcAdQAdAegBBBIAACgQAAARAFAHQAFAHAJgBQAGABAGgFQAGgFAJgNIAKAIQgLAZgSALQgTALgcAAQgeAAgRgOgAAAgNIgNAFQggAMgQAWQgQAWAAAhQAAAbAMAMQALANAWAAQALABAMgHQALgHARgOIAAh8IgTAFgAhtiKIAKgDg");
	this.shape_56.setTransform(1347.674,410.375);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#333333").s().p("AhxDpQgggVgSgmQgTgnAAg2QAAg4AUgnQAUgnAhgVQAigUAqgBQAaAAAUAKQAVALASAVIAAiZIgygFIAAgQICIgZIAJAFIgDBhIAAFzIAnADIAAATIiAAHIgFgmQgTAUgXAKQgWAKgcABQgngBgggTgAglgqQgTAMgMAeQgLAcAAAxQAAAxALAdQAKAeATANQASANAWgBQAMAAAMgDQAMgEALgJIAAjoQgLgIgLgEQgLgDgMAAIgCAAQgUAAgSALg");
	this.shape_57.setTransform(1309.125,402.5);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#333333").s().p("AAgBXQgPgQgBgfQAAgbAKgaQAJgbAWgXQAUgXAjgPIAMAUQgUAKgPAOQgPANgHANQgIAOgBAJQAOADAOAHQAOAHALANQAKAMAAAVQgBAVgOANQgOANgXAAQgWAAgPgPgAhsBXQgPgQAAgfQAAgbAJgaQAJgbAWgXQAVgXAjgPIAMAUQgWAKgOAOQgPANgHANQgHAOgCAJQAOADAOAHQAPAHAKANQAJAMABAVQAAAVgOANQgPANgWAAQgWAAgQgPg");
	this.shape_58.setTransform(1271.8,384.425);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#333333").s().p("AkOETQAeguAPg1QAOg1AEg5QAEg4gBg4IAAjcIBiAhIEBAAIAoguIBQBAIgJAIQgHAEgKACIAAGBQAAAcgHAUQgHATgWAMQgXALgtAEQgBgUgDgPQgDgPgGgJQgGgJgLgHQgLgHgWgEIAAgIIAJABIAVABIAWABIAQABQAHAAADgDQACgEAAgFIAAhsIhnAAIAAC7QAAADgIAFQgIAGgQAEQgPAFgWAAIgPAAIAAjSIhhAAQgGAogPAlQgPAmgcAiQgdAiguAdgAA3A0IBnAAIAAiBIhnAAgAh3guIAAAvQgBAZgDAaIBeAAIAAiBIhaAAgAA3hdIBnAAIAAh7IhnAAgAh3hdIBaAAIAAh7IhaAAg");
	this.shape_59.setTransform(1197.325,403.775);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#333333").s().p("AkUELIgFgRIDrAAIAAi4IidAAIgEgQIChAAIAAiaIhbAAQgdAxglAlQgkAlgqAbIgGgEQAWgkATguQAUgwAPg1QAQg1AIg3IB5AjQgCAGgFAEQgHADgKAAIgSAqQgJAUgKATIBRAAIAAiSIB2ALQgBAHgFAEQgFAFgMACIAAB1IBJAAIAwg7IAOALIAiAZIAlAeQgBAFgEACQgFACgIAAIi8AAIAACaIA3AAIAxg7IAPAKIAiAbIAmAdQgBAFgFACQgEACgIAAIitAAIAAC4IBkAAIAyg/IAQAMIAjAcIAmAeQgCAFgEADQgFACgHAAg");
	this.shape_60.setTransform(1138.35,402.525);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#333333").s().p("AhVD5QgFgQgKgJQgHgHgJgGQgJgFgNgFQgOgEgVgFIAAgHIAPACIAjACIAlACIAYAAQAHABADgDQADgDAAgFIAAhdIjiAAIgEgRIDmAAIAAg+IA8AEIAZgfIAWghIjnAAIgFgRIDwAAIAwgtIAmAlIAJgcIAIgcIlhAAQAEAjgKAYQgKAYgSAKQgMAHgNAAQgMAAgKgIQgLgGgEgNQgGgTAJgOQAJgOAQgIQALgHAKgMQAJgNAFgRQAEgSgDgUIAIAAQAHAOAFANQAFANADAMID6AAQAKgUAKgYQAKgYAIgYQAIgXAGgVIBrApQgCAFgGADQgFACgLgBQgWAUgeAXQgdAXggAUIBSAAIAuguIBPBKQgDAEgGACQgFACgKAAQgUAMgcAOQgcANgbAKIAbAZQgDAEgGACQgFACgKAAQgYAMggAMIg+AXIARACQgBAGgFAEQgEADgKACIAAAmIBvAAIAtg9IAPALIAhAbIAjAdQgCAGgEACQgFADgHAAIjdAAIAABhQABAdgJAWQgJAUgZANQgaAMg0AFQgCgWgFgPgAiYimQgDgegMgcQgNgcgQgXIAFgCQA3AIAcASQAbATAGAUQAFAWgKAQQgKAQgTAFIgHAAQgRAAgTgNgAgiiwQAAgdgHgbQgHgbgKgXIAFgDQA1AOAXAUQAYAUADAVQACAVgMAPQgNAOgVABIgDABQgRAAgUgSg");
	this.shape_61.setTransform(1079.0207,403.95);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#333333").s().p("Ag6BiQAkgTASgZQAPgXAEgXQgOgDgRgIQgRgIgNgOQgMgNAAgXQAAgXAPgQQAQgQAagBQAQAAANAIQAPAIAIAQQAIAPABAXQgBAegKAgQgLAfgYAbQgXAcgnARg");
	this.shape_62.setTransform(997,429.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#333333").s().p("ABZEfQABgVgFgQQgEgPgKgJQgKgLgUgJQgVgIgbgGIABgGIAoACIAoADIAcABQAIAAAGgDQAGgCAFgFQAMgKAIgsQAIgsAEhKQAFhIADhjIkBAAIgaAkQgOARgPAPIAzAUIBOAAIAjgoIBOA6QgEAEgFADQgGAEgKABIAAClQAAADgMAEQgLAFgQADQgQAEgOAAIgOAAIAAgwIhWAAIAAA1QAAAEgLAGQgKAGgQAFQgPAFgSAAIgMAAIAAjpQgWASgYAPQgYAPgaANIgFgEQAbghAbgtQAagsAWg1QAVg0ANg3IB4AsQgCAGgGADQgGADgLgBIgPAcIgOAaIDtAAIAwgwIBKBDQgEAFgGADQgHADgLACQgDB3gGBRQgGBSgMAwQgLAwgUATQgSASgYAJQgXAIgkAAIgFAAgAhhBMIBWAAIAAiEIhWAAg");
	this.shape_63.setTransform(958.425,403.8764);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#333333").s().p("AkgETQAigrATguQATgvAIgwQAJgwABguIhPAAIgEgQIBUAAIAAgSIAAgSIAAhRQgRAagTAWQgUAWgWARIgIgEQANgeALglQALgkAHgpQAHgoADgqIBoAYQgBAHgGADQgFAEgKABIgPAmQgIATgIARIAvAAIAlgxIAMAKIAaAWQAQAMAMAMIAAABIBQAgIBdAAIAlgoIBNA5QgCAEgGAEQgGADgKACIAACIQAAACgMAEQgLAEgQADQgQAEgOAAIgPAAIAAgdIhmAAIAAAPQAAADgLAGQgKAGgQAFQgPAFgRAAIgLAAIAAhHIgCAAIgDAAIhQAAIgCAeIgFAgQAzARAXAXQAYAYADAXQADAXgMAQQgLAQgUACQgUADgVgUQABgbgHgdQgHgcgLgZQgJAlgSAkQgSAlgfAhQgfAhgvAbgAAvAMIBmAAIAAh5IhmAAgAhOg+IAVARIAYAWIAAiCQgCACgEABIgHABIhGAAIAABeIAAANIgBAOIAegpIAJAHgAheEKIgFgQIDFAAQAJgcAGggIALhBIAHg8IBuAYQgCAGgFAEQgGADgKABQgMAWgRAZQgRAagVAZQgUAagXAXIBEAAIAog4IANAKIAdAZIAfAcQgBAFgFACQgEACgHAAgAAKDQQADgigGgkQgGgjgJgeIAGgCQAuAXAVAaQAWAbABAYQACAYgMAPQgLAQgTABIgCAAQgRAAgTgTgAg3jOIgEgRIDYAAIAqg1IANAKIAeAYIAgAaQgCAFgEADQgFACgGAAg");
	this.shape_64.setTransform(899.175,403.475);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#333333").s().p("AhTEgIAAlRIibAAIgGgQIFwAAIAtgqIBLA+QgDADgFAEQgHACgJACQgCBGgEAsQgEArgJAYQgJAYgQALQgOAMgVAFQgTAGgdAAQAAgUgCgPQgCgPgHgKQgHgJgMgHQgMgGgSgFIAAgHIAWACIAXACIARAAIAJgBQAEgCAEgCQAIgIAEgnQAEgmAChKIh2AAIAAE8QAAADgKAFQgIAFgRAEQgSAEgYAAgAiLhTIAAhdIiOAAIgEgRICSAAIAAheIBqAJQgBAFgFAEQgEAFgMACIAABFIBpAAIAAheIBrAJQAAAFgFAEQgEAFgLACIAABFIAeAAIAsg9IANAMIAgAbQARAPANAOQAAAFgFACQgFADgGAAIiFAAIAABDQAAAFgLAFQgLAEgQAEQgQADgTAAIgOAAIAAhYIhpAAIAABHQAAAFgLAEQgKAGgQACQgQAEgSABg");
	this.shape_65.setTransform(778.95,403.6);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#333333").s().p("Aj9EXQBCgVAngXQAngYAUgaQAUgbAHgdIiMAAIgEgRICTAAQADgQABgQIABgjIhDAAIgDgKQgfAbgoAWQgnAXgxASIgEgGQAygiAlgoQAkgoAZgrIiJAAIgFgRICYAAIAOgdIAMgeIh7AAIgEgRICGAAIAIgbIAIgaIikAAIgFgRICtAAIAIgrIAGgqIB1AXQgBAHgGAEQgFAEgLAAIgGAXIgFAYIBwAAIArg1IANAKIAfAXIAiAbQgCAFgEACQgFADgGAAIjeAAIgJAbIgJAaICBAAIAngwIAMAKIAcAVIAfAYQgBAFgFADQgEACgHAAIjmAAIgPAeIgRAdIDOAAIArg3IAOALIAgAYIAiAbQgBAFgFACQgEADgHAAIirAAQAWAXAfAPQAgANAjAHQAkAHAiACIgBAJQgZAQgPAUQgPAUgCAYQgygWgmgpQglgpgYg0IiIAAQgNASgPARQgPAPgSAQICCAAIAlgsIAMAJIAaATIAdAXQgBAFgFACQgEADgHAAIg/AAQAAASgCARQgCAQgEAQIA1AAIAogzIAMAKIAdAWIAfAaQgBAFgFADQgEACgHAAIiZAAIgEALIgFALQBVAJAvAQQAwARATATQAUASgCARQgBARgPALQgPAKgUAAQgVAAgSgPQgRgWgigcQghgcgygaQgPAagfAWQgfAXg0ASQgzAShOAOg");
	this.shape_66.setTransform(718.925,403.725);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#333333").s().p("AjMEBQgCgNgHgIQgHgIgNgGQgNgGgSgEIAAgHIAZABIAaABIASABIALgBQAEgBAFgDQAKgIAHgpQAHgoAEhJIgtAAIgXAdIhBgjIAIgIIAKgHQADgVACgcIAEg3IACgwIBRAmIAUAAIAAhxIh2AAIgFgQIB0AAIAignIBKA3QgDAFgHAEQgGAEgKACIAAB/QgBACgKAEQgLAEgOADQgOAEgNAAIgMAAIAAgeIgkAAIgCAhIgDAkIgEAiIAqAAIAnglIBCA3QgDAEgGADQgGACgJABQgEBBgFArQgHArgKAZQgKAYgPAMQgPAKgTAGQgTAFgaAAQAAgQgCgNgAA/EeIAAiGIiFAAIgFgRICKAAIAAhHIgkAAIAAAPQAAAEgQAGQgPAHgdABIgNAAIAAkaIBQAeIBdAAQAJgaAKgjQALgjAIgiIBiAmQgCAGgGADQgGACgKAAQgVAWgYAWQgXAUgXARIAXAAIAlgpIBDA0QgDADgGADQgFADgKABIAADHQAAAEgRAHQgRAGgeAAIgNAAIAAgSIgkAAIAABHIAjAAIAng2IAMALIAcAYIAdAaQgBAFgFADQgEACgHAAIh+AAIAAByQAAACgHAFQgHAEgOAEQgNAEgUABgACKAwIAkAAIAAhYIgkAAgAAbAwIAkAAIAAhYIgkAAgACKg5IAkAAIAAhRIgkAAgAAbg5IAkAAIAAhRIgkAAgAAPiwQgEgbgLgaQgMgagPgUIAFgDQAyAHAaARQAZARAGATQAFAUgJAOQgJAPgSAEIgHABQgOAAgSgMg");
	this.shape_67.setTransform(658.475,403.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#333333").s().p("AAyEcIAAl/IgkAAIAAEXQAAADgHAFQgHAGgOAEQgOAEgTAAIgOAAIAAleIBTAgIAcAAIAAhdIiBAAIgFgRID0AAIAqg5IAOALIAeAZQARAPAOANQgBAFgEACQgGACgGABIiBAAIAABdIAfAAIAhgmIBHA2QgCADgFADQgFAEgIACIAADKQAAAagGARQgFASgRALQgSAJgjADIgBggQgBgNgDgIQgCgIgFgFQgGgGgKgCIAAgIIAEAAIAJAAIAJAAQAFAAACgCQACgDgBgEIAAjOIgkAAIAAFpQAAADgIAFQgIAGgOAEQgPAEgVAAgAkHEXQAjgnASgvQAUguAHg1QAHg1AAg5IAAkKIBjAKQgBAGgGAFQgEADgMACIAADwQAAA/gOA4QgOA5gjAuQgiAug8AggAkUCVIAAlkIBcAIQgBAHgEADQgEAEgLACIAAE4QgBADgIAFQgJAFgOADQgNAEgOAAg");
	this.shape_68.setTransform(599.95,404.05);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#333333").s().p("Ai2D7QgDgNgHgJQgHgJgLgHQgLgGgWgEIAAgIIAKABIAWABIAaABIAQABQAGAAADgDQACgBAAgGIAAgxIgkALIglAOQgDAFgEAFQgFADgFABIgihVIA0gFIBIgJIAAg1IAnADIAMgVIALgTIg0AAQgfAYgjAXQgiAXgoASIgGgHQAagRAWgVQAYgVAUgWIg0AAIgGgRIBKAAIAZgeIAXgfIiRAAIgFgRIBaAAIAAhOIg/AAIgFgRIBEAAIAAhTIBnAIQgBAGgFAFQgFADgLADIAAA1IAbgmIAIAIIAVASIANgfIANgeIBZAsQgCAFgGADQgFACgMgCQgQAdgTAfQgVAfgZAeIASAAIAdgpIAHAGIAQANIATASQAKgqAHgrQAHgsAEgsIBxAbQgBAGgGAEQgGAEgKABIgPAwIgQAtIAyAAIAqg3IANAKIAfAZIAfAbQgCAFgEADQgFACgGAAIgaAAQgHBEgSA9QgTA9giA1QAZAbAfAXQAfAXAlARIgCAGQgeAGgRASQgTASgHAdQgfgXgWgbQgYgegQghQgmAlg0AdQgzAehHAUIgDgGQBEgjAsgvQAugtAdg1QgKgggIgiQgHgigFglQgQAWgSAUQgSATgUASIgIgEIAJgTIAHgTIgHACIgKABIgfARIgjARIAVABQAAAIgFADQgFADgJABIAAAUIA2gHIA4gHIABAHIgxAWIg+AZIAABUQABAbgIASQgHAUgVAKQgWAMgrADQgBgSgEgPgABkheQgJASgKAQQAHAdAKAaQAKAZANAXQAPgoAIgrQAJgsACguIgmAAQgIASgJASgAAGgLQAHgRAGgUIALgoIhhAAIgdAfIghAeIAjAAIAlgmgAh1h2IAUggIATghIgnAAg");
	this.shape_69.setTransform(538.85,404);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#333333").s().p("AiUDlIAAg2IAzg4IAvg1QAggkAUgdQAVgbAKgaQAKgbAAggQAAgtgUgaQgTgZgigBIgLABIgMACIgNA7QgGAdgMALQgNAKgOAAQgNAAgLgHQgKgGgFgMQADgiAVgYQAVgYAigNQAigMAnAAQAwAAAeAQQAfAQAPAbQAPAcAAAkQAAAfgSAdQgTAdglAgQglAhg3ArIgiAdIgoAiID6AAIAABKg");
	this.shape_70.setTransform(470.275,403.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48,p:{x:2128.475,y:657.575}},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42,p:{x:2468.875,y:639.025}},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.instance}]}).to({state:[{t:this.shape_70},{t:this.shape_48,p:{x:498.525,y:422.275}},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_42,p:{x:838.925,y:403.725}},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50}]},5).wait(5));

	// bg
	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("EiLsBMwQhvAAhQhPQhPhPAAhwMAAAiRDQAAhwBPhPQBQhPBvAAMEXZAAAQBvAABPBPQBQBPAABwMAAACRDQAABwhQBPQhPBPhvAAg");
	this.shape_71.setTransform(959.9897,540.0003,0.9999,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_71).wait(10));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(999,588.8,2323.4,442.5);
// library properties:
lib.properties = {
	id: '6CC2A54E1AA7D548BDC8E574C2A3EB8B',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#F7C677",
	opacity: 1.00,
	manifest: [
		{src:"images/复习_atlas_P_1.png?1688611223709", id:"复习_atlas_P_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['6CC2A54E1AA7D548BDC8E574C2A3EB8B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;