(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.半 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E89018").s().p("Ah1CvIAAioIDvAAIAACnIglAAIAAgNIinAAIAAAOgAhSCEICnAAIAAgjIinAAgAhSBFICnAAIAAggIinAAgAimgVIAAgfIBZAAQgDgLgFgNQgFgMgHgMIAjgHQAIANAGAPQAGAOACAMIgFABIBWAAQAGgMAGgPIAKgdIjQAAIAAgfICDAAIgGgPIgHgOIAjgGQAFAHAEAKIAIASIB9AAIAAAfIhTAAIAkAIIgMAZIgMAXIBYAAIAAAfg");
	this.shape.setTransform(66.325,29.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E89018").s().p("AgTCtIAAhnIiUAAIAAgjICUAAIAAg1Ih9AAIAAgiIB9AAIAAh4IAkAAIAAB4ICDAAIAAAiIiDAAIAAA1ICXAAIAAAjIiXAAIAABngAhnhcQgGgPgJgPIgQgcIAggNIARAcIAQAdQAGAOAEALIgiAPQgEgLgGgPgAA4hPQAIgMAIgOIAPgeIAMgdIAmAMQgMAXgNAWIgYAng");
	this.shape_1.setTransform(28.525,29.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FCF0D9").s().p("An2HEQhbAAhAhBQhBhAAAhbIAAnPQAAhbBBhAQBAhBBbAAIPtAAQBbAABABBQBBBAAABbIAAHPQAABbhBBAQhABBhbAAg");
	this.shape_2.setTransform(47.3513,28.9713,0.6548,0.6291);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ah1CvIAAioIDvAAIAACnIglAAIAAgNIinAAIAAAOgAhSCEICnAAIAAgjIinAAgAhSBFICnAAIAAggIinAAgAimgVIAAgfIBZAAQgDgLgFgNQgFgMgHgMIAjgHQAIANAGAPQAGAOACAMIgFABIBWAAQAGgMAGgPIAKgdIjQAAIAAgfICDAAIgGgPIgHgOIAjgGQAFAHAEAKIAIASIB9AAIAAAfIhTAAIAkAIIgMAZIgMAXIBYAAIAAAfg");
	this.shape_3.setTransform(66.325,29.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgTCtIAAhnIiUAAIAAgjICUAAIAAg1Ih9AAIAAgiIB9AAIAAh4IAkAAIAAB4ICDAAIAAAiIiDAAIAAA1ICXAAIAAAjIiXAAIAABngAhnhcQgGgPgJgPIgQgcIAggNIARAcIAQAdQAGAOAEALIgiAPQgEgLgGgPgAA4hPQAIgMAIgOIAPgeIAMgdIAmAMQgMAXgNAWIgYAng");
	this.shape_4.setTransform(28.525,29.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E89018").s().p("An2HEQhbAAhAhBQhBhAAAhbIAAnPQAAhbBBhAQBAhBBbAAIPtAAQBbAABABBQBBBAAABbIAAHPQAABbhBBAQhABBhbAAg");
	this.shape_5.setTransform(47.3513,28.9713,0.6548,0.6291);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,94.7,58);


(lib.全 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D24D34").s().p("AhtCtIAAimIDeAAIAAClIgiAAIAAgNIicAAIAAAOgAhNCCICcAAIAAgiIicAAgAhNBFICcAAIAAghIicAAgAicgUIAAgfIBUAAQgDgLgFgMQgFgNgFgLIAfgHQAIANAGAOQAGAPACALIgFABIBQAAIALgbQAHgPADgNIjDAAIAAgfIB7AAIgFgPIgHgOIAggGIAJARQAEAKADAIIB1AAIAAAfIhNAAIAhAIIgMAYIgLAXIBTAAIAAAfg");
	this.shape.setTransform(61.95,29.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D24D34").s().p("AiUCoIAAgfICDAAIAAg2IhVAAIAAgeIBVAAIAAg0IhZAAIAAgXIgTALIgTALIgKgPIgNgOQAhgOAegWQAfgUAZgbQAagaASgdIAcAPIgDAEIgDAFQAgAmAmAcQAlAcArAWQgHAFgGAIQgGAIgEAHIgTgLIgSgMIAAAXIhbAAIAAA0IBZAAIAAAeIhZAAIAAA2ICFAAIAAAfgABigdQgbgSgYgWQgZgWgWgaQgUAZgZAXQgYAWgbASIDCAAIAAAAg");
	this.shape_1.setTransform(26.625,28.55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FAEDEA").s().p("An2HEQhbAAhAhBQhBhAAAhbIAAnPQAAhbBBhAQBAhBBbAAIPtAAQBbAABABBQBBBAAABbIAAHPQAABbhBBAQhABBhbAAg");
	this.shape_2.setTransform(44.234,28.5718,0.612,0.6197);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhtCtIAAimIDeAAIAAClIgiAAIAAgNIicAAIAAAOgAhNCCICcAAIAAgiIicAAgAhNBFICcAAIAAghIicAAgAicgUIAAgfIBUAAQgDgLgFgMQgFgNgFgLIAfgHQAIANAGAOQAGAPACALIgFABIBQAAIALgbQAHgPADgNIjDAAIAAgfIB7AAIgFgPIgHgOIAggGIAJARQAEAKADAIIB1AAIAAAfIhNAAIAhAIIgMAYIgLAXIBTAAIAAAfg");
	this.shape_3.setTransform(61.95,29.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiUCoIAAgfICDAAIAAg2IhVAAIAAgeIBVAAIAAg0IhZAAIAAgXIgTALIgTALIgKgPIgNgOQAhgOAegWQAfgUAZgbQAagaASgdIAcAPIgDAEIgDAFQAgAmAmAcQAlAcArAWQgHAFgGAIQgGAIgEAHIgTgLIgSgMIAAAXIhbAAIAAA0IBZAAIAAAeIhZAAIAAA2ICFAAIAAAfgABigdQgbgSgYgWQgZgWgWgaQgUAZgZAXQgYAWgbASIDCAAIAAAAg");
	this.shape_4.setTransform(26.625,28.55);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#D24D34").s().p("An2HEQhbAAhAhBQhBhAAAhbIAAnPQAAhbBBhAQBAhBBbAAIPtAAQBbAABABBQBBBAAABbIAAHPQAABbhBBAQhABBhbAAg");
	this.shape_5.setTransform(44.234,28.5718,0.612,0.6197);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,88.5,57.1);


(lib.多余键盘 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EDAqAS1QhSAAg5geQg7geAAgsIAAxNIGEAAQA4AAAlgQQAngRAAgWIAAx8IAAgBIIEAAQBTAAA4AfQA8AeAAAtMAAAAiXQAAAsg8AeQg4AehTAAgEhWJAS1QhTAAg4geQg8geAAgsIAAxNIGEAAQA5AAAkgQQAogRAAgWIAAx8IAAgBIIEAAQBSAAA5AfQA7AeAAAtMAAAAiXQAAAsg7AeQg5AehSAAgEjNvAS1Qg1AAgrgMQgXgHgUgLQg7gegBgrMAAAgiZQABgsA7geQAUgLAXgHQArgNA1AAIHlAAIAAABIAAR8QAAAXAnAQQAlAQA1AAIGmAAIAARNQAAAsg7AeQg5AehSAAgECssAS1QhPAAg5geQg7geAAgsIAAxNIDoAAQA4AAAlgQQAkgPAAgYIAAx8IAAgBIJiAAIAAABIAAR8QAAAWAoARQAkAQA4AAICEAAIAARNQAAAsg8AeQg4AehTAAgECYyAS1QhTAAg4geQg8geAAgsIAAxNIBdAAQA5AAAkgQQAkgPAAgYIAAx8IAAgBIJUAAIAAABIAAR8QAAAWAoARQAkAQA1AAIEgAAIAARNQAAAsg4AeQg8AehPAAgECE4AS1QhTAAg4geQg8geAAgsMAAAgiYQAAgsA8geQA4gfBTAAIHcAAIAAABIAAR8QAAAWAoARQAkAQA1AAIGvAAIAARNQAAAsg7AeQg5AehSAAgEBw5AS1QhTAAg4geQg5geAAgsIAAxNIGPAAQA1AAAkgQQAogRAAgWIAAx8IAAgBIH9AAQBTAAA4AfQA8AeAAAsMAAAAiYQAAAsg8AeQg4AehTAAgEBc/AS1QhTAAg5geQg7geAAgsIAAxNIBlAAQA5AAAkgQQAkgPAAgYIAAx8IAAgBILuAAIAAABIAAR8QAAAWAoARQAlAQA4AAIB6AAIAARNQAAAsg8AeQg4AehTAAgEhqIAS1QhPAAg4geQg8geAAgsIAAxNIDoAAQA5AAAkgQQAlgPAAgYIAAx8IAAgBIJhAAIAAABIAAR8QAAAWAoARQAkAQA5AAICDAAIAARNQAAAsg7AeQg5AehSAAgEh+CAS1QhTAAg4geQg7geAAgsIAAxNIBdAAQA4AAAkgQQAlgPAAgYIAAx8IAAgBIJTAAIAAABIAAR8QAAAWAoARQAlAQA1AAIEgAAIAARNQAAAsg5AeQg7AehQAAgEiR8AS1QhSAAg5geQg7geAAgsMAAAgiYQAAgsA7geQA5gfBSAAIHdAAIAAABIAAR8QAAAWAnARQAlAQA1AAIGvAAIAARNQAAAsg8AeQg4AehTAAgEil7AS1QhSAAg5geQg4geAAgsIAAxNIGOAAQA1AAAlgQQAngRAAgWIAAx8IAAgBIH9AAQBTAAA4AfQA8AeAAAsMAAAAiYQAAAsg8AeQg4AehTAAgEi51AS1QhTAAg4geQg8geAAgsIAAxNIBmAAQA4AAAkgQQAlgPAAgYIAAx8IAAgBILuAAIAAABIAAR8QAAAWAoARQAkAQA4AAIB6AAIAARNQAAAsg7AeQg4AehTAAg");
	this.shape.setTransform(1336.675,125.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231916").s().p("EC9zAJ0IgoAAIiDAAQg5AAgkgPQgogRAAgXIAAx6IAAgCQACgVAmgPQAogQA1AAIIvAAQA1AAAoAQQAmAPACAVIAAACIAAR6QAAAXgoARQgkAPg5AAgECp4AJ0IgqAAIkgAAQg1AAglgPQgogRAAgXIAAx6IAAgCQACgVAmgPQAlgQA1AAIIyAAQA1AAAoAQQAkAPABAVIAAACIAAR6QAAAZglAPQgkAPg5AAgECV7AJ0IgnAAImvAAQg1AAglgPQgngRAAgXIAAx6IAAgCQABgVAmgPQAlgQA1AAIIzAAQA1AAAnAQQAkAPABAVIAAACIAAR6QAAAZglAPQgkAPg4AAgEBuFAJ0IgrAAIh6AAQg4AAgkgPQgogRAAgXIAAx6IAAgCQABgVAngPQAngQA1AAIIzAAQA1AAAlAQQAmAPABAVIAAACIAAR6QAAAXgnARQglAPg1AAgEBaHAJ0InNAAQg1AAglgPQgngRAAgWIAAx7IAAgCQABgVAmgPQAlgQA1AAIIzAAQA1AAAnAQQAkAPABAVIAAACIAAR7QAAAXglAQQgkAPg4AAgEhZAAJ0IgoAAIiEAAQg4AAgkgPQgogRAAgXIAAx6IAAgCQABgVAngPQAngQA1AAIIwAAQA1AAAoAQQAmAPABAVIAAACIAAR6QAAAXgnARQglAPg4AAgEhs7AJ0IgrAAIkgAAQg1AAgkgPQgogRAAgXIAAx6IAAgCQABgVAngPQAkgQA1AAIIzAAQA1AAAoAQQAjAPABAVIAAACIAAR6QAAAZgkAPQglAPg4AAgEiA5AJ0IgnAAImvAAQg1AAgkgPQgogRAAgXIAAx6IAAgCQACgVAmgPQAkgQA1AAIIzAAQA1AAAoAQQAjAPABAVIAAACIAAR6QAAAZgkAPQgkAPg5AAgEiovAJ0IgqAAIh6AAQg4AAglgPQgogRAAgXIAAx6IAAgCQACgVAmgPQAogQA1AAIIzAAQA1AAAkAQQAmAPACAVIAAACIAAR6QAAAXgoARQgkAPg1AAgEi8sAJ0IgnAAImnAAQg1AAgkgPQgogRAAgWIAAx7IAAgCQACgVAmgPQAkgQA1AAIIzAAQA1AAAoAQQAjAPABAVIAAACIAAR7QAAAXgkAQQgkAPg5AAg");
	this.shape_1.setTransform(1335.125,62.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,2673.4,246.4);


// stage content:
(lib.c自然大调音阶 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {q1:4,q2:9,b3:14,q4:19,q5:24,q6:29,b7:34};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		var _this = this;
		
		
		_this.q1_btn.on('click', function(){
		
		_this.gotoAndStop('q1');
			
		});
		
		
		_this.q2_btn.on('click', function(){
		
		_this.gotoAndStop('q2');
			
		});
		
		
		
		_this.b3_btn.on('click', function(){
		
		_this.gotoAndStop('b3');
			
		});
		
		
		_this.q4_btn.on('click', function(){
		
		_this.gotoAndStop('q4');
			
		});
		
		
		_this.q5_btn.on('click', function(){
		
		_this.gotoAndStop('q5');
			
		});
		
		
		_this.q6_btn.on('click', function(){
		
		_this.gotoAndStop('q6');
			
		});
		
		
		_this.b7_btn.on('click', function(){
		
		_this.gotoAndStop('b7');
			
		});
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(39));

	// 左右遮罩 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EiP5BONMAAAicZMEfzAAAMAAACcZg");
	mask.setTransform(959.925,564.975);

	// 图层_5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhtCtIAAimIDfAAIAAClIgjAAIAAgNIicAAIAAAOgAhNCCICcAAIAAgiIicAAgAhNBFICcAAIAAghIicAAgAibgUIAAgfIBTAAQgDgLgFgMQgFgNgFgLIAfgHQAIANAGAOQAGAPACALIgFABIBQAAIALgbQAHgPADgNIjDAAIAAgfIB7AAIgFgPIgHgOIAggGIAJARQAFAKACAIIB1AAIAAAfIhNAAIAhAIIgMAYIgLAXIBTAAIAAAfg");
	this.shape.setTransform(592.6,410.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiUCoIAAgfICDAAIAAg2IhVAAIAAgfIBVAAIAAgzIhZAAIAAgXIgTALIgTALIgKgOIgNgPQAhgOAegWQAfgUAZgbQAagaASgdIAcAOIgDAGIgDAEQAgAmAmAcQAlAcArAVQgHAGgGAIQgGAIgEAHIgTgLIgSgMIAAAXIhbAAIAAAzIBZAAIAAAfIhZAAIAAA2ICFAAIAAAfgABigdQgbgSgYgWQgZgWgWgbQgUAagZAXQgYAVgbATIDCAAIAAAAg");
	this.shape_1.setTransform(557.275,409.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D24D34").s().p("An2HEQhbAAhAhBQhBhAAAhbIAAnPQAAhbBBhAQBAhBBbAAIPtAAQBbAABABBQBBBAAABbIAAHPQAABbhBBAQhABBhbAAg");
	this.shape_2.setTransform(574.884,409.9719,0.612,0.6197);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#D24D34").ss(6,1,1).p("AqAGFQAPg3AOgyQAahUAahHQBJjEBUhnQC1jaEAAAQD/AAC1DaQBwCFAqCmQAJAkAGAm");
	this.shape_3.setTransform(571.85,491.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#D24D34").ss(6,1,1).p("AqNGGQAMgmALgkQBulUB4iUQC1jZEAAAQEAAAC1DZQCGCjAuD4");
	this.shape_4.setTransform(701.275,472.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhtCtIAAimIDeAAIAAClIgiAAIAAgNIicAAIAAAOgAhNCCICcAAIAAgiIicAAgAhNBFICcAAIAAghIicAAgAicgUIAAgfIBUAAQgDgLgFgMQgFgNgFgLIAfgHQAIANAGAOQAGAPACALIgFABIBQAAIALgbQAHgPADgNIjDAAIAAgfIB7AAIgFgPIgHgOIAggGIAJARQAEAKADAIIB1AAIAAAfIhNAAIAhAIIgMAYIgLAXIBTAAIAAAfg");
	this.shape_5.setTransform(718.95,392.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiUCoIAAgfICDAAIAAg2IhVAAIAAgeIBVAAIAAg0IhZAAIAAgXIgTAMIgTAKIgKgPIgNgNQAhgPAegVQAfgWAZgZQAagbASgdIAcAOIgDAGIgDAEQAgAmAmAcQAlAcArAVQgHAGgGAIQgGAIgEAHIgTgLIgSgLIAAAWIhbAAIAAA0IBZAAIAAAeIhZAAIAAA2ICFAAIAAAfgABigcQgbgTgYgWQgZgWgWgbQgUAagZAWQgYAWgbAUIDCAAIAAAAg");
	this.shape_6.setTransform(683.625,392.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ah1CvIAAioIDvAAIAACnIglAAIAAgNIinAAIAAAOgAhSCEICnAAIAAgjIinAAgAhSBFICnAAIAAggIinAAgAimgVIAAgfIBZAAQgDgLgFgNQgFgMgHgMIAjgHQAIANAGAPQAGAOACAMIgFABIBWAAIAMgbIAKgdIjQAAIAAgfICDAAIgGgPIgHgOIAjgGQAFAHAEAKIAIASIB9AAIAAAfIhTAAIAkAIIgMAZIgMAXIBYAAIAAAfg");
	this.shape_7.setTransform(849.125,372.775);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgTCtIAAhnIiUAAIAAgjICUAAIAAg1Ih9AAIAAgiIB9AAIAAh4IAkAAIAAB4ICDAAIAAAiIiDAAIAAA1ICXAAIAAAjIiXAAIAABngAhnhcQgGgPgJgPIgQgcIAggNIARAcIAQAdQAGAOAEALIgiAPQgEgLgGgPgAA4hPQAIgMAIgOIAPgeIAMgdIAmAMQgMAXgNAWIgYAng");
	this.shape_8.setTransform(811.325,372.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E89018").s().p("An2HEQhbAAhAhBQhBhAAAhbIAAnPQAAhbBBhAQBAhBBbAAIPtAAQBbAABABBQBBBAAABbIAAHPQAABbhBBAQhABBhbAAg");
	this.shape_9.setTransform(830.1513,372.1713,0.6548,0.6291);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#E89018").ss(6,1,1).p("Ao5G7IJAt1IIzLU");
	this.shape_10.setTransform(829.65,452.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhuCtIAAimIDfAAIAAClIgiAAIAAgNIicAAIAAAOgAhNCCICcAAIAAgiIicAAgAhNBFICcAAIAAghIicAAgAicgUIAAgfIBTAAQgCgLgFgMQgEgNgHgLIAhgHQAHANAGAOQAFAPADALIgFABIBQAAIALgbQAGgPAEgNIjDAAIAAgfIB7AAIgGgPIgGgOIAggGIAJARIAHASIB1AAIAAAfIhOAAIAiAIIgLAYIgLAXIBTAAIAAAfg");
	this.shape_11.setTransform(976.95,361.575);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiUCoIAAgfICDAAIAAg2IhVAAIAAgfIBVAAIAAgzIhZAAIAAgXIgTAMIgTAKIgKgPIgNgNQAhgPAegVQAfgWAZgZQAagbASgdIAcAOIgDAGIgDAEQAgAmAmAcQAlAcArAVQgHAGgGAIQgGAIgEAHIgTgLIgSgLIAAAWIhbAAIAAAzIBZAAIAAAfIhZAAIAAA2ICFAAIAAAfgABigcQgbgTgYgWQgZgWgWgbQgUAagZAWQgYAWgbAUIDCAAIAAAAg");
	this.shape_12.setTransform(941.625,361.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#D24D34").ss(6,1,1).p("Ap/GFQBomNCFiiQC2jaEAAAQD/AAC1DaQCGCiAjDT");
	this.shape_13.setTransform(957.8,440.775);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhuCtIAAimIDfAAIAAClIgiAAIAAgNIicAAIAAAOgAhNCCICcAAIAAgiIicAAgAhNBFICcAAIAAghIicAAgAicgUIAAgfIBTAAQgCgLgFgMQgEgNgHgLIAhgHQAHANAGAOQAFAPADALIgFABIBQAAIAMgbQAFgPAEgNIjDAAIAAgfIB7AAIgGgPIgGgOIAggGIAJARIAHASIB1AAIAAAfIhOAAIAiAIIgLAYIgLAXIBTAAIAAAfg");
	this.shape_14.setTransform(1109.7,344.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AiUCoIAAgfICDAAIAAg2IhVAAIAAgfIBVAAIAAgzIhZAAIAAgXIgTALIgTALIgKgOIgNgPQAhgOAegWQAfgUAZgaQAagbASgdIAcAOIgDAGIgDAEQAgAmAmAcQAlAcArAVQgHAGgGAIQgGAIgEAHIgTgLIgSgLIAAAWIhbAAIAAAzIBZAAIAAAfIhZAAIAAA2ICFAAIAAAfgABigdQgbgSgYgWQgZgWgWgbQgUAagZAXQgYAVgbATIDCAAIAAAAg");
	this.shape_15.setTransform(1074.375,344.15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#D24D34").ss(6,1,1).p("Ap/GFQBomNCFiiQC1jaEAAAQEAAAC0DaQCHCiAiDT");
	this.shape_16.setTransform(1092.025,423.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhuCtIAAimIDgAAIAAClIgjAAIAAgNIicAAIAAAOgAhNCCICcAAIAAgiIicAAgAhNBFICcAAIAAghIicAAgAibgUIAAgfIBSAAQgCgLgFgMQgFgNgGgLIAhgHQAHANAGAOQAFAPADALIgFABIBQAAIAMgbQAFgPAEgNIjDAAIAAgfIB7AAIgGgPIgHgOIAhgGIAJARQAFAKACAIIB1AAIAAAfIhOAAIAiAIIgLAYIgMAXIBUAAIAAAfg");
	this.shape_17.setTransform(1239.1,326.575);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AiUCoIAAgfICDAAIAAg2IhVAAIAAgfIBVAAIAAgzIhZAAIAAgXIgTALIgTALIgKgOIgNgOQAhgPAegWQAfgVAZgZQAagbASgdIAcAOIgDAGIgDAEQAgAmAmAcQAlAcArAVQgHAGgGAIQgGAIgEAHIgTgLIgSgLIAAAWIhbAAIAAAzIBZAAIAAAfIhZAAIAAA2ICFAAIAAAfgABigcQgbgTgYgWQgZgWgWgbQgUAagZAWQgYAXgbATIDCAAIAAAAg");
	this.shape_18.setTransform(1203.775,326.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#D24D34").ss(6,1,1).p("AqNGGQB4mPCGijQC1jZEAAAQD/AAC1DZQCGCjAtD4");
	this.shape_19.setTransform(1221.4,404.675);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_3},{t:this.shape_2,p:{x:574.884,y:409.9719}},{t:this.shape_1},{t:this.shape}]},4).to({state:[{t:this.shape_2,p:{x:701.234,y:392.1219}},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]},5).to({state:[{t:this.shape_10},{t:this.shape_9,p:{x:830.1513,y:372.1713}},{t:this.shape_8,p:{x:811.325,y:372.825}},{t:this.shape_7,p:{x:849.125,y:372.775}}]},5).to({state:[{t:this.shape_13},{t:this.shape_2,p:{x:959.234,y:361.0719}},{t:this.shape_12},{t:this.shape_11}]},5).to({state:[{t:this.shape_16},{t:this.shape_2,p:{x:1091.984,y:344.1719}},{t:this.shape_15},{t:this.shape_14}]},5).to({state:[{t:this.shape_19},{t:this.shape_2,p:{x:1221.384,y:326.0719}},{t:this.shape_18},{t:this.shape_17}]},5).to({state:[{t:this.shape_9,p:{x:1349.8012,y:303.6713}},{t:this.shape_8,p:{x:1330.975,y:304.325}},{t:this.shape_7,p:{x:1368.775,y:304.275}}]},5).wait(5));

	// 全半音按钮
	this.b7_btn = new lib.半();
	this.b7_btn.name = "b7_btn";
	this.b7_btn.setTransform(1349.85,303.7,1,1,0,0,0,47.4,29);
	new cjs.ButtonHelper(this.b7_btn, 0, 1, 2, false, new lib.半(), 3);

	this.q6_btn = new lib.全();
	this.q6_btn.name = "q6_btn";
	this.q6_btn.setTransform(1221.35,326.1,1,1,0,0,0,44.2,28.6);
	new cjs.ButtonHelper(this.q6_btn, 0, 1, 2, false, new lib.全(), 3);

	this.q5_btn = new lib.全();
	this.q5_btn.name = "q5_btn";
	this.q5_btn.setTransform(1091.95,344.2,1,1,0,0,0,44.2,28.6);
	new cjs.ButtonHelper(this.q5_btn, 0, 1, 2, false, new lib.全(), 3);

	this.q4_btn = new lib.全();
	this.q4_btn.name = "q4_btn";
	this.q4_btn.setTransform(959.2,361.1,1,1,0,0,0,44.2,28.6);
	new cjs.ButtonHelper(this.q4_btn, 0, 1, 2, false, new lib.全(), 3);

	this.b3_btn = new lib.半();
	this.b3_btn.name = "b3_btn";
	this.b3_btn.setTransform(830.2,372.2,1,1,0,0,0,47.4,29);
	new cjs.ButtonHelper(this.b3_btn, 0, 1, 2, false, new lib.半(), 3);

	this.q2_btn = new lib.全();
	this.q2_btn.name = "q2_btn";
	this.q2_btn.setTransform(701.2,392.15,1,1,0,0,0,44.2,28.6);
	new cjs.ButtonHelper(this.q2_btn, 0, 1, 2, false, new lib.全(), 3);

	this.q1_btn = new lib.全();
	this.q1_btn.name = "q1_btn";
	this.q1_btn.setTransform(574.85,410,1,1,0,0,0,44.2,28.6);
	new cjs.ButtonHelper(this.q1_btn, 0, 1, 2, false, new lib.全(), 3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#D24D34").ss(1,1,1).p("AUbCRQBomNCGiiQC1jaEBAAQD/AAC1DaQCGCiAjDUQB4mRCFiiQC1jaEBAAQD/AAC1DaQCHCiAtD5AgiE/QBnmNCGijQC1jaEBAAQD/AAC1DaQCGCjAjDSEg82AM2QAPg3AOgyQAZhUAbhHQBJjFBUhnQC1jaEBAAQD/AAC1DaQBvCFArCnQAJAkAGAmQAMgmALgkQBulVB4iUQC1jZEBAAQEAAAC1DZQCGCjAuD4");
	this.shape_20.setTransform(897.275,447.85);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#E89018").ss(1,1,1).p("AfuBpIJCt1IIzLVEgxiAMOIJBt1IIzLU");
	this.shape_21.setTransform(1089.75,418.4);

	var maskedShapeInstanceList = [this.b7_btn,this.q6_btn,this.q5_btn,this.q4_btn,this.b3_btn,this.q2_btn,this.q1_btn,this.shape_20,this.shape_21];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.q1_btn},{t:this.q2_btn},{t:this.b3_btn},{t:this.q4_btn},{t:this.q5_btn},{t:this.q6_btn},{t:this.b7_btn}]}).wait(39));

	// 变色
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#D24D34").s().p("Awfc8Qg1AAgrgNQgXgHgUgKQg8geABgsMAAAgiYQgBgsA8geQAUgLAXgIQArgNA1AAIHlAAIAAACIAAR7QAAAWAoARQAkAPA1AAIGnAAIAARPQgBAsg7AeQg4AehTAAgADac7QhTAAg4geQg7gegBgsIAAxOIBmAAQA4AAAlgPQAkgQAAgXIAAx7IAAgCILuAAIAAACIAAR6QAAAXAoARQAlAPA4AAIB5AAIAAROQABAsg8AeQg4AehTAAgArzoyQgCgDAAgEIAAgkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAAAkQAAAEgCADQgDADgEAAQgFAAgDgDgAIipJQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArzqSQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAAA8QAAAEgCADQgDADgEAAQgFAAgDgDgAIirBQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArzsKQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAAA8QAAAEgCADQgDADgEAAQgFAAgDgDgAIis5QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArzuCQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAAA8QAAAEgCADQgDADgEAAQgFAAgDgDgAIiuxQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArzv6QgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAAA8QAAAEgCADQgDADgEAAQgFAAgDgDgAIiwpQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArzxyQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAAA8QAAAEgCADQgDADgEAAQgFAAgDgDgAIiyhQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArzzqQgCgDAAgEIAAg8IAAgDIACgEQADgDAFAAQAEAAADADIACAEIgCgEQgDgDgEAAQgFAAgDADIgCAEQg2AAgygKQg0gLgpgWQgWgLgQgOQgSgOgNgRQgbgigDgvQgDgjAUggQATgfAlgYQAjgYAxgPQAwgOA4AAQA5AAA0AKQA1ALAoAWQApAXAbAiQAaAiAEAwQACAigSAfQgOAWgTASQgKAJgMAHQgkAYgwAOQgrAMgwACIAAADIAAA8QAAAEgCADQgDADgEAAQgFAAgDgDgAtE5jQgSAKgMARQgNAPgFAUQgFAUADAUQAFAjAJAgQAJAhAPAXQAEAIAGAGQAMAOAQAKQAWANAhAAQAYAAATgKQAUgLANgQIABAAQAMgRAGgSQAHgUgEgTQgEgkgKggQgJgggQgYQgRgYgXgOQgXgOghAAQgYAAgUALgAIi0ZQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAIi2RQgDgDAAgEIAAg8IABgEIACgDQADgDAEAAQAEAAADADIACADIgCgDQgDgDgEAAQgEAAgDADIgCADQg0gBgwgJQg0gLgpgVQgqgXgbgiQgagigFgvQgCgiAUggQATggAkgYQAkgYAygPQAvgOA4AAQA5AAA0AKQA1ALAoAXQApAXAaAiQAbAhAEAwQADAigTAgQgTAggkAXQgkAYgxAPQgsAMgzABIABAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAHW8LQgTALgMAPQgNARgEAUQgGAUADATQAFAjAJAgQAJAhAPAXQAPAZAWANQAXANAhAAQAYAAATgKQAUgLANgQQANgQAHgTQAFgUgDgTQgEgjgKggQgKgggPgZQgRgXgXgPQgXgOgiAAQgXAAgTALg");
	this.shape_22.setTransform(584.15,698.225);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#D24D34").s().p("ADZePQhTAAg5gdQg4gfAAgsIAAxNIGOAAQA1AAAlgQQAogRAAgWIAAx7IAAgCIA5AAQAAAFADACQADADAEAAQAEAAADgDQADgCAAgFQAAAFgDACQgDADgEAAQgEAAgDgDQgDgCAAgFIAAgZQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAAZIGvAAQBTABA5AfQA7AeAAAsMAAAAiXQAAAsg7AfQg5AdhTAAgAwhePQhTAAg4gdQg7gfgBgsIAAxNIBmAAQA4AAAlgQQAkgPAAgYIAAx7IAAgCILuAAIAAACIAAR7QAAAWAoARQAlAQA4AAIB5AAIAARNQABAsg8AfQg4AdhTAAgArZn1QgDgCAAgFIAAg7QAAgFADgCQADgDAEAAQAEAAADADQADACAAAFIAAA7QAAAFgDACQgDADgEABQgEgBgDgDgAJiooQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArZpsQgDgDAAgFIAAg8QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA8QAAAFgDADQgDACgEAAQgEAAgDgCgAJiqgQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArZrkQgDgDAAgEIAAg9QAAgEADgDQADgCAEAAQAEAAADACQADADAAAEIAAA9QAAAEgDADQgDACgEABQgEgBgDgCgAJisYQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArZtdQgDgCAAgFIAAg7QAAgFADgCQADgDAEAAQAEAAADADQADACAAAFIAAA7QAAAFgDACQgDADgEABQgEgBgDgDgAJiuQQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArZvUQgDgDAAgFIAAg8QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA8QAAAFgDADQgDACgEAAQgEAAgDgCgAJiwIQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArZxMQgDgDAAgEIAAg9QAAgEADgDQADgCAEAAQAEAAADACQADADAAAEIAAA9QAAAEgDADQgDACgEABQgEgBgDgCgAJiyAQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArZzFQgDgCAAgFIAAg7QAAgFADgCQADgDAEAAQAEAAADADQADACAAAFIAAA7QAAAFgDACQgDADgEABQgEgBgDgDgAJiz4QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgArZ08QgDgDAAgFIAAg8IABgEQg0AAgwgKQg0gKgpgWQgqgXgbgiQgagigFgvQgCgiAUggQATgfAkgZQAkgYAygPQAvgNA4AAQA5AAA0AKQA1AKAoAXQApAXAaAiQAbAiAEAvQADAigTAgQgTAggkAXQgkAZgxAOQgsAMgzABIgCgCQgDgDgEgBQgEABgDADIgCACIACgCQADgDAEgBQAEABADADIACACIABAEIAAA8QAAAFgDADQgDACgEAAQgEAAgDgCgAsl63QgTALgMAQQgNAQgEAUQgGAUADATQAFAjAJAhQAJAgAPAYQAPAYAWANQAXAOAhAAQAYAAATgLQAUgKANgRQANgPAHgTQAFgUgDgUQgEgjgKggQgKgggPgZQgRgXgXgPQgXgNgiAAQgXAAgTAKgAJi1wQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJi3oQgDgDAAgEIAAg8Qg1gBgxgKQg0gLgpgVQgqgXgbghQgagjgEgvQgDgiAUggQAKgRAPgOQANgNASgLQAjgYAxgPQAxgOA4AAQAbAAAcACQAbADAaAFQA0ALApAWQAaAPAVATQALALAKAMQAaAiAFAvQACAjgTAfQgTAggkAYQgjAXgxAPQgrAMgxACQAAgEgDgDQgDgDgEAAQgEAAgDADQgDADAAAEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAIU9fQgUALgMAQIgCADQgKAOgGATQgFAUADATQAFAkAKAgQAIAgAPAYQAPAYAXANQAWANAiABQAYgBATgJQATgMANgPQAOgRAFgSQAGgVgCgSQgFgkgKggQgJgggQgYIgJgMQgNgQgRgKQgYgOghAAQgYAAgSAKg");
	this.shape_23.setTransform(711.75,689.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#E89018").s().p("ADbfiQhSAAg5geQg8geAAgsMAAAgiXQAAgsA8geQA5ggBSAAIHcAAIAAACIAAR6QAAAXAoARQAlAPA1AAIGvAAIAAROQAAAsg8AeQg5AehSAAgAwjfiQhSAAg5geQg4geAAgsIAAxOIGOAAQA1AAAlgPQAngRAAgXIAAx6IAAgCIA6AAQAAAEACADQADADAFAAQAEAAADgDQACgDABgEQgBAEgCADQgDADgEAAQgFAAgDgDQgCgDAAgEIAAgZQAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAAZIGvAAQBTAAA4AgQA8AeAAAsMAAAAiXQAAAsg8AeQg4AehTAAgAIgmLQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqanVQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIgoDQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqapNQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIgp7QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqarFQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIgrzQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqas9QgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIgtrQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqau1QgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIgvjQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqawtQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIgxbQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqaylQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIgzTQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqa0dQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABAEIAAA8QgBAEgCADQgDADgEAAQgFAAgDgDgAIg1LQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqa2VQgCgDAAgEIAAg8QAAgEACgDQADgDAFAAQAEAAADADQACADABADQgBgDgCgDQgDgDgEAAQgFAAgDADQgCADAAAEQg1gBgxgKQg0gLgqgWQgpgWgbghQgbgjgEgvQgCgiATggQALgRAPgOQAMgNASgMQAkgXAxgPQAwgPA4AAQAcAAAbADQAbACAaAFQA1ALApAXQAaAPAVATQALAKAJAMQAbAjAEAvQADAigTAgQgUAggjAXQgkAYgxAPQgqAMgxABIAAA9QgBAEgCADQgDADgEAAQgFAAgDgDgAro8MQgUALgLAQIgCADQgLAOgFATQgGAUAEATQAFAjAJAgQAJAhAPAYQAPAYAWANQAXANAhAAQAYAAATgKQAUgLANgQQAOgQAFgTQAGgUgDgTQgFgjgJggQgKgggPgYIgJgMQgOgQgRgLQgXgNgiAAQgYAAgSAKgAIg3DQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAIg47QgDgDAAgEIAAg8QgzgBgwgJQg0gLgpgWQgqgWgagiIgJgNQgTgegDgmQgDgjAUggQATggAkgXQAfgUCPggIAPgBQA5AAA0AKQA1ALAoAWQApAXAbAiQAaAiAEAvQADAggQAeIgDAEQgUAhgjAXQgkAYgwAOQgsANgzABQAAgEgDgDQgDgDgEAAQgEAAgDADQgDADAAAEQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAHU+yQgTALgLAQIgDADQgLAPgEASQgGAUAEATQAEAkAJAgQAEANAFANQAHAQAIAOQAQAYAWAOQAWANAhAAQAYAAAUgKQATgLAMgQQAPgQAGgTIACgJQADgQgCgOQgGgjgJghQgJgggPgYQgRgYgYgOQgWgOgiAAQgYAAgTAKg");
	this.shape_24.setTransform(839.4,681.525);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#D24D34").s().p("EADaAg0QhTAAg4gdQg7gfgBgsIAAxNIBdAAQA5AAAkgQQAlgPAAgYIAAx7IAAgCIJTAAIAAACIAAR7QAAAWAoARQAkAQA1AAIEgAAIAARNQABAsg5AfQg7AdhQAAgEgQfAg0QhSAAg5gdQg8gfAAgsMAAAgiXQAAgsA8geQA5gfBSgBIHcAAIAAACIAAR7QAAAWAoARQAlAQA1AAIGvAAIAARNQAAAsg8AfQg5AdhSAAgArak4QgDgDAAgEIAAg9QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA9QAAAEgDADQgDACgEAAQgEAAgDgCgAJilmQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgAramxQgDgCAAgEIAAg8QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgAJineQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgAraopQgDgCAAgFIAAg7QAAgFADgCQADgDAEAAQAEAAADADQADACAAAFIAAA7QAAAFgDACQgDADgEAAQgEAAgDgDgAJipWQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgAraqgQgDgDAAgEIAAg9QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA9QAAAEgDADQgDACgEAAQgEAAgDgCgAJirOQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgArasZQgDgCAAgEIAAg8QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgAJitGQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgArauRQgDgCAAgFIAAg7QAAgFADgCQADgDAEAAQAEAAADADQADACAAAFIAAA7QAAAFgDACQgDADgEAAQgEAAgDgDgAJiu+QgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgArawIQgDgDAAgEIAAg9QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA9QAAAEgDADQgDACgEAAQgEAAgDgCgAJiw2QgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgArayBQgDgCAAgEIAAg8QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgAJiyuQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgAraz5QgDgCAAgFIAAg7QAAgFADgCQADgDAEAAQAEAAADADQADACAAAFIAAA7QAAAFgDACQgDADgEAAQgEAAgDgDgAJi0mQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgAra1wQgDgDAAgEIAAg9QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA9QAAAEgDADQgDACgEAAQgEAAgDgCgAJi2eQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgAra3pQgDgCAAgEIAAg8QgzgBgwgKQg0gLgpgWQgqgWgagiIgJgNQgTgegDgmQgDgiAUggQATghAkgXQAfgUCPggIAPgBQA5AAA0AKQA1ALAoAWQApAYAbAhQAaAiAEAwQADAggQAdIgDAFQgUAggjAXQgkAYgwAOQgsANgzACQAAgFgDgDQgDgCgEAAQgEAAgDACQgDADAAAFQAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgAsm9fQgTALgLAQIgDACQgLAPgEATQgGAUAEASQAEAkAJAgQAEANAFANQAHAQAIAPQAQAYAWANQAWANAhAAQAYAAAUgKQATgLAMgQQAPgQAGgTIACgJQADgPgCgPQgGgjgJggQgJghgPgYQgRgYgYgOQgWgNgiAAQgYAAgTAKgAJi4WQgDgDgBgEIAAg8QABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgAJi6OQgDgDgBgEIAAg8IgCAAQg5AAg0gKQg0gLgqgWQgpgWgagiQgbgigFgvQgCgjATggQAUggAlgYQAjgXAxgOQAwgOA5gBQA3ABA1AJQA0ALApAXQApAWAaAiQAbAiAEAvQADAjgTAgQgTAggkAXQgkAYgwAOQgnALgsADQAAgEgDgDQgCgDgFAAQgEAAgCADQgDADgBAEQABgEADgDQACgDAEAAQAFAAACADQADADAAAEIAAA8QAAAEgDADQgCADgFAAQgEAAgCgDgEAIJggFQgTALgMAQQgMARgGATQgFAVADATQAFAjAKAgQAIAhAPAYQAPAXAWAOQAXANAhAAQAYAAATgKQATgLANgQQAPgQAFgTQAHgUgDgTQgGgjgJghQgJgfgQgZQgRgYgXgOQgXgOgiAAQgXABgTAJg");
	this.shape_25.setTransform(966.9,673.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#D24D34").s().p("EADYAiJQhPAAg4geQg8geAAgsIAAxOIDoAAQA5AAAkgQQAlgPAAgYIAAx7IAAgBIDxAAQAAAEADADQADADAEAAQAEAAADgDQADgDAAgEIFcAAIAAABIAAR7QAAAWAoARQAkAQA5AAICDAAIAAROQAAAsg7AeQg5AehSAAgEgQhAiJQhTAAg4geQg7geAAgsIAAxOIBdAAQA4AAAkgQQAlgPAAgYIAAx7IAAgBIJTAAIAAABIAAR7QAAAWAoARQAlAQA1AAIEgAAIAAROQAAAsg5AeQg7AehQAAgAJ6jWQgEAAgDgDQgDgDAAgEIAAgsQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAAsQAAAEgDADQgDADgEAAIAAAAgAJwjgIAAAAgAqZkSQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzlBQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZmKQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzm5QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZoCQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzoxQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZp6QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzqpQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZryQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzshQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZtqQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzuZQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZviQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzwRQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZxaQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJzyJQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZzSQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJz0BQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZ1KQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJz15QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZ3CQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJz3xQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqZ46QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQACADABAEQgBgEgCgDQgDgDgEAAQgEAAgDADQgDADAAAEIgDAAQg4AAg1gKQg0gLgpgWQgqgWgagiQgbgigEgvQgDgiAUghQATgfAlgYQAjgXAxgPQAwgOA5AAQA4AAA0AKQA1AKAoAXQApAXAbAiQAaAhAEAwQADAigTAgQgTAggkAXQgkAYgwAPQgnALgrACIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAry+wQgTALgMAQQgMAQgFAUQgFAUACATQAFAjAKAgQAIAhAPAYQAPAXAXAOQAWAOAhAAQAYAAATgLQAUgLANgQQAOgQAGgTQAGgUgDgTQgFgjgKggQgJgggQgYQgQgYgYgPQgXgNgiAAQgXAAgTAKgAJz5pQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJz7hQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAgEgDgDQgDgDgEAAQgEAAgDADQgDADAAAEQgzgBgwgKQg0gLgpgVQgqgWgagjQgbgigEgvQgDgiAUggQATggAlgYQAjgXAxgPQAxgPA4AAQA4AAA0ALQA1AKAoAXQApAXAbAiQAaAhAEAwQADAigTAgQgTAggkAXQgkAZgwAOQgsANgzABIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEAInghYQgTALgMAQQgMAQgGAUQgFAUADATQAFAkAJAgQAJAgAPAYQAQAYAWANQAWAOAhAAQAZAAASgLQAUgLANgPQAOgRAFgSQAHgVgDgSQgFgkgJggQgKgggPgYQgRgYgYgOQgXgOghAAQgYAAgTAKg");
	this.shape_26.setTransform(1094.475,664.875);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#D24D34").s().p("EADbAjdQhTAAg5geQg7geAAgsIAAxPIGEAAQA4AAAlgPQAngRAAgXIAAx6IAAgCIIFAAQBSAAA4AgQA8AeAAAsMAAAAiZQAAArg8AeQg4AehSAAgEgQjAjcQhPAAg4geQg8geAAgsIAAxOIDoAAQA4AAAlgPQAkgQAAgYIAAx6IAAgCIDyAAQAAAEADADQADADAEAAQAEAAADgDQADgDAAgEIFcAAIAAACIAAR6QAAAXAoARQAkAPA4AAICEAAIAAROQAAAsg7AeQg5AehTAAgAqBiDQgEAAgDgDQgDgDAAgEIAAgsQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAAsQAAAEgDADQgDADgEAAIAAAAgAqLiNIAAAAgAKiimQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIjuQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKikeQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIlmQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKimWQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIneQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKioOQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIpWQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKiqGQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIrOQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKir+QgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqItGQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKit2QgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIu+QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKivuQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIw2QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKixmQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqIyuQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKizeQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqI0mQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKi1WQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqI2eQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKi3OQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqI4WQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKi5GQgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAqI6OQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAgEgDgDQgDgDgEAAQgEAAgDADQgDADAAAEQg0gBgvgJQg0gLgpgWQgqgWgbgiQgbgigDgvQgDgjAUggQASgfAmgYQAigYAygPQAwgOA5AAQA4AAA0AKQA1AKAoAXQApAXAaAiQAbAiAEAwQADAigTAfQgUAggjAYQgkAYgwAOQgsANgzABIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgLUggEQgTAKgMARQgNAPgFAUQgFAUADAUQAFAjAJAgQAJAhAOAXQAQAYAXAOQAVANAiAAQAZAAASgKQATgLAOgQQANgQAGgTQAGgUgCgTQgGgkgJggQgKgggPgXQgQgZgYgOQgXgOgiAAQgXAAgTALgAKi6+QgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgAKi82QgCgDAAgEIAAg8QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEQAAgEgCgDQgDgDgFAAQgEAAgDADQgCADAAAEQg4AAgzgKQg0gLgpgWQgqgWgbgiQgbgigDgvQgEgiAVghQASgfAmgYQAjgYAxgPQAwgOA5AAQA3AAA1ALQA0AKAoAXQApAWAcAjQAaAhAEAwQADAigUAgQgSAgglAXQgkAYgvAPQgpALgvACIAAA8QAAAEgCADQgDADgFAAQgEAAgDgDgEAJPgisQgUALgLAQQgNAQgFAUQgFAUACATQAGAjAJAgQAIAhAPAXQAQAZAWANQAXANAhAAQAYAAATgKQATgLANgQQAOgQAGgTQAGgUgCgTQgGgjgJggQgKgggPgZQgQgXgYgPQgXgOgiAAQgYAAgSALg");
	this.shape_27.setTransform(1222.1,656.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#E89018").s().p("EADXAqrQg1AAgrgNQgXgHgUgKQg7geAAgrMAAAgiaQAAgsA7geQAUgLAXgIQArgNA1AAIF+AAQAAAEADADQADADAEAAQAEAAADgDQADgDAAgEIBTAAIAAACIAAR8QAAAWAnARQAlAPA1AAIGmAAIAARPQAAAsg7AeQg4AehTAAgEgQcAqrQhTAAg4geQg7gegBgsIAAxPIGEAAQA5AAAkgPQAogRAAgXIAAx7IAAgCIIEAAQBTAAA4AgQA7AeAAAsMAAAAiaQAAArg7AeQg4AehTAAgAJfFKQgEAAgDgDQgDgDAAgEIAAgTQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAATQAAAEgDADQgDADgEAAIAAAAgApUEnQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYD4QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUCvQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYCAQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUA3QgDgDAAgEIAAg7QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA7QAAAEgDADQgDADgEAAQgEAAgDgDgAJYAIQgDgDAAgEIAAg7QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA7QAAAEgDADQgDADgEAAQgEAAgDgDgApUhAQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYhvQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUi4QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYjnQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUkwQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYlfQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUmoQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYnXQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUogQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYpPQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUqYQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYrHQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUsQQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYs/QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUuIQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYu3QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUwAQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYwvQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUx4QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJYynQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApUzwQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJY0fQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgApU1oQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAgEgDgDQgDgDgEAAQgEAAgDADQgDADAAAEQg3AAgzgKQg0gLgqgWQgqgWgagiQgbgigEgvQgDgiAUghQATgfAlgYQAkgYAxgPQAvgOA5AAQAWAAAWACIgBgEQgCgMAGgKIJCt2QAFgIAIgEQAKgDAJACQAKADAGAIIIzLWQAHAJgBALIAAACQgCANgKAHIAAABIAAAAQgIAGgJAAIgBAAIAAAAIgBAAIgBAAIgCgBQgMgBgIgKIgOgSIAOASQAIAKAMABIACABIABAAIABAAIAAAAIABAAQAJAAAIgGIAAAAIAAgBQAKgHACgNIAAgCQAgACAeAGQA1ALApAXQAoAXAcAhQAaAiAEAwQACAigSAgQgTAggkAYQgkAXgwAPQgpAMgvABQAAgDgDgDQgDgDgEAAQgEAAgDADQgDADAAAEQg3gBgzgKQg0gLgqgWQgpgWgagiQgcgigDgvQgDgiAUggQATggAkgYQAkgXAxgPQAngMArgCIoLqjIopNSIgBABIALACQA1AKAoAXQApAWAbAjQAaAhAFAwQADAigUAgQgTAggkAXQgkAYgwAPQgpALguACIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqo7eQgTALgMAQQgMAQgGAUQgFAUADATQAGAjAIAgQAJAhAPAXQAQAZAVANQAYANAgAAQAYAAATgKQAUgLANgQQAOgQAFgTQAGgUgCgTQgFgjgJggQgKgggQgZQgQgXgYgPQgWgOgjAAQgXAAgTALgAIF+GQgTALgMAQQgNAQgFAUQgFAUADATQAFAjAJAgQAJAhAPAYQAQAYAVANQAXANAhAAQAYAAATgKQATgKAOgRQANgQAGgTQAHgUgEgTQgEgjgJggQgLgggPgYQgQgZgYgOQgXgNgiAAQgXAAgTAKgAo074IAGAAIABgBQAMgCAGgKQgGAKgMACIgBABIgGAAIAAAAIgBAAQgHAAgGgEIgBAAIgBgBIAAAAQgJgGgDgJQADAJAJAGIAAAAIABABIABAAQAGAEAHAAIABAAIAAAAgAJY2XQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAJY4PQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAADIAAA9QAAAEgDADQgDADgEAAQgEAAgDgDg");
	this.shape_28.setTransform(1349.25,610.3279);

	var maskedShapeInstanceList = [this.shape_22,this.shape_23,this.shape_24,this.shape_25,this.shape_26,this.shape_27,this.shape_28];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_22}]},4).to({state:[{t:this.shape_23}]},5).to({state:[{t:this.shape_24}]},5).to({state:[{t:this.shape_25}]},5).to({state:[{t:this.shape_26}]},5).to({state:[{t:this.shape_27}]},5).to({state:[{t:this.shape_28}]},5).wait(5));

	// 五线谱
	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#231916").s().p("AhQTWQgwgJgsgWQgtgWgggmQggglgDg3QgDggAGghQAHghARgaQARgaAbgRQAbgRApgDQAYgBAZAIQAYAJAVAQQAWAQANAYQAOAYACAcQADAyghAuQgjAuhTAXQANASAmARQAlARA4AAQA6AAA2gjQA2giAeg1QATgjAAg3QAAg4gHg4QgDgJgFglQgFglgHgoIgQhoQgmAGgqACQgqABgogDQgngEgigGQgjgFgVgLQhngyg/g3Qg/g4gkg8Qgig8gOhAQgOg/gEhAQgFhGARhFQAShFAgg/QAfhAApg1QApg2AqgoQAvgtA1gtQA1gtA/gvIgEgeIgEgcIgGgfQgDgSgCgZIgCgnQgDgdAAgpQgBgpACg0QADg0ALg4QAGgiAWgzQAVg0AegwQAfgwAhgjQAhgjAeAAQAPAAARATQARARARAeQAQAeARAnQAQAmAMAoQAMAoAHAmQAIAoABAdQABBFgGA1QgHA1gOAqQgNAqgSAkIgmBHQgVAkgXAcIgtA3QgXAegaATQgaAUgaAXIAWB6IAIAvIAGAqIAFAgIADAQQAhgEAiADQAiADAfAHQAfAGAZAMQAZAKAPAJQBIA1AeBFQAeBFAGBIQAEA4gOA5QgNA5ggAzQgfA0gyAqQgyArhEAdIAOBlQAHAoAFAmIAIA1QAMBQgDA0QgCAzgRAgQgPAbgUAaQgTAZgbAUQgaAUgkANQgjAOguACIgRABQgcAAglgGgAgkj1QgkAcgrAnQgqAmgrAtQgpAtgbApQgwBMgbBAQgbBAAHBLQAFBUAuBJQAuBJBIAxQBJAyBcAUQBcASBigXIgmjtIgPhXIgNhMQgGgigCgVIgEgUQg2ADgjATQgjATgVAcQgVAbgHAfQgHAfABAYQACAYAJAZQAJAaAPAVQAQAXASASQASASARAJIgEAFIgEAEIgEAGQgpgUgggbQgfgcgJgMIgagkQgKgQgHgSQgHgSgFgWQgEgVgBgdQgDgcAHggQAGggAQggQAPggAZgeQAYgeAigaQARgNAPgIIAZgOQAMgGANgDIAbgIIgojyQgQAKgkAcgAB3CIIBKHTQA6gUAgggQAgggAPgmQAQglACgmQACglgBgdQgDgYgJgkQgJglgYghQgXgigtgWQgmgTg8AAIgTABgABovbQgnAxgZBLQgYBLgIBZQgIBaAMBTQArgiAxgvQAwgvAng2QAng2AZg2QAZg3gEgyQgBgQgEgUQgEgUgKgSQgJgRgOgMQgPgMgXAAQg0AAgoAxg");
	this.shape_29.setTransform(394.7902,448.9798);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#231916").ss(4).p("EBa1gNBICUAAIAJAAEBa1gHxICUAAIAJAAEBa1gCiIAAFMICUAAIAJAAEBdJgCiIAVAAEBdJgCiIAAFMIAAFQEBa1gCiICUAAEBa1gHxIAAFPEBdJgHxIAAFPEBa1AH6ICUAAIAJAAEBa1ACqIAAFQEhdRgCiMB/vAAAIEGAAIOQAAICtAAIDaAAICqAAIOGAAIBBAAIOJAAEhddgHxMCnNAAAIEGAAIM/AAEBa1gNBIAAFQEBdJgNBIAAFQEhddAH6MAu1AAAIEUAAIOfAAICsAAIDbAAICpAAIOWAAIBAAAMBekAAAEhddACqMBXOAAAIDrAAIOaAAICsAAIDbAAICqAAIPVAAIB3AAMA1CAAAEhGdANCIBTAAICsAAIDbAAICqAAIBeAAEhddgNBMC4SAAA");
	this.shape_30.setTransform(921.45,464.575);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#231916").s().p("EhHtALxQg0gMgqgVQgVgLgRgPQgRgOgNgRQgZgggFgrICsAAIisAAIgBgGQgCgiAUghQASgfAlgYQAkgXAxgPQAwgPA4AAQA4AAA0AKQA1ALApAWQAoAYAbAhQAbAiAEAvIiqAAQgEgSgFgSQgKgfgPgZQgRgYgXgNQgXgPgiAAQgXAAgUALQgSALgMAQQgNAPgFAUQgFAVADATIAFAfIAJAkQAJAhAOAYQAFAHAFAGQAMAOAQAKQAWANAiAAQAYAAATgKQATgLAOgQIAAAAQANgRAGgSQAGgUgDgSIgFghICqAAIAAABQACAigSAgQgOAVgUASQgKAJgLAIQgkAYgwANQgxAPg4AAQg5gBg0gJgEgzTAJIQg0gKgpgWQgqgXgbgiQgagigFgvQgCgiAUggQATgfAkgZQAcgSAkgNIEUAAQAbAJAYANQApAXAaAiQAbAiAEAvQADAigTAgQgUAggjAXQgkAZgxAOQgwANg4AAQg5AAg0gKgEgy5AEfQgTALgMAQQgNAQgFAUQgFAUADATQAFAjAJAhQAJAgAOAYQAQAYAWANQAXAOAhAAQAYAAATgLQATgKANgRQAOgPAGgTQAGgUgDgUQgFgjgJggQgKgggPgZQgRgXgXgPQgXgNgiAAQgYAAgSAKgEhEmAJMgEhKtAJMgA+aGgQg0gLgpgVQgqgXgbghQgWgdgHgmIgBgPQgDgiAUggQAKgRAPgOQANgNARgLQAkgYAxgPQAwgOA5AAQAbAAAcACQAbADAaAEQA0AMApAWQAaAPAVATQALALAKALQAaAjAEAvIABAIIiqAAICqAAQAAAegRAcQgTAggkAYQgkAXgwAPQgxAOg4AAQg5AAg0gLgA+sEFIAHAcQAJAgAPAYQAPAYAWANQAXANAhABQAYgBATgJQAUgMANgPQAOgRAFgSQAGgVgCgSIgFgYQgEgXgGgVQgJgggQgYIgJgMQgNgQgSgKQgXgOgiAAQgXAAgTAKQgTALgMAQIgCADQgLAOgFATQgFAUADATIAHAoIitAAICtAAIAAAAgAqSEFIBAAAIgeAAIgiAAgAqSEFQgmgDgkgHQg0gLgqgWQgqgWgagiIgJgNQgTgegDgmQgDgiAUggQATggAlgXQAVgOBNgUIBLgSQhfAPAHgCQApgMAvgBIAQgBQA4AAA0AKQATAEAQAFQAgAKAbAOQAoAYAbAgQAaAiAFAwQACAggQAdIgDAFQgTAggkAXQgkAYgwAOQgjALgoADgArDgtQgSALgMAQIgDACQgLAPgEASQgFAUADASQAFAkAJAgQADANAFANQAHAQAIAPQAQAYAWANQAWANAhAAQAZAAATgKQATgLANgQQAOgQAGgTIACgJQADgPgCgPQgFgjgJggQgKghgPgXQgRgYgXgOQgXgNgiAAQgYAAgTAKgAoIhKIjqAAgAqSEFgA4oEFgA+sEFgEg0LAEFIAVgIQAwgNA4AAQA5AAA0AKQAWAEAUAHgEg0LAEFgAJSBWQg0gLgpgWQgqgWgaghQgYgfgGgpIgBgJQgDgjAUggQATggAlgYQAjgXAxgOQAwgOA5gBQA4ABA0AJQA1ALAoAXQApAWAbAiQAaAiAEAvIAAADIipAAICpAAQADAhgTAfQgTAfgkAXQgkAYgwAOQgxAOg4AAQg4AAg1gKgAI/hKIAJAhQAIAhAPAXQAPAXAXAOQAWANAhAAQAYAAATgKQAUgLANgQQAOgQAGgSQAGgUgDgTIgFgdQgEgUgGgTQgJgfgQgZQgQgYgYgOQgXgOgiAAQgXABgTAJQgTALgMAQQgMARgFATQgFAVACATIAGAiIisAAICsAAIAAAAgAeZhKQgXgDgWgEQg0gLgpgWQgqgVgagjQgbgigEgvQgDgiAUggQATggAlgYQAegUAogOIEGAAQAgAJAaAPQApAXAbAjQAaAhAEAwQADAigTAfQgTAggkAYQgkAYgwAOQgYAIgaADQgbADgcAAQghAAgfgDgEAgQgBKIh3AAgAeGl6QgTAKgMARQgMAPgGAVQgFATADAUQAFAjAJAhQAJAgAPAYQAQAYAWANQAWAOAhAAQAZAAASgLQAUgLANgQQAOgQAFgSQAHgVgDgTQgFgjgJggQgKghgPgXQgRgZgYgOQgXgNghAAQgYAAgTAKgAPDhKgAI/hKgEAyQgD5Qg0gLgpgVQgqgXgagiQgYgegGgnIgBgMQgDgiAUggQATgfAlgZQAjgXAxgQQAwgOA5ABQA3AAA1AKQA0AKApAXQApAXAbAiQAaAhAEAwIAAAFIipAAICpAAQACAggSAdQgTAggkAYQgkAXgwAPQgxANg4AAQg5AAg0gKgEAx+gGXIAHAfQAJAgAPAXQAPAZAWANQAXANAhABQAYAAATgKQAUgMANgQQANgPAGgUQAGgUgCgSIgFgbQgEgVgGgUQgJgggQgYQgQgYgYgOQgXgOgiAAQgXAAgTAKQgTALgMAQQgMAQgGAUQgFAUADATIAHAlIitAAICtAAIAAAAgEBGIgGXIBAAAIgdABIgjgBgEBGIgGXQgmgCgkgHQg0gLgqgWQgpgXgbghQgbgjgDguQgDgjAUggQASggAlgYQAfgUAogOIAOgEQAwgPA4AAQA4ABA0AJQATAEAQAFQAgAKAbAPQAoAXAcAhQAaAiAEAwQACAigSAgQgUAhgjAXQgkAYgwAOQgkAKgoADgEBFYgLKQgTALgMAQQgNAQgFAUQgFAUADATQAFAkAJAfQAJAhAPAYQAPAYAWAOQAXANAhgBQAYABATgLQATgKAOgRQANgPAGgUQAGgUgDgSQgFgkgJggQgKgggPgYQgRgYgXgOQgXgOgiAAQgXAAgTAKgEBISgLnIkFAAgEBGIgGXgEA4BgGXgEAx+gGXgAc7mXIAOgFQAxgOA4AAQA4AAA0ALQASADARAFgAc7mXg");
	this.shape_31.setTransform(956.976,489.1);

	var maskedShapeInstanceList = [this.shape_29,this.shape_30,this.shape_31];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29}]}).wait(39));

	// 键盘
	this.instance = new lib.多余键盘("synched",0);
	this.instance.setTransform(903.15,760.25,1,1,0,0,0,1336.7,123.2);
	this.instance.alpha = 0.1484;

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("EA/KAS1Qg1AAgrgMQgXgHgUgLQg7geAAgrMAAAgiZQAAgsA7geQAUgLAXgHQArgNA1AAIHlAAIAAABIAAR8QAAAXAnAQQAlAQA1AAIGmAAIAARNQAAAsg7AeQg4AehTAAgEArWAS1QhTAAg4geQg7gegBgsIAAxNIGEAAQA5AAAkgQQAogRAAgWIAAx8IAAgBIIEAAQBTAAA4AfQA7AeAAAsMAAAAiZQAAArg7AeQg4AehTAAgEhMPAS1Qg1AAgrgMQgXgHgUgLQg8geABgsMAAAgiXQgBgtA8geQAUgLAXgHQArgNA1AAIHlAAIAAABIAAR8QAAAXAnAQQAlAQA1AAIGnAAIAARNQgBAsg7AeQg4AehTAAgAXXS1QhPAAg4geQg8geAAgsIAAxNIDoAAQA5AAAkgQQAlgPAAgYIAAx8IAAgBIJhAAIAAABIAAR8QAAAWApARQAjAQA5AAICEAAIAARNQAAAsg8AeQg5AehSAAgADeS1QhUAAg4geQg7geAAgsIAAxNIBdAAQA5AAAjgQQAlgPAAgYIAAx8IAAgBIJTAAIAAABIAAR8QAAAWApARQAkAQA1AAIEgAAIAARNQAAAsg5AeQg7AehQAAgAwcS1QhSAAg4geQg8geAAgsMAAAgiYQAAgsA8geQA4gfBSAAIHdAAIAAABIAAR8QAAAWAnARQAlAQA1AAIGvAAIAARNQAAAsg7AeQg5AehTAAgEgkaAS1QhTAAg5geQg4geAAgsIAAxNIGOAAQA1AAAlgQQAogRAAgWIAAx8IAAgBIH8AAQBTAAA5AfQA7AeAAAsMAAAAiYQAAAsg7AeQg5AehTAAgEg4VAS1QhTAAg4geQg7gegBgsIAAxNIBmAAQA4AAAlgQQAkgPAAgYIAAx8IAAgBILuAAIAAABIAAR8QAAAWAoARQAlAQA4AAIB5AAIAARNQABAsg8AeQg4AehTAAg");
	this.shape_32.setTransform(966.55,762.875);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#231916").s().p("EAyZAJ1IgoAAIiEAAQg4AAgkgQQgogRAAgWIAAx7IAAgCQABgVAngPQAogRA0AAIIwAAQA1AAAoARQAmAPABAVIAAACIAAR7QAAAWgnARQglAQg4AAgAeeJ1IgrAAIkgAAQg1AAgkgQQgogRAAgWIAAx7IAAgCQABgVAngPQAkgRA1AAIIzAAQA1AAAoARQAjAPABAVIAAACIAAR7QAAAYgkAPQglAQg4AAgAKgJ1IgmAAImvAAQg1AAglgQQgogRAAgWIAAx7IAAgCQACgVAmgPQAlgRA1AAIIyAAQA1AAAoARQAkAPABAVIAAACIAAR7QAAAYglAPQgkAQg5AAgA9UJ1IgrAAIh6AAQg4AAglgQQgngRAAgWIAAx7IAAgCQABgVAmgPQAogRA1AAIIzAAQA1AAAlARQAmAPABAVIAAACIAAR7QAAAWgnARQglAQg1AAgEgxSAJ1IgnAAImnAAQg0AAglgQQgogQAAgXIAAx7IAAgCQACgVAmgPQAlgRA0AAIIzAAQA2AAAnARQAjAPABAVIAAACIAAR7QAAAYgkAPQgkAQg5AAg");
	this.shape_33.setTransform(901.6,699.9);

	var maskedShapeInstanceList = [this.instance,this.shape_32,this.shape_33];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.instance}]}).wait(39));

	// 键盘bg
	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("rgba(35,25,22,0.4)").s().p("EggQAGNQgQAAgMgLQgLgLAAgQIAArMQAAgQALgMQAMgLAQAAMBAgAAAQAQAAAMALQAMAMgBAQIAALMQABAQgMALQgMALgQAAg");
	this.shape_34.setTransform(950.0157,767.2951,6.6222,3.8413);

	var maskedShapeInstanceList = [this.shape_34];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_34).wait(39));

	// 不动
	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("rgba(153,153,153,0.498)").s().p("AgXB0QAQgaAHgdQAHgeABgfQgBgegHgeQgHgdgQgaIANgFQAPAbAJAdQAKAeAAAiQAAAjgKAeQgJAegPAbg");
	this.shape_35.setTransform(469.75,238.65);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("rgba(153,153,153,0.498)").s().p("AgpBoIgFgEQAJgHAHgJQAHgKAGgMIgJgTQgFgLgDgNIAMgEIAFARQADAJAEAGIAGgZQADgOABgQIghAAIAJgUIAKgYIAJgYIgcAAIAAgOIAuAAIgJAXIgIAYIgKAXIASAAIACAAIAJABQgDAYgEAUQgEAUgGAQQAKANAMAHQANAHAOACQAOADAPAAIAjAAIgEAHIgCAHIgdAAQgRAAgPgCQgPgEgOgGQgNgHgKgNQgGALgHAJQgHAIgIAGIgFgFgAhVBlIgEgFIAEgFIAFgHQACgEAAgFIAAgzIgcAAIAAgOIAcAAIAAgiIgSAAIAAgOIAzAAIAAAOIgUAAIAAAiIAbAAIAAAOIgbAAIAAA1IAZgQIACAGIADAGIgcATIgNAKIgFAEIgEgFgAAzBUIAAgeIgmAAIAAgNIAmAAIAAgUIgfAAIAAgOIAfAAIAAgRIgcAAIAAgNIAcAAIAAgUIgmAAIAAgMIAmAAIAAgUIgcAAIAAgNIAcAAIAAgUIAOAAIAAAUIAhAAIAAAhIALAAIAAAMIgLAAIAAAhIghAAIAAARIAhAAIAAAOIghAAIAAAUIAmAAIAAANIgmAAIAAAegABBgXIAUAAIAAgUIgUAAgABBg3IAUAAIAAgUIgUAAgAhpgrIgFgGQAJgLAGgPQAGgPAEgRIANADIgDAMIgEAMIAoAAIAAAPIguAAIgIAQIgJANIgDgHg");
	this.shape_36.setTransform(454.425,236.95);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("rgba(153,153,153,0.498)").s().p("ABLBeIgdgTQgNAMgSAIQgQAJgXAGIgDgHIgEgHQAUgFAPgHQAQgHAMgKIgZgOIgYgNIAKgSIAKgWIgjAAIAAgOIApAAIAIgUIAGgTIAQADIgGARIgHATIBUAAIAAAOIgaAAQgEAUgHAPQgHAQgKANIAeASIAXAQIgMAMIgWgQgAALASIgIARIAUAKIAUALQAJgLAGgOQAGgOADgRIgvAAIgJASgAhkBmIgDgHIAPAAIAJAAIAEgBIABgDIAAg8IgQAGIgPAEIgEgPIAQgFIATgFIAAg9IghAAIAAgPIAhAAIAAgwIAQAAIAAAwIAaAAIAAAPIgaAAIAAA4IAcgJIADAOIgfAKIAABAQAAAHgCAEQgCAEgFACQgEACgHAAIgUABIgCgIgAgagfIAAguIA7AAIgEgPIgFgOIAQgDIAGAQIAFAQIA4AAIAAAtIgQAAIAAgfIhmAAIAAAgg");
	this.shape_37.setTransform(430.275,236.975);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("rgba(153,153,153,0.498)").s().p("AgvBfIgFgHQASgEASgIQAQgIAQgLQgRgRgOgWQgOgVgJgbQgCAVgGAWQgGAWgMAWQgMAWgWAVQgBgEgEgDIgGgHQATgTALgTQAMgUAFgUQAFgTACgTIABgjIAAgUIgqAAIAAgRICRAAIgGAeIgHAdIAwAAIADgBIAKAFQgHAfgPAXQgOAZgTARQAOAKARAIQARAHAUAEIgGAIIgFAIQgUgGgSgJQgSgIgPgMQgQANgRAIQgSAJgUAGIgEgIgAglhKQAJAnARAeQAPAeAZAWQAQgPANgTQAMgRAHgZIg+AAIAHgaIAIgeIhDAAg");
	this.shape_38.setTransform(406.375,237.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("rgba(153,153,153,0.498)").s().p("AhGBtIAAhdIgMAOIgMAMIgGgGIgFgGQAPgOANgRQAOgSAKgUIAPAFIgIAPIgJAPIAABxgAAUBtIgCgHIgDgIIARAAIANAAIAIAAIAEgBQABgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAhUIhgAAIAAgOIBgAAIAAgbIAPAAIAAAbIAiAAIAAAOIgiAAIAABUQABAJgDADQgCAFgGABQgGACgLAAIgQABIgLAAgAAAA6IgKgRIgLgRIAMgHIALARIALAQIAIAOIgNAIIgIgOgAhkgoIgHgFQALgMAJgQQAJgSAGgSIAPAEIgDAKIgEAKIA9AAIAAAOIgmAAIAHAPIAGANIgOAFIgHgQIgIgRIgOAAIgLATIgMAQIgGgEgAgIgrIgHgEQAMgMAIgPQAKgRAFgSIAPAEIgDAKIgEAKIBNAAIAAAOIgyAAIAJANIAGALIgNAGIgIgOIgKgQIgSAAQgFAKgGAIQgGAIgGAHIgGgFg");
	this.shape_39.setTransform(382.175,236.95);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("rgba(153,153,153,0.498)").s().p("AhIBuIAAhoICTAAIAABoIgRAAIAAgIIhyAAIAAAIgAg4BXIByAAIAAgbIhyAAgAg4AvIByAAIAAgbIhyAAgAhpgPIAAgOIA9AAIgFgSQgEgKgFgJIAPgDIAHAMIAFAOIAEALIgKADIBAAAIAHgNIAGgPIAFgNIARAEIgJATIgJASIA+AAIAAAOgAhchHIAAgPIBYAAIgEgKIgGgKIAPgEIAHANIAFALIBRAAIAAAPg");
	this.shape_40.setTransform(358.425,236.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("rgba(153,153,153,0.498)").s().p("AhlBqIgHgEQAJgRAEgVQAEgTACgUIABglIAAhBIBgAAIgHgOIgHgPIAPgEQAFAIAEAIIAHAQIgDABIBUAAIAAAPIiyAAIAAAyIgBAdQgBAQgCAQQgCARgEAQQgGAQgHANIgGgFgAhEBiIAAgPIBfAAQAMgTAJgWQAKgWAIgVQAHgXAFgUIARAGIgOAoQgIAVgJAUQgJAVgLATIBBAAIAAAPgAgjAeIgJgdIgKgaIANgHIALAcIAKAcIAGAZIgOAHIgHgagAAMARIgGgcIgHgcIANgEIAIAcIAHAbIAGAaIgPAFIgGgag");
	this.shape_41.setTransform(334.3,237);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("rgba(153,153,153,0.498)").s().p("AAeBlIgDgIIAVAAIAMAAIAEgBQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAh+IhEAAIAAgQIBEAAIAAg1IARAAIAAA1IAcAAIAAAQIgcAAIAAB+QgBAIgCAEQgCAFgFACQgGACgJAAIgZABIgCgIgAhnBVIgHgGQAOgJANgQQANgPAKgUIgUgeIgWgeIALgJIAUAaIATAbQAHgPAGgRQAFgSADgTIhJAAIAAgOIBPAAIACgBIAKAEQgEAbgHAZQgHAYgLAUIARAZIALAVIgMALIgKgTIgOgXQgKATgMAOQgMAPgOAKIgFgHgAAYAgQgDgKgHgLIgLgTIANgFIAMASIALAUQAEAKACAIIgOAHQgCgIgFgKg");
	this.shape_42.setTransform(310.25,236.975);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(153,153,153,0.498)").s().p("AgsBcIgDgJIAQAAIANABIAHgBIAFgBIABgDIAAhoIhgAAIAAgRIDRAAIAAARIhhAAIAABoQABAIgDAEQgCAEgGACQgFACgLABIgaAAIgDgIgABQA3IgPgaIgSgZIAPgEIARAXIAQAZQAHANAEALIgQAHQgEgKgGgOgAhjBJIgIgEQAPgNANgTQANgSAIgUIAQADQgJAWgNAVQgNATgPAPIgHgGgAhQhUIAAgPICnAAIAAAPg");
	this.shape_43.setTransform(286.125,237.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("rgba(153,153,153,0.498)").s().p("AhsBiIAAgPIBLAAIAAhQIAPAAIAABQIAjAAIAAhQIAQAAIAABQIBMAAIAAAPgAhEA2IgKgRIgKgRIANgGIAKARIAKARQAFAIADAHIgOAGIgHgPgAArA+IAMgQIAMgRIAKgRIANAHQgHANgKANQgJANgJAJgAhOgGIAAhbICdAAIAABbgAg+gSIB9AAIAAgbIh9AAgAg+g6IB9AAIAAgaIh9AAg");
	this.shape_44.setTransform(262.4,237);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("rgba(153,153,153,0.498)").s().p("AgGAEQgOgNgNgLIAOgMIASAQIASASIARASIgPANQgLgPgOgOg");
	this.shape_45.setTransform(204.35,244.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("rgba(153,153,153,0.498)").s().p("ABDBtIAAgOIiVAAIAAhMIAQAAIAAA9IA7AAIAAhQIhfAAIAAgQIBfAAIAAgnIhNAAIAAgPIBNAAIAAgmIAPAAIAAAmIBPAAIAAAPIhPAAIAAAnIBfAAIAAAQIhfAAIAABQIA7AAIAAg9IAQAAIAABag");
	this.shape_46.setTransform(150.225,237);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("rgba(153,153,153,0.498)").s().p("AhrBmIANgNIALgRQAFgJAEgJIAPAEQgGAPgJANQgJANgKAKgABVBcIgLgSIgMgQIAOgFIAMAQIAMARIAIAPIgPAGIgIgPgAgfBdIgCgRIgDgQIAQgBIADAQIACAQIABANIgQADIgBgOgAAaBcIgGgQIgHgPIAOgEIAIAQIAGAQIAEAOIgPAEIgEgPgAhNAmIAAhJIBFAAIAAhJIAPAAIAAAaIBbAAIAAAPIhbAAIAAAgIBJAAIAABJgAg+AYIB+AAIAAgtIh+AAg");
	this.shape_47.setTransform(126.125,237);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("rgba(153,153,153,0.498)").s().p("AgNBBQgKgeABgjQgBgiAKgeQAJgdAPgbIANAFQgQAagIAdQgGAegBAeQABAfAGAeQAIAdAQAaIgNAGQgPgbgJgeg");
	this.shape_48.setTransform(110.85,238.65);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("AgoCVQgQgQAAgYQAAgYAQgRQARgQAXgBQAZABAQAQQAQARAAAYQAAAYgQAQQgQAQgZABQgXgBgRgQgAgohDQgQgRAAgXQAAgZAQgQQARgQAXgBQAZABAQAQQAQAQAAAZQAAAXgQARQgQAPgZABQgXgBgRgPg");
	this.shape_49.setTransform(603.4,185.075);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("AgyEBQgCgOgGgHQgFgIgJgHQgKgGgWgEIAAgHIAIABIASABIAUABIAPABQAFAAADgDQACgDAAgFIAAiBIhDAMIhIANIgIAIQgEADgEACIgohZIAGgBIANgCIAOgCQAggJAkgNQAlgPAlgTQAmgTAigWIhNAUIhcAWIgGAFIgGAEIgohYIAJgBIAOgEQATgEAUgJQAUgJAUgNQATgMARgNIhfADIhcAAIAAgJQA2gHA7gLQA8gLA6gNQA6gNAzgOQAygNAlgNIBQBSQgGAEgLAAQgMAAgRgHQgnAGgwAEIhnAIIAtAZQgDAEgFACQgGACgKgCQgVAJgbAJQgcAJggAHQgfAIgfAGIBYAAIBogBQAVgPARgNQARgOAMgLIBXBCQgEAEgHACQgHACgLgDQgZAOglAQQgkAQgsAQQgsAPgtAPQgvANgtAMQA4gBBJgCICbgFQgOgQgOgOQgPgPgOgLIAEgEQBGAHAoAVQAnATAOAaQAPAZgFAWQgFAUgTAJQgSAJgagOQgHgRgKgRQgLgTgNgRIgwALIg4AMIAACVQAAAagHATQgHATgXALQgVALgtADIgDgggAkNEDQAbgXAZgfQAYgdATgfQAUgfALgaIBhA5QgDAEgFACQgFADgLgCQgiAigyAdQgzAfg8ATgAC6D6QgJgbgRgcQgRgbgWgZQgWgZgWgSIAFgFQA9AHAmASQAnARASAWQATAWADAVQADAWgJAPQgJAQgSADIgJABQgOAAgSgJg");
	this.shape_50.setTransform(554.9141,180.9);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("AkeEYQBPglAvgpQAtgpAWgrQAWgrAHgtIjTAAIgEgRIDZAAIABgUIAAgVIAAhaIivAAIgFgQIERAAQAJgXAGgbIANg0IAJgvIB0AiQgCAGgFADQgGADgKgBQgUAYgeAbQgeAcghAZIBGAAIAug6IAPALIAhAZIAkAdQgBAFgFACQgFACgHAAIjFAAIAABZIgCAqIBzAAIAxg7IAPAMIAiAaIAmAcQgBAFgFADQgFACgHAAIjjAAQAYAtAmAgQAnAhAwAVQAwAVA0AKIgBAHQgaAHgSAWQgUAWgHAiQhLgigtg7Qgsg8gWhgQgFAkgRAkQgRAkgjAiQgiAhg7AcQg6AbhYATgAh5idQgEgggOggQgNgfgSgYIAEgDQA7AJAeAUQAeAUAGAXQAHAXgKASQgLASgVAEIgIABQgSAAgTgOg");
	this.shape_51.setTransform(496.2,180.875);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("AjHEeIAAjoQgSAZgTAVQgVAWgXAUIgIgGQAWgjAPgpQAQgqAKgtQALgtAGguIhIAAIgEgRIBVAAIAAiWIBmAKQAAAHgFAEQgFAEgMACIAAB4IAhgwIAJAIIAVAVIAZAYQAJgkAIgnQAIgnAEglIBtAeQgBAFgHAEQgFADgKAAIgQAmIgSAjIB+AAIArgrIBFA+QgDAFgHADQgGADgLACQgCBfgDBDQgDBEgGAtQgGAtgJAbQgJAcgOANQgRASgXAIQgVAHggABQABgVgDgNQgEgPgGgIQgJgJgPgIQgPgIgWgEIABgIIAdADIAeACIAUAAQAJAAAEgCQAGgCAFgEQARgPAHhUQAIhVAEicIiPAAQgUAigWAcQgYAbgbAWIgGgEIAMgjIAMgmIgDAAIgEAAIhNAAIAAA1QAsAOAUATQAVAUADASQACATgKANQgJANgRACQgRACgSgRQABgWgFgWQgGgWgJgUIAAE1QgBAEgJAFQgJAHgQADQgOAGgPAAgAguBKIAIgDQAHgCAEgEQAKgMAJgYQAJgWAJgbQAJgcAGgbQAHgcACgVIBiAqQgCAEgFADQgGADgIAAQgNAYgTAaQgSAagUAZQgVAbgUATIArgDIAzgFIgMgnIgLgjIAHgBQAqAWAVAaQAUAZADAYQADAXgJAOQgJAPgQADQgQABgRgQIgBgUIgCgUIgqAZQgWANgbAOQgDAFgDAEIgJAGg");
	this.shape_52.setTransform(436.3,180.95);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AghEdIAAkQIBVAhIBjAAIAngsIBIA3QgDAEgGADQgFADgLABIAADDQABACgJAFQgHAEgQADQgQADgWABIgOAAIAAgzIhsAAIAAAlQgBAEgQAIQgSAGgeAAgAAuDVIBsAAIAAiWIhsAAgAkgClQAWgCAmgIIBYgSIBigVIABAEQgcAYgvAgQgvAhhFAoQgDAHgFAFQgFAEgFACgAkgAhIAFgBIAKgDIAKgFQASgLATgWQAUgWAUgdIgaANIgbAOIgHAGIgGADIgmhbIAFgBIAJgDIAJgEQALgJANgTQAMgUAMgXQAMgXAKgXQAKgXADgTIBqAqQgDAFgFACQgEADgJAAQgPAUgXAVQgWAVgYAUQgYAUgYAPIAmgBIAqgCIAQggQAHgPAFgNIBiA0QgCAEgGADQgGACgJAAQgTAXgcAaQgdAbggAaQghAZggAUIBLgIIBXgJIABAHQgbAQgtAYQguAXg7AbIgHAIQgEADgEACgAgpgWIgFgRIBkAAIAAhsIhzAAIgGgQIB5AAIAAh5IBqAIQAAAGgFAFQgFAEgMADIAABfIArAAIAngzIAMAKIAdAWIAeAaQgCAFgEACQgEACgHAAIiIAAIAABsIAeAAIAngyIAMAKIAbAWIAdAZQgBAFgEADQgEACgHAAg");
	this.shape_53.setTransform(376.3,181.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#333333").s().p("AkREeIAAorIBXAgIAiAAIApgoIBOBHQgDAFgGACQgHACgLAAQgLATgPAYQgQAYgRAYQgSAYgRAUQAjATAWAZQAWAYALAcQAKAcAAAZQABAfgKAWQgJAWgWANQgWAMglABIgBgaIgDgZQgCgLgCgGQgEgGgGgEQgHgFgKgDIAAgGIAiAAIAHgBIAFgCQAFgEADgHQADgHAAgNQAAgfgJgfQgJgggUgcIAIgxQAFgcAEgdIAGg2IgwAAIAAHhQAAADgIAGQgIAGgOAFQgOAFgVAAgAiAEYQAoggAVgmQAUgnAHgqQAGgpAAgpIAAh0IBmAJQgBAHgEAEQgFAEgKABIAABbQgBAigHAjQgHAigTAgQgRAggiAbQgiAag1ASgABlEaIAAleIBYAIQgggigXgvQgXgvgKg2QgSAtghAoQggAogoAgQgqAggtAVIgEgEQAZgYAXgfQAXgfASgjQATgiALghQAMghAEgcIBvAYQgBAFgFAEQgGADgNABQARAgAbAZQAbAZAhARQAgASAeAJIAAAIQgZAJgPAVQgOAWgDAaIgIgHIgJgHIgFAEIgKACIAAEwQAAAEgLAFQgKAFgPAEQgQAEgQAAg");
	this.shape_54.setTransform(317.675,180.925);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#333333").s().p("AixEdIAAkpIBbAiICnAAIApgsIBTA/QgEAEgGADQgFAEgLADIAADHQgBAEgLAGQgMAHgRAFQgSAGgQAAIgQAAIAAgsIizAAIAAATQABAFgMAHQgLAGgQAFQgRAFgTAAgAhbDeICzAAIAAhUIizAAgAhbB5ICzAAIAAhSIizAAgAkRglIgFgRIE2AAIAPgpIAMgsIAKgqIjFAAQAwAOAVAUQAVAVABAUQABAVgLAOQgNAOgUABQgTABgVgSQgBgdgIgcQgHgcgMgXIhiAAIgGgQIDwAAIgKgEIgKgGQgDgWgJgTQgJgUgLgOIAEgCQAzgCAYALQAaALAFAQQAFARgKAOQgJAOgSAGIB3AAIAsg6IAPAMIAeAZIAjAcQgCAFgFACQgEACgHAAIiXAAIBcAcQgBAGgFADQgGADgKgBQgVAUgfAYQgfAYgfAUIBsAAIAtg7IAPALIAhAaIAiAdQgBAFgFACQgFADgGAAg");
	this.shape_55.setTransform(256.4,180.816);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#333333").s().p("ACjD5QgCgOgHgJQgGgIgKgHQgLgHgVgDIAAgIIAIABIAUABIAXABIAQABQAHAAADgEQACgDAAgFIAAimIgIAGQgFACgHACIAAB6QgBACgIAEQgJAEgNADQgMADgLAAIgLAAIAAgcIgfAAIAAAWQABADgJAEQgIAFgMAEQgNADgOAAIgJAAIAAjLIBCAaIAYAAIAdggIA9AtIAAgzIgBAAIi9AAIgBgEIAAADQAAApgEArQgDArgOApQgNAqgeAlQgdAlgyAfIgGgFQAcgkAPgoQAOgpAHgrIgfAvQgSAbgYAfQgEAPgGAKQgHALgIAFIg7hXQAWgNAIgIQAGgIAAgKIAAj0IhEAAIgFgQIBKAAIAlglQgGAAgFgDIgMgGQgHgdgOgbQgQgcgQgVIAFgDQAxAFAbAPQAbAOAKASQAKARgEARQgDAQgNAJQgMAJgTgCIBCA3QgCADgHADQgGADgMACIAADXIAXgNIAXgNQADgfACghQABgggBghIAAjqIBYAfICuAAIAigoIBJA4QgEAEgGAEQgGADgJACIAAGSQABAbgGASQgHASgUALQgVALgoAEQgBgTgEgNgABFB6IAfAAIAAhnIgfAAgAB0g0IAEAAIAdgvIALAMIAZAaIAAhEIgFADIgGABIg6AAgAgGg0IA2AAIAAhJIgvAAIgDgRIAyAAIAAhFIBUAJQgBAFgDADQgEAEgIABIAAAvIACAAIAagpIAHAHIAQARIASAUIAAhUIi/AAg");
	this.shape_56.setTransform(196,181.225);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#333333").s().p("ACBDUQgigpgUguQgWgvgMgxQgMgvgGgtQgGA2gRAxQgSAxghAsQgiAsg4AmQg4AmhUAfIgEgIQA8gnApgqQAogrAYgtQAZgtAMgwQAMgvAEg0IjQAAIgFgRIDWAAQADgrAAgtIAAhdIB3ALQgBAHgFAEQgFAFgLACIgCBNQgBAngDAkIBzAAIAyg/IAQAMIAkAcIAmAeQgBAFgGACQgEADgHAAIjqAAQAKA3AdAyQAeA0A1ArQA1ArBQAeIAAAIQgiAGgTAWQgUAWgEAmQgwgfgggpg");
	this.shape_57.setTransform(136.35,181.125);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("rgba(35,25,22,0.6)").s().p("EBGQAPRQgDgDAAgEIAAgUQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAAUQAAAEgDADQgDADgEAAQgEAAgDgDgAe4PRQgDgDAAgEIAAgsQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAAsQAAAEgDADQgDADgEAAQgEAAgDgDgA9NPRQgDgDAAgEIAAgaQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAAaQAAAEgDADQgDADgEAAQgEAAgDgDgAqRPGQgDgCAAgEIAAg8QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgEhGdAPFQgDgCAAgFIAAgkQAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAAkQAAAFgDACQgDADgEABQgEgBgDgDgEAzjAOxQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIAOvQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqOZQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQAOBQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MN7QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4NpQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEhGdANmQgDgDAAgEIAAg9QAAgEADgDQADgCAEgBQAEABADACQADADAAAEIAAA9QAAAEgDADQgDACgEABQgEgBgDgCgAqRNOQgDgCAAgFIAAg7QAAgFADgCQADgDAEgBQAEABADADQADACAAAFIAAA7QAAAFgDACQgDADgEAAQgEAAgDgDgEAzjAM5QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIAM3QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqMhQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQAMJQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MMDQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4LxQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEhGdALtQgDgCAAgFIAAg7QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA7QAAAFgDACQgDADgEABQgEgBgDgDgAqRLXQgDgDAAgEIAAg9QAAgEADgDQADgCAEgBQAEABADACQADADAAAEIAAA9QAAAEgDADQgDACgEAAQgEAAgDgCgEAzjALBQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIAK/QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqKpQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQAKRQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MKLQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4J5QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEhGdAJ2QgDgDAAgFIAAg8QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA8QAAAFgDADQgDACgEAAQgEAAgDgCgAqRJeQgDgCAAgEIAAg8QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgEAzjAJJQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIAJHQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqIxQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQAIZQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MITQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4IBQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEhGdAH+QgDgDAAgEIAAg9QAAgEADgDQADgCAEgBQAEABADACQADADAAAEIAAA9QAAAEgDADQgDACgEABQgEgBgDgCgAqRHmQgDgCAAgFIAAg7QAAgFADgCQADgDAEgBQAEABADADQADACAAAFIAAA7QAAAFgDACQgDADgEAAQgEAAgDgDgEAzjAHRQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIAHPQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqG5QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQAGhQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MGbQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4GJQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEhGdAGFQgDgCAAgFIAAg7QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA7QAAAFgDACQgDADgEABQgEgBgDgDgAqRFvQgDgDAAgEIAAg9QAAgEADgDQADgCAEgBQAEABADACQADADAAAEIAAA9QAAAEgDADQgDACgEAAQgEAAgDgCgEAzjAFZQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIAFXQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqFBQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQAEpQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MEjQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4ERQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEhGdAEOQgDgDAAgFIAAg8QAAgEADgCQADgDAEgBQAEABADADQADACAAAEIAAA8QAAAFgDADQgDACgEAAQgEAAgDgCgAqRD2QgDgCAAgEIAAg8QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgEAzjADhQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIADfQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqDJQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQACxQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MCrQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4CZQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqRB+QgDgCAAgFIAAg7QAAgFADgCQADgDAEgBQAEABADADQADACAAAFIAAA7QAAAFgDACQgDADgEAAQgEAAgDgDgEAzjABpQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEgyIABnQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqBRQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQAA5QgDgDAAgEIAAg7QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA7QAAAEgDADQgDADgEAAQgEAAgDgDgA9MAzQgDgDAAgEIAAg7QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA7QAAAEgDADQgDADgEAAQgEAAgDgDgAe4AhQgDgDAAgEIAAg7QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA7QAAAEgDADQgDADgEAAQgEAAgDgDgAqRAHQgDgDAAgEIAAg8QAAgEADgDQADgCAEgBQAEABADACQADADAAAEIAAA8QAAAEgDADQgDACgEAAQgEAAgDgCgEAzjgAOQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqgmQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgA+QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgA9MhEQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4hWQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqRhxQgDgCAAgEIAAg8QAAgFADgDQADgCAEAAQAEAAADACQADADAAAFIAAA8QAAAEgDACQgDADgEABQgEgBgDgDgEAzjgCGQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqieQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgC2QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4jOQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAqRjpQgDgCAAgFIAAg7QAAgFADgCQADgDAEgBQAEABADADQADACAAAFIAAA7QAAAFgDACQgDADgEAAQgEAAgDgDgEAzjgD+QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqkWQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgEuQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4lGQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEAzjgF2QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAKqmOQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgGmQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4m+QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEAzjgHuQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgIeQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgAe4o2QgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEAzjgJmQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgKWQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEAzjgLeQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgMOQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDgEBGQgOGQgDgDAAgEIAAg8QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAA8QAAAEgDADQgDADgEAAQgEAAgDgDg");
	this.shape_58.setTransform(959.625,545.35);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#E89018").s().p("ABSA4IAAgEIgyAAIAAAEIgLAAIAAg1IBIAAIAAA1gAAgArIAyAAIAAgMIgyAAgAAgAXIAyAAIAAgLIgyAAgAg9A4IAAghIgtAAIAAgLIAtAAIAAgRIgmAAIAAgLIAmAAIAAgmIAKAAIAAAmIAoAAIAAALIgoAAIAAARIAuAAIAAALIguAAIAAAhgAAHgGIAAgKIAbAAIgDgIIgDgHIAKgCIAEAIIADAJIgCAAIAaAAIAEgJIADgJIg/AAIAAgKIAoAAIgCgFIgDgEIALgCIADAFIACAGIAmAAIAAAKIgZAAIALADIgEAIIgDAHIAaAAIAAAKgAhXgdIgEgJIgGgJIAKgEIAGAJIAEAJIAEAIIgLAFIgDgJgAgmgYIAEgJIAFgKIADgJIALAEIgHAPIgHAMg");
	this.shape_59.setTransform(228.55,238.625);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FCF0D9").s().p("AhiBbQgSAAgMgNQgNgNAAgSIAAhdQAAgSANgNQAMgNASAAIDFAAQASAAANANQAMANAAASIAABdQAAASgMANQgNANgSAAgABTA2IAAAEIALAAIAAg2IhIAAIAAA2IALAAIAAgEgAhpAYIAsAAIAAAiIALAAIAAgiIAuAAIAAgLIguAAIAAgQIAnAAIAAgLIgnAAIAAgnIgLAAIAAAnIglAAIAAALIAlAAIAAAQIgsAAgAAHgEIBlAAIAAgKIgbAAIAEgIIADgIIgKgCIAZAAIAAgKIgmAAIgCgGIgDgGIgLACIACAFIACAFIgnAAIAAAKIA/AAIgDAJIgEAJIgaAAIABgBIgCgIIgEgJIgLACIAEAIIACAIIgbAAgAhgguIAFAJIAFAKIADAIIAKgEIgDgJIgFgJIgFgJgAgdgpIgEAKIgFAIIAKAEIAHgNIAHgOIgLgEIgEAJgAAhAsIAAgLIAyAAIAAALgAAhAYIAAgLIAyAAIAAALg");
	this.shape_60.setTransform(228.475,238.475);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#D24D34").s().p("ABXA6IAAgFIg0AAIAAAFIgLAAIAAg4IBLAAIAAA4gAAjAsIA0AAIAAgLIg0AAgAAjAYIA0AAIAAgLIg0AAgAhqA3IAAgLIAsAAIAAgSIgdAAIAAgKIAdAAIAAgQIgeAAIAAgIIgHAEIgGADIgDgFIgEgEQALgFAJgHQALgIAIgIQAJgJAGgKIAKAFIgBABIgBACQAKANANAJQANAKAOAHIgEAEIgEAGIgGgEIgGgEIAAAIIgeAAIAAAQIAdAAIAAAKIgdAAIAAASIAsAAIAAALgAhIgYIgRAOIBCAAQgKgHgHgHIgRgQIgPAQgAAIgGIAAgKIAcAAIgCgIIgDgIIAKgCIAFAJIADAIIgCABIAbAAIAEgKIADgJIhCAAIAAgKIAqAAIgDgFIgCgFIALgBIAEAFIACAGIAnAAIAAAKIgaAAIAMADIgFAIIgDAIIAbAAIAAAKg");
	this.shape_61.setTransform(180.35,238.65);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FAEDEA").s().p("AhmBeQgTAAgNgOQgNgNAAgTIAAhfQAAgTANgOQANgNATAAIDNAAQATAAANANQANAOAAATIAABfQAAATgNANQgNAOgTAAgABWA3IAAAEIALAAIAAg3IhLAAIAAA3IALAAIAAgEgAhsA4IBkAAIAAgKIgsAAIAAgSIAeAAIAAgLIgeAAIAAgRIAeAAIAAgHIAGAEIAHADIADgEIAEgFQgOgHgNgJQgMgKgLgNIABgBIABgCIgKgFQgGAKgIAJQgJAJgKAHQgKAHgLAFIAEAFIADAEIAHgDIAGgEIAAAHIAeAAIAAARIgdAAIAAALIAdAAIAAASIgsAAgAAHgFIBpAAIAAgKIgcAAIAEgIIAEgIIgMgCIAaAAIAAgLIgnAAIgCgGIgDgFIgLACIACAEIACAFIgpAAIAAALIBBAAIgDAJIgEAJIgbAAIACAAIgDgJIgFgJIgKACIADAIIADAIIgcAAgAAhAtIAAgLIA1AAIAAALgAAhAZIAAgLIA1AAIAAALgAhbgJIASgOIAPgQIAQAQQAIAIAJAGg");
	this.shape_62.setTransform(180.525,238.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35}]}).wait(39));

	// bg
	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("EiLsBMwQhvAAhQhPQhPhPAAhwMAAAiRDQAAhwBPhPQBQhPBvAAMEXZAAAQBvAABPBPQBQBPAABwMAAACRDQAABwhQBPQhPBPhvAAg");
	this.shape_63.setTransform(959.9897,540.0003,0.9999,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_63).wait(39));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(999,588.8,882,442.5);
// library properties:
lib.properties = {
	id: '14CB93263BA1D74EA5B3F38304C0AC64',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FF9999",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['14CB93263BA1D74EA5B3F38304C0AC64'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;